import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";

import { checkRuntimeDetach, formatRuntimeDetachReport } from "../../src/skills/runtime-detach.ts";

const tempRoots: string[] = [];

function makeRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "kata-runtime-detach-"));
  tempRoots.push(root);
  return root;
}

function writeRuntimeFile(root: string, rel: string, body: string): void {
  const path = join(root, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body, "utf8");
}

function writeDetachedEntries(root: string): void {
  const shared = [
    "Claude 与 Codex 同等优先。",
    "修改任一 runtime 必须同步评估另一套。",
    "不得把 `.ai` 作为当前规范来源。",
  ].join("\n");
  writeRuntimeFile(root, "AGENTS.md", `# AGENTS.md\n\n${shared}\n`);
  writeRuntimeFile(root, "CLAUDE.md", `# CLAUDE.md\n\n${shared}\n`);
}

function writeSkill(
  root: string,
  runtimeDir: ".claude" | ".agents",
  name: string,
  body = "",
): void {
  writeRuntimeFile(
    root,
    `${runtimeDir}/skills/${name}/SKILL.md`,
    `---\nname: ${name}\ndescription: example\n---\n# ${name}\n${body}\n`,
  );
}

describe("runtime detach check", () => {
  afterEach(() => {
    for (const root of tempRoots.splice(0)) {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("passes detached runtime entries and clean skills", () => {
    const root = makeRoot();
    writeDetachedEntries(root);
    writeRuntimeFile(root, ".claude/INDEX.md", "# Claude index\n");
    writeRuntimeFile(root, ".agents/INDEX.md", "# Codex index\n");
    writeSkill(root, ".claude", "case-draft");
    writeSkill(root, ".agents", "case-draft");

    const report = checkRuntimeDetach(root);
    expect(report.passed).toBe(true);
    expect(report.violations).toEqual([]);
    expect(formatRuntimeDetachReport(report, root)).toBe("runtime detach passed");
  });

  test("flags CLAUDE.md symlink and CLAUDE.local.md", () => {
    const root = makeRoot();
    writeRuntimeFile(root, "AGENTS.md", "# AGENTS.md\n");
    symlinkSync("AGENTS.md", join(root, "CLAUDE.md"));
    writeRuntimeFile(root, "CLAUDE.local.md", "# local\n");

    const report = checkRuntimeDetach(root);
    expect(report.passed).toBe(false);
    expect(report.violations.some((v) => v.rule === "RUNTIME_ENTRY_SYMLINK")).toBe(true);
    expect(report.violations.some((v) => v.rule === "RUNTIME_LOCAL_ENTRY_PRESENT")).toBe(true);
  });

  test("flags missing synchronization rule in entry files", () => {
    const root = makeRoot();
    writeRuntimeFile(root, "AGENTS.md", "# AGENTS.md\n");
    writeRuntimeFile(root, "CLAUDE.md", "# CLAUDE.md\n");

    const report = checkRuntimeDetach(root);
    expect(report.violations.some((v) => v.rule === "RUNTIME_SYNC_RULE_MISSING")).toBe(true);
  });

  test("flags generated markers and active ai-core references", () => {
    const root = makeRoot();
    writeDetachedEntries(root);
    writeRuntimeFile(
      root,
      ".agents/skills/case-edit/SKILL.md",
      [
        "---",
        "name: case-edit",
        "description: example",
        "---",
        "<!-- generated by kata ai-core; do not edit -->",
        "<!-- ai-core-hash: abc123 -->",
        "详见 .ai/core/skills/case-draft/references/output-standard.md",
      ].join("\n"),
    );

    const report = checkRuntimeDetach(root);
    expect(report.violations.some((v) => v.rule === "RUNTIME_GENERATED_MARKER")).toBe(true);
    expect(report.violations.some((v) => v.rule === "RUNTIME_AI_CORE_REFERENCE")).toBe(true);
  });

  test("formats detach failures with relative paths", () => {
    const root = makeRoot();
    writeRuntimeFile(root, "AGENTS.md", "# AGENTS.md\n");
    writeRuntimeFile(root, "CLAUDE.md", "# CLAUDE.md\n");

    const text = formatRuntimeDetachReport(checkRuntimeDetach(root), root);
    expect(text).toContain("runtime detach failed");
    expect(text).toContain("AGENTS.md");
  });
});
