// spec: features/2099-01-lt-dq-main-flow/岚图主流程用例整理.md#L8402,#L8496,#L8589,#L8682,#L8775,#L8868,#L8961,#L9055,#L9192,#L9330,#L9423,#L9517,#L9610,#L9703,#L9796,#L9889,#L9982,#L10075,#L10168,#L10261,#L10354,#L10448,#L10541,#L10634,#L10773,#L10911,#L11004,#L11097,#L11190,#L11284,#L11378,#L11472,#L11566,#L11705,#L11799,#L11893,#L12031,#L12169,#L12262,#L12355,#L12448,#L12541,#L12634,#L12727,#L12865
// intent: SR-INTENT-2099-01-DQ-SPARKTHRIFT-VALIDATION-L8402-L12865
// probe: SR-UI-PROBE-20260527-DQ-SPARKTHRIFT-COMPLETENESS-001
// page: _shared/pages/2099-01-lt-dq-main-flow/data-quality-page.ts
// generated_at: 2026-05-27T00:00:00Z
// SourceRefs: SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L8402, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L8496, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L8589, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L8682, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L8775, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L8868, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L8961, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L9055, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L9192, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L9330, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L9423, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L9517, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L9610, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L9703, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L9796, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L9889, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L9982, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10075, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10168, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10261, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10354, SR-2099-01-DQ-SPARKTHRIFT-UNIQUENESS-L10448, SR-2099-01-DQ-SPARKTHRIFT-UNIQUENESS-L10541, SR-2099-01-DQ-SPARKTHRIFT-UNIQUENESS-L10634, SR-2099-01-DQ-SPARKTHRIFT-UNIQUENESS-L10773, SR-2099-01-DQ-SPARKTHRIFT-STATISTICAL-L10911, SR-2099-01-DQ-SPARKTHRIFT-STATISTICAL-L11004, SR-2099-01-DQ-SPARKTHRIFT-STATISTICAL-L11097, SR-2099-01-DQ-SPARKTHRIFT-CUSTOMSQL-L11190, SR-2099-01-DQ-SPARKTHRIFT-CUSTOMSQL-L11284, SR-2099-01-DQ-SPARKTHRIFT-CUSTOMSQL-L11378, SR-2099-01-DQ-SPARKTHRIFT-CUSTOMSQL-L11472, SR-2099-01-DQ-SPARKTHRIFT-CUSTOMSQL-L11566, SR-2099-01-DQ-SPARKTHRIFT-CUSTOMSQL-L11705, SR-2099-01-DQ-SPARKTHRIFT-CUSTOMSQL-L11799, SR-2099-01-DQ-SPARKTHRIFT-CONSISTENCY-L11893, SR-2099-01-DQ-SPARKTHRIFT-CONSISTENCY-L12031, SR-2099-01-DQ-SPARKTHRIFT-TIMELINESS-L12169, SR-2099-01-DQ-SPARKTHRIFT-TIMELINESS-L12262, SR-2099-01-DQ-SPARKTHRIFT-REASONABLENESS-L12355, SR-2099-01-DQ-SPARKTHRIFT-REASONABLENESS-L12448, SR-2099-01-DQ-SPARKTHRIFT-REASONABLENESS-L12541, SR-2099-01-DQ-SPARKTHRIFT-REASONABLENESS-L12634, SR-2099-01-DQ-SPARKTHRIFT-REASONABLENESS-L12727, SR-2099-01-DQ-SPARKTHRIFT-REASONABLENESS-L12865, SR-UI-PROBE-20260527-DQ-SPARKTHRIFT-COMPLETENESS-001
import { test } from "../../../../_shared/fixtures/step-screenshot";
import {
  expectSparkThriftQualityRuleValidationContract,
  type SparkThriftQualityRuleValidationScenario,
} from "../../../../_shared/pages/2099-01-lt-dq-main-flow/data-quality-page";
import { ensureSelectedDtstackPreconditionTables } from "../helpers/dtstack-preconditions";

test.setTimeout(90 * 60 * 1000);

const PRECOND_TABLES_FILE =
  "workspace/dataAssets/features/2099-01-lt-dq-main-flow/tests/fixtures/precond/sparkthrift-rule-validation-tables.yaml";

const scenarios: readonly SparkThriftQualityRuleValidationScenario[] = [
  {
    archiveLine: 8402,
    title: "完整性校验-字段级-空值数",
    tableName: "dwd_voyah_dq_rule_01_main",
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "空值数",
    fields: ["car_model_name"],
    expectation: { method: "固定值", operator: "=", value: "0" },
    description: "校验空值数分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_01_F003", "car_model_name"],
    fusionChecks: {
      ruleSetListAndConfiguredTableFilter: true,
      t1BeforeImmediateWithEnvParams: [
        { name: "logLevel", value: "ERROR" },
        { name: "spark.executor.cores", value: "2" },
        { name: "spark.executor.instances", value: "2" },
        { name: "spark.executor.memory", value: "2g" },
        { name: "spark.sql.shuffle.partitions", value: "10" },
        { name: "spark.network.timeout", value: "300s" },
        { name: "spark.driver.maxResultSize", value: "2g" },
      ],
      passHasNoDirtyDetail: true,
    },
  },
  {
    archiveLine: 8496,
    title: "完整性校验-字段级-空值率",
    tableName: "dwd_voyah_dq_rule_02_main",
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "空值率",
    fields: ["car_model_name", "owner_phone"],
    fieldLogic: "or",
    expectation: { method: "固定值", operator: "<", value: "1%" },
    description: "校验空值率分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0%",
    failExpectedValue: "25%",
    dirtyEvidence: ["ORD_02_F003", "car_model_name"],
    fusionChecks: {
      ruleSetDetail: true,
      taskDetectionToggle: true,
    },
  },
  {
    archiveLine: 8589,
    title: "完整性校验-字段级-空串数",
    tableName: "dwd_voyah_dq_rule_03_main",
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "空串数",
    fields: ["delivery_center"],
    expectation: { method: "固定值", operator: "!=", value: "1" },
    description: "校验空串数分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_03_F003", "delivery_center"],
    fusionChecks: {
      ruleSetPackageNameManagement: true,
    },
  },
  {
    archiveLine: 8682,
    title: "完整性校验-字段级-空串率",
    tableName: "dwd_voyah_dq_rule_04_main",
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "空串率",
    fields: ["delivery_center", "car_series_name"],
    fieldLogic: "and",
    expectation: { method: "固定值", operator: "<=", value: "0%" },
    description: "校验空串率分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0%",
    failExpectedValue: "25%",
    dirtyEvidence: ["ORD_04_F003", "delivery_center"],
    fusionChecks: {
      ruleSetGlobalParams: true,
    },
  },
  {
    archiveLine: 8775,
    title: "完整性校验-字段级-字段取值校验",
    tableName: "dwd_voyah_dq_rule_05_main",
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "字段取值校验",
    fields: ["final_price", "power_type"],
    fieldLogic: "and",
    expectation: { method: "固定值", operator: ">=", value: "0" },
    description: "校验字段取值分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部 final_price >= 0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_05_F003", "-100.000"],
    fusionChecks: {
      ruleSetRuleEdit: true,
    },
  },
  {
    archiveLine: 8868,
    title: "完整性校验-字段级-key范围校验",
    tableName: "dwd_voyah_dq_rule_06_main",
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "key范围校验",
    fields: ["json_payload"],
    expectation: { method: "不包含", value: "debug.errorCode" },
    description: "校验key范围分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "key 全部不存在",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_06_F003", "debug.errorCode"],
    fusionChecks: {
      dirtyDetail: { highlightedColumns: ["json_payload"] },
    },
  },
  {
    archiveLine: 8961,
    title: "完整性校验-单表-表行数",
    tableName: "dwd_voyah_dq_rule_07_main",
    ruleCategory: "完整性校验",
    scope: "单表",
    statisticFunction: "表行数",
    fields: [],
    expectation: { method: "固定值", operator: "=", value: "4" },
    description: "校验表行数分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "4",
    failExpectedValue: "5",
    dirtyEvidence: ["5", "stat_date"],
    fusionChecks: {
      partitionModesVisible: true,
      samplingRows: "10",
      failByEditingExistingTask: {
        partitionMode: "manual",
        deleteRuleSetBeforeRun: true,
      },
    },
  },
  {
    archiveLine: 9055,
    title: "完整性校验-多表数据行数对比",
    tableName: "dwd_voyah_dq_rule_08_main",
    comparisonTableName: "dwd_voyah_dq_rule_08_ref",
    ruleCategory: "完整性校验",
    scope: "多表",
    statisticFunction: "多表数据行数对比",
    fields: [],
    expectation: { method: "数量差异", operator: "<=", value: "0" },
    description: "校验多表行数分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "差异 0",
    failExpectedValue: "差异 1",
    dirtyEvidence: ["ORD_08_F004", "dwd_voyah_dq_rule_08_ref"],
  },
  {
    archiveLine: 9192,
    title: "完整性校验-多表数据内容对比",
    tableName: "dwd_voyah_dq_rule_09_main",
    comparisonTableName: "dwd_voyah_dq_rule_09_ref",
    ruleCategory: "完整性校验",
    scope: "多表",
    statisticFunction: "多表数据内容对比",
    fields: ["car_model_code", "power_type"],
    comparisonFields: ["car_model_code", "power_type"],
    primaryKeys: ["vin", "car_series_code"],
    comparisonPrimaryKeys: ["vin", "car_series_code"],
    fieldLogic: "and",
    expectation: { method: "in", value: "car_model_code" },
    description: "校验多表内容分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "内容差异 0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "MISMATCH_MODEL"],
  },
  {
    archiveLine: 9330,
    title: "有效性校验-数值-取值范围",
    tableName: "dwd_voyah_dq_rule_10_main",
    ruleCategory: "有效性校验",
    statisticFunction: "数值-取值范围",
    fields: ["final_price"],
    ruleInputs: [{ label: "期望值", value: ">= 0 且 <= 1000000" }],
    description: "校验数值范围分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部在 [0,1000000] 范围内",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_10_F003", "-100.000"],
  },
  {
    archiveLine: 9423,
    title: "有效性校验-格式-身份证号",
    tableName: "dwd_voyah_dq_rule_11_main",
    ruleCategory: "有效性校验",
    statisticFunction: "格式-身份证号",
    fields: ["owner_id_card"],
    expectation: { method: "固定值", operator: "=", value: "0" },
    description: "校验身份证格式分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部合法",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_11_F003", "ABC123"],
  },
  {
    archiveLine: 9517,
    title: "有效性校验-格式-手机号",
    tableName: "dwd_voyah_dq_rule_12_main",
    ruleCategory: "有效性校验",
    statisticFunction: "格式-手机号",
    fields: ["owner_phone"],
    expectation: { method: "固定值", operator: ">=", value: "4" },
    description: "校验手机号格式分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "手机号合法数 4",
    failExpectedValue: "手机号合法数 3",
    dirtyEvidence: ["ORD_12_F003", "10086"],
  },
  {
    archiveLine: 9610,
    title: "有效性校验-格式-邮箱",
    tableName: "dwd_voyah_dq_rule_13_main",
    ruleCategory: "有效性校验",
    statisticFunction: "格式-邮箱",
    fields: ["owner_email"],
    expectation: { method: "固定值", operator: "!=", value: "1" },
    description: "校验邮箱格式分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部合法",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_13_F003", "owner-at-example"],
  },
  {
    archiveLine: 9703,
    title: "有效性校验-字符串长度",
    tableName: "dwd_voyah_dq_rule_14_main",
    ruleCategory: "有效性校验",
    statisticFunction: "字符串长度",
    fields: ["vin"],
    expectation: { method: "固定值", operator: "<=", value: "17" },
    description: "校验字符串长度分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部长度 <= 17",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_14_F003", "LTV202601150003AATOOLONG"],
  },
  {
    archiveLine: 9796,
    title: "有效性校验-数据精度",
    tableName: "dwd_voyah_dq_rule_15_main",
    ruleCategory: "有效性校验",
    statisticFunction: "数据精度",
    fields: ["final_price"],
    ruleOptions: [{ label: /关系|逻辑关系/, value: "且" }],
    ruleInputs: [
      { label: "小数点前最大位", value: "18" },
      { label: "小数点后最大位", value: "2" },
    ],
    description: "校验数据精度分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部小数位 <= 2",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_15_F003", "252800.123"],
  },
  {
    archiveLine: 9889,
    title: "有效性校验-枚举值",
    tableName: "dwd_voyah_dq_rule_16_main",
    ruleCategory: "有效性校验",
    statisticFunction: "枚举值",
    fields: ["power_type"],
    ruleInputs: [{ label: "枚举值", value: "EV,PHEV,REEV" }],
    description: "校验枚举值分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部在枚举范围内",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_16_F003", "DIESEL"],
  },
  {
    archiveLine: 9982,
    title: "有效性校验-格式-日期格式-date",
    tableName: "dwd_voyah_dq_rule_17_main",
    ruleCategory: "有效性校验",
    statisticFunction: "格式-日期格式-date",
    fields: ["production_date"],
    ruleInputs: [{ label: "日期格式", value: "YYYY-MM-DD" }],
    expectation: { method: "固定值", operator: "=", value: "0" },
    description: "校验日期格式分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部符合 yyyy-MM-dd",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_17_F003", "2026/01/15"],
  },
  {
    archiveLine: 10075,
    title: "有效性校验-格式-日期格式-date time",
    tableName: "dwd_voyah_dq_rule_18_main",
    ruleCategory: "有效性校验",
    statisticFunction: "格式-日期格式-datetime",
    fields: ["delivery_time"],
    ruleInputs: [{ label: "日期时间格式", value: "YYYY-MM-DD HH:mm:ss" }],
    expectation: { method: "固定值", operator: ">=", value: "4" },
    description: "校验日期时间格式分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "日期时间格式合法数 4",
    failExpectedValue: "日期时间格式合法数 3",
    dirtyEvidence: ["ORD_18_F003", "2026/01/15 10:00"],
  },
  {
    archiveLine: 10168,
    title: "有效性校验-格式校验-自定义正则",
    tableName: "dwd_voyah_dq_rule_19_main",
    ruleCategory: "有效性校验",
    statisticFunction: "格式校验-自定义规则",
    fields: ["vin"],
    ruleOptions: [{ label: /自定义规则|规则名称/, value: "VIN_LTV格式" }],
    expectation: { method: "固定值", operator: "!=", value: "1" },
    description: "校验自定义正则分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部匹配正则",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_19_F003", "BAD202601150003AA"],
  },
  {
    archiveLine: 10261,
    title: "有效性校验-取值范围&枚举范围",
    tableName: "dwd_voyah_dq_rule_20_main",
    ruleCategory: "有效性校验",
    statisticFunction: "取值范围&枚举范围",
    fields: ["final_price"],
    ruleOptions: [{ label: /取值范围和枚举值的关系|关系|逻辑关系/, value: "且" }],
    ruleInputs: [
      { label: "取值范围", value: ">= 0 且 <= 1000000" },
      { label: "枚举值", value: "299000.00,308000.00,317000.00,326000.00" },
    ],
    description: "校验范围枚举分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "异常记录数实际值为 0",
    failExpectedValue: "异常记录数实际值为 1",
    dirtyEvidence: ["ORD_20_F003", "-100.000"],
    fusionChecks: {
      dirtyDetail: { highlightedColumns: ["final_price"], verifyDownloadEntry: true },
    },
  },
  {
    archiveLine: 10354,
    title: "有效性校验-格式-json格式校验",
    tableName: "dwd_voyah_dq_rule_21_main",
    ruleCategory: "有效性校验",
    statisticFunction: "格式-json格式校验",
    fields: ["json_payload"],
    ruleOptions: [{ label: /校验key|key/, value: "vehicle-vin" }],
    description: "校验json格式分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "JSON 合法且 key 存在",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_21_F003", "json_payload"],
    fusionChecks: {
      dirtyDetail: { highlightedColumns: ["json_payload"] },
      passHasNoDirtyDetail: true,
    },
  },
  {
    archiveLine: 10448,
    title: "唯一性校验-重复数",
    tableName: "dwd_voyah_dq_rule_22_main",
    ruleCategory: "唯一性校验",
    statisticFunction: "重复数",
    fields: ["vin"],
    expectation: { method: "固定值", operator: "!=", value: "1" },
    description: "校验重复数分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "重复"],
    fusionChecks: {
      monitorRecordTableSearch: true,
      samplingRows: "10",
    },
  },
  {
    archiveLine: 10541,
    title: "唯一性校验-重复率",
    tableName: "dwd_voyah_dq_rule_23_main",
    ruleCategory: "唯一性校验",
    statisticFunction: "重复率",
    fields: ["vin", "order_id"],
    fieldLogic: "or",
    expectation: { method: "固定值", operator: "<", value: "1%" },
    description: "校验重复率分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0%",
    failExpectedValue: "25%",
    dirtyEvidence: ["LTV202601150003AA", "重复"],
  },
  // archive-title: 验证【唯一性校验-多表唯一性判断】质量规则任务校验正常(唯一+或+单字段)
  {
    archiveLine: 10634,
    title: "唯一性校验-多表唯一性判断(唯一+或)",
    tableName: "dwd_voyah_dq_rule_24_main",
    comparisonTableName: "dwd_voyah_dq_rule_24_ref",
    ruleCategory: "唯一性校验",
    statisticFunction: "多表唯一性判断",
    fields: ["vin"],
    comparisonFields: ["vin"],
    ruleOptions: [
      { label: /校验字段逻辑|字段逻辑/, value: "唯一" },
      { label: /和其他表的校验关系|校验关系|关系/, value: "或" },
    ],
    description: "校验多表唯一或分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "dwd_voyah_dq_rule_24_ref"],
    fusionChecks: {
      sameTableSecondTask: true,
    },
  },
  // archive-title: 验证【唯一性校验-多表唯一性判断】质量规则任务校验正常(允许重复+且+多字段)
  {
    archiveLine: 10773,
    title: "唯一性校验-多表唯一性判断(允许重复+且)",
    tableName: "dwd_voyah_dq_rule_25_main",
    comparisonTableName: "dwd_voyah_dq_rule_25_ref",
    ruleCategory: "唯一性校验",
    statisticFunction: "多表唯一性判断",
    fields: ["vin", "order_id"],
    comparisonFields: ["vin", "order_id"],
    fieldLogic: "and",
    ruleOptions: [
      { label: /校验字段逻辑|字段逻辑/, value: "允许重复" },
      { label: /和其他表的校验关系|校验关系|关系/, value: "且" },
    ],
    description: "校验多表重复且分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["vin", "order_id"],
  },
  {
    archiveLine: 10911,
    title: "统计性校验-异常值检测-IQR离群点数量",
    tableName: "dwd_voyah_dq_rule_26_main",
    ruleCategory: "统计性校验",
    statisticFunction: "异常值检测",
    fields: ["final_price"],
    expectation: { method: "IQR离群点数量", operator: "=", value: "0" },
    description: "校验IQR数量分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_26_F004", "999999.000"],
  },
  {
    archiveLine: 11004,
    title: "统计性校验-异常值检测-IQR离群点占比",
    tableName: "dwd_voyah_dq_rule_27_main",
    ruleCategory: "统计性校验",
    statisticFunction: "异常值检测",
    fields: ["final_price"],
    expectation: { method: "IQR离群点占比", operator: "<", value: "1%" },
    description: "校验IQR占比分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: ">0",
    dirtyEvidence: ["ORD_27_F004", "999999.000"],
  },
  {
    archiveLine: 11097,
    title: "统计性校验-异常值检测-Z-score置信区间",
    tableName: "dwd_voyah_dq_rule_28_main",
    ruleCategory: "统计性校验",
    statisticFunction: "异常值检测",
    fields: ["final_price"],
    expectation: { method: "Z-score置信区间", operator: ">=", value: "-1.96 且 <= 1.96" },
    description: "校验Z-score分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_28_F004", "999999.000"],
  },
  {
    archiveLine: 11190,
    title: "自定义SQL-完整性校验",
    tableName: "dwd_voyah_dq_rule_29_main",
    ruleCategory: "完整性校验",
    sourceRefKind: "CUSTOMSQL",
    statisticFunction: "自定义SQL",
    fields: ["car_model_name"],
    customSqlTemplate: {
      ruleName: "自定义SQL完整性空值数模板",
      ruleType: 1,
      relationRange: 3,
      ruleDesc: "自定义SQL-完整性校验模板",
      customConfiguration: "select count(*) from ${test_table} where car_model_name is null;",
      params: [{ param: "${test_table}", type: 4, paramName: "当前校验表", description: "当前任务主表" }],
    },
    expectation: { method: "固定值", operator: "=", value: "0" },
    description: "校验完整性校验SQL结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_29_F003", "car_model_name"],
    fusionChecks: {
      dirtyDetail: { highlightedColumns: ["car_model_name"], verifyDownloadEntry: true },
    },
  },
  {
    archiveLine: 11284,
    title: "自定义SQL-有效性校验",
    tableName: "dwd_voyah_dq_rule_30_main",
    ruleCategory: "有效性校验",
    sourceRefKind: "CUSTOMSQL",
    statisticFunction: "自定义SQL",
    fields: ["final_price"],
    customSqlTemplate: {
      ruleName: "自定义SQL有效性取值范围模板",
      ruleType: 3,
      relationRange: 3,
      ruleDesc: "自定义SQL-有效性校验模板",
      customConfiguration: "select count(*) from ${test_table} where final_price >= 0;",
      params: [{ param: "${test_table}", type: 4, paramName: "当前校验表", description: "当前任务主表" }],
    },
    expectation: { method: "固定值", operator: ">", value: "3" },
    description: "校验有效性校验SQL结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_30_F003", "-100.000"],
  },
  {
    archiveLine: 11378,
    title: "自定义SQL-唯一性校验",
    tableName: "dwd_voyah_dq_rule_31_main",
    ruleCategory: "唯一性校验",
    sourceRefKind: "CUSTOMSQL",
    statisticFunction: "自定义SQL",
    fields: ["vin"],
    customSqlTemplate: {
      ruleName: "自定义SQL唯一性重复VIN模板",
      ruleType: 2,
      relationRange: 3,
      ruleDesc: "自定义SQL-唯一性校验模板",
      customConfiguration: "select count(distinct vin) from ${test_table};",
      params: [{ param: "${test_table}", type: 4, paramName: "当前校验表", description: "当前任务主表" }],
    },
    expectation: { method: "固定值", operator: ">=", value: "4" },
    description: "校验唯一性校验SQL结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "重复"],
  },
  {
    archiveLine: 11472,
    title: "自定义SQL-统计性校验",
    tableName: "dwd_voyah_dq_rule_32_main",
    ruleCategory: "统计性校验",
    sourceRefKind: "CUSTOMSQL",
    statisticFunction: "自定义SQL",
    fields: ["final_price"],
    customSqlTemplate: {
      ruleName: "自定义SQL统计性异常价格模板",
      ruleType: 6,
      relationRange: 3,
      ruleDesc: "自定义SQL-统计性校验模板",
      customConfiguration: "select count(*) from ${test_table} where final_price > 900000;",
      params: [{ param: "${test_table}", type: 4, paramName: "当前校验表", description: "当前任务主表" }],
    },
    expectation: { method: "固定值", operator: "<", value: "1" },
    description: "校验统计性校验SQL结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_32_F004", "999999.000"],
  },
  {
    archiveLine: 11566,
    title: "自定义SQL-一致性校验",
    tableName: "dwd_voyah_dq_rule_33_main",
    comparisonTableName: "dwd_voyah_dq_rule_33_ref",
    ruleCategory: "一致性校验",
    sourceRefKind: "CUSTOMSQL",
    statisticFunction: "自定义SQL",
    fields: ["car_model_code"],
    customSqlTemplate: {
      ruleName: "自定义SQL一致性主外表差异模板",
      ruleType: 7,
      relationRange: 1,
      ruleDesc: "自定义SQL-一致性校验模板",
      customConfiguration:
        "select count(*) from ${test_table} t left join ${ref_table} r on t.vin = r.vin where t.car_model_code <> r.car_model_code or r.vin is null;",
      params: [
        { param: "${test_table}", type: 4, paramName: "当前校验表", description: "当前任务主表" },
        { param: "${ref_table}", type: 6, paramName: "对比表", description: "对比表表名" },
      ],
    },
    ruleInputs: [{ label: "对比表", value: "dwd_voyah_dq_rule_33_ref" }],
    expectation: { method: "固定值", operator: "<=", value: "0" },
    description: "校验一致性校验SQL结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "car_model_code"],
  },
  {
    archiveLine: 11705,
    title: "自定义SQL-时效性校验",
    tableName: "dwd_voyah_dq_rule_34_main",
    ruleCategory: "时效性校验",
    sourceRefKind: "CUSTOMSQL",
    statisticFunction: "自定义SQL",
    fields: ["delivery_time", "order_time"],
    customSqlTemplate: {
      ruleName: "自定义SQL时效性超时交付模板",
      ruleType: 8,
      relationRange: 3,
      ruleDesc: "自定义SQL-时效性校验模板",
      customConfiguration: "select count(*) from ${test_table} where datediff(to_date(delivery_time), to_date(order_time)) > 1;",
      params: [{ param: "${test_table}", type: 4, paramName: "当前校验表", description: "当前任务主表" }],
    },
    expectation: { method: "固定值", operator: "!=", value: "1" },
    description: "校验时效性校验SQL结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_34_F003", "2026-01-13 08:00:00"],
  },
  {
    archiveLine: 11799,
    title: "自定义SQL-合理性校验",
    tableName: "dwd_voyah_dq_rule_35_main",
    ruleCategory: "合理性校验",
    sourceRefKind: "CUSTOMSQL",
    statisticFunction: "自定义SQL",
    fields: ["final_price", "guide_price", "discount_amount"],
    customSqlTemplate: {
      ruleName: "自定义SQL合理性价格公式模板",
      ruleType: 9,
      relationRange: 3,
      ruleDesc: "自定义SQL-合理性校验模板",
      customConfiguration: "select count(*) from ${test_table} where final_price <> guide_price - discount_amount;",
      params: [{ param: "${test_table}", type: 4, paramName: "当前校验表", description: "当前任务主表" }],
    },
    expectation: { method: "固定值", operator: "=", value: "0" },
    description: "校验合理性校验SQL结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_35_F003", "final_price"],
  },
  {
    archiveLine: 11893,
    title: "一致性校验-多表数据一致性比对",
    tableName: "dwd_voyah_dq_rule_36_main",
    comparisonTableName: "dwd_voyah_dq_rule_36_ref",
    ruleCategory: "一致性校验",
    statisticFunction: "多表数据一致性比对",
    fields: ["car_model_code", "power_type"],
    comparisonFields: ["car_model_code", "power_type"],
    primaryKeys: ["vin"],
    comparisonPrimaryKeys: ["vin"],
    fieldLogic: "and",
    ruleInputs: [{ label: "比对细节设置", value: "数值差异绝对值 <= 0" }],
    description: "校验多表一致分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "car_model_code", "power_type"],
  },
  {
    archiveLine: 12031,
    title: "一致性校验-多表数据一致性比对(多主键+or)",
    tableName: "dwd_voyah_dq_rule_36_multi_main",
    comparisonTableName: "dwd_voyah_dq_rule_36_multi_ref",
    ruleCategory: "一致性校验",
    statisticFunction: "多表数据一致性比对",
    fields: ["car_model_code", "power_type"],
    comparisonFields: ["car_model_code", "power_type"],
    primaryKeys: ["vin", "car_series_code"],
    comparisonPrimaryKeys: ["vin", "car_series_code"],
    fieldLogic: "or",
    ruleInputs: [{ label: "比对细节设置", value: "数值差异绝对值 <= 0" }],
    description: "校验多表一致分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "PASSION", "car_model_code"],
  },
  {
    archiveLine: 12169,
    title: "时效性校验-周期性校验（单字段时间差校验）",
    tableName: "dwd_voyah_dq_rule_37_main",
    ruleCategory: "时效性校验",
    statisticFunction: "周期性校验（单字段时间差校验）",
    fields: ["delivery_time"],
    ruleOptions: [{ label: /排序字段/, value: "event_time" }],
    ruleInputs: [{ label: "时间差", value: "<= 1 天" }],
    description: "校验单字段时间差分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部 <= 1 天",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_37_F003", "2026-01-13 08:00:00"],
  },
  {
    archiveLine: 12262,
    title: "时效性校验-及时性校验（多字段时间差校验）",
    tableName: "dwd_voyah_dq_rule_38_main",
    ruleCategory: "时效性校验",
    statisticFunction: "及时性校验（多字段时间差校验）",
    fields: ["order_time", "payment_time"],
    ruleOptions: [
      { label: /对比字段组|字段组/, value: "order_time,payment_time" },
      { label: /大小关系/, value: "order_time < payment_time" },
    ],
    ruleInputs: [{ label: "时间差", value: "> 0 分钟 且 <= 60 分钟" }],
    description: "校验多字段时间差分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部 > 0 分钟且 <= 60 分钟",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_38_F003", "90"],
  },
  {
    archiveLine: 12355,
    title: "合理性校验-数据变化趋势-单调递增",
    tableName: "dwd_voyah_dq_rule_39_main",
    ruleCategory: "合理性校验",
    statisticFunction: "数据变化趋势",
    fields: ["mileage"],
    ruleOptions: [
      { label: /排序字段/, value: "event_time" },
      { label: /校验方法|趋势|比较方式/, value: "单调递增" },
    ],
    description: "校验单调递增分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "里程按 event_time 单调递增",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_39_F003", "mileage"],
    fusionChecks: {
      dirtyDetail: { highlightedColumns: ["mileage"], verifyDownloadEntry: true },
    },
  },
  {
    archiveLine: 12448,
    title: "合理性校验-数据变化趋势-单调递减",
    tableName: "dwd_voyah_dq_rule_40_main",
    ruleCategory: "合理性校验",
    statisticFunction: "数据变化趋势",
    fields: ["battery_loss_rate"],
    ruleOptions: [
      { label: /排序字段/, value: "event_time" },
      { label: /校验方法|趋势|比较方式/, value: "单调递减" },
    ],
    description: "校验单调递减分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "电池衰减率按 event_time 单调递减",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_40_F003", "battery_loss_rate"],
  },
  {
    archiveLine: 12541,
    title: "合理性校验-字段值计算对比-计算结果与字段对比",
    tableName: "dwd_voyah_dq_rule_41_main",
    ruleCategory: "合理性校验",
    statisticFunction: "字段值计算对比",
    fields: ["final_price"],
    ruleInputs: [{ label: "计算逻辑配置", value: "guide_price - discount_amount" }],
    ruleOptions: [
      { label: /对比方法/, value: "计算结果与字段对比" },
      { label: /比较关系/, value: "final_price = 计算逻辑结果" },
    ],
    description: "校验字段计算对比分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_41_F003", "final_price"],
  },
  {
    archiveLine: 12634,
    title: "合理性校验-字段值计算对比-计算结果值判断",
    tableName: "dwd_voyah_dq_rule_42_main",
    ruleCategory: "合理性校验",
    statisticFunction: "字段值计算对比",
    fields: ["final_price"],
    ruleInputs: [
      { label: "计算逻辑配置", value: "guide_price - final_price" },
      { label: "结果值", value: ">= 0" },
    ],
    ruleOptions: [{ label: /对比方法/, value: "计算结果值判断" }],
    description: "校验字段计算判断分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部 >= 0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_42_F003", "guide_price-final_price"],
  },
  {
    archiveLine: 12727,
    title: "合理性校验-多表字段值对比-计算结果对比",
    tableName: "dwd_voyah_dq_rule_43_main",
    comparisonTableName: "dwd_voyah_dq_rule_43_ref",
    ruleCategory: "合理性校验",
    statisticFunction: "多表字段值对比",
    fields: ["final_price"],
    primaryKeys: ["vin", "car_series_code"],
    comparisonPrimaryKeys: ["vin", "car_series_code"],
    ruleInputs: [
      { label: "计算逻辑配置", value: "guide_price - discount_amount" },
      { label: "计算逻辑配置2", value: "guide_price - discount_amount" },
    ],
    ruleOptions: [
      { label: /对比方法/, value: "计算结果对比" },
      { label: /比较关系/, value: "计算逻辑1 = 计算逻辑2" },
    ],
    description: "校验多表计算对比分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "计算结果不一致"],
  },
  {
    archiveLine: 12865,
    title: "合理性校验-多表字段值对比-计算结果值判断",
    tableName: "dwd_voyah_dq_rule_44_main",
    comparisonTableName: "dwd_voyah_dq_rule_44_ref",
    ruleCategory: "合理性校验",
    statisticFunction: "多表字段值对比",
    fields: ["final_price"],
    primaryKeys: ["vin"],
    comparisonPrimaryKeys: ["vin"],
    ruleInputs: [
      { label: "计算逻辑配置", value: "guide_price - final_price" },
      { label: "结果值", value: "<= 1000000" },
    ],
    ruleOptions: [{ label: /对比方法/, value: "计算结果值判断" }],
    description: "校验多表计算判断分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部 <= 1000000",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "1000000"],
  },
];

function sourceRefKindFor(scenario: SparkThriftQualityRuleValidationScenario): string {
  if (scenario.sourceRefKind) return scenario.sourceRefKind;
  const { ruleCategory } = scenario;
  if (ruleCategory === "有效性校验") return "VALIDITY";
  if (ruleCategory === "唯一性校验") return "UNIQUENESS";
  if (ruleCategory === "统计性校验") return "STATISTICAL";
  if (ruleCategory === "一致性校验") return "CONSISTENCY";
  if (ruleCategory === "时效性校验") return "TIMELINESS";
  if (ruleCategory === "合理性校验") return "REASONABLENESS";
  return "COMPLETENESS";
}

for (const scenario of scenarios) {
  test(`【P0】数据质量${scenario.title}质量规则任务校验正常`, async ({ page, step }) => {
    await step(`步骤1-8: ${scenario.title} 规则集、规则任务、通过分区与失败分区校验`, async () => {
      ensureSparkThriftScenarioPreconditions(
        scenario,
        `SR-2099-01-DQ-SPARKTHRIFT-${sourceRefKindFor(scenario)}-L${scenario.archiveLine}`,
      );
      await expectSparkThriftQualityRuleValidationContract(
        page,
        `SR-2099-01-DQ-SPARKTHRIFT-${sourceRefKindFor(scenario)}-L${scenario.archiveLine}`,
        scenario,
      );
    });
  });
}

function ensureSparkThriftScenarioPreconditions(
  scenario: SparkThriftQualityRuleValidationScenario,
  sourceRef: string,
): void {
  const tableNames = [scenario.tableName, scenario.comparisonTableName]
    .filter((name): name is string => Boolean(name))
    .sort();
  const groupKey = tableNames.join(",");
  ensureSelectedDtstackPreconditionTables(groupKey, PRECOND_TABLES_FILE, tableNames, sourceRef);
}
