import { createHash } from "node:crypto";
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  readlinkSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { type ProjectionRuntime, skillProjectionPath } from "../runtime/projection-targets.ts";
import { symlinkPathComponentIssue } from "./containment.ts";
import { repoRoot } from "./paths.ts";
import { parseProductSkillContract } from "./product-skill-contract.ts";
import { parseProjectionInventory, parseProjectionInventoryText } from "./projection-inventory.ts";
import {
  type RenderedSkillFile,
  renderProductSkill,
  type SkillCallGraph,
} from "./skill-renderer.ts";
import type { AiCoreIssue, AiCoreResult, ProjectionInventoryRow } from "./types.ts";
import { readVendorSkillManifestFiles, type VendorManifestFile } from "./vendor.ts";
import {
  parseYamlContract,
  parseYamlTopLevelScalars,
  readOptionalScalar,
  readOptionalStringList,
  yamlIssues,
} from "./yaml-contract.ts";

export type ProjectionOptions = {
  runtime: "all" | ProjectionRuntime;
  outputRoot?: string;
  coreRoot?: string;
  vendorRoot?: string;
  prune?: boolean;
};

type VendorProjectionFile = {
  path: string;
  content: Buffer;
};

type CommandContract = {
  id: string;
  skill: string;
  userInvocable: "true" | "false";
  summary: string;
};

const COMMAND_INDEX_START = "<!-- ai-core:start command-index -->";
const COMMAND_INDEX_END = "<!-- ai-core:end command-index -->";
const ROUTING_HEADING = "## Routing";
const ROUTING_HEADING_CN = "## 路由规则";
const LEGACY_ROUTING_GUARD_HEADING = "## Routing Guard";
const ROUTING_GUARD_SOURCE_PATH = "rules/routing-guard.md";

function loadRoutingGuardSection(coreRoot: string): string {
  const path = join(coreRoot, ROUTING_GUARD_SOURCE_PATH);
  return readFileSync(path, "utf8").replace(/\n+$/, "");
}
const COMMAND_INDEX_ORDER = [
  "workspace-manage",
  "case-draft",
  "case-edit",
  "knowledge-curate",
  "bug-file",
  "conflict-analyze",
  "case-hotfix",
  "playwright-automation",
  "diff-scan",
  "infra-diagnose",
];
const COMMAND_INDEX_IDS = new Set(COMMAND_INDEX_ORDER);

function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function generatedHeader(source: string): string {
  return [
    "<!-- generated by kata ai-core; do not edit -->",
    `<!-- ai-core-hash: ${sha256(source)} -->`,
    "",
  ].join("\n");
}

function defaultCoreRoot(): string {
  return join(repoRoot(), ".ai/core");
}

function productSkillRoots(coreRoot: string): string[] {
  return readdirSync(join(coreRoot, "skills"), { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => join(coreRoot, "skills", entry.name))
    .filter((skillRoot) => {
      try {
        return statSync(join(skillRoot, "skill.yaml")).isFile();
      } catch {
        return false;
      }
    })
    .sort();
}

type WorkflowSummary = {
  id: string;
  entrySkill: string;
  uses: string[];
  prompts: string[];
};

function parseWorkflowStepReferences(text: string): { uses: string[]; prompts: string[] } {
  const uses: string[] = [];
  const prompts: string[] = [];
  let inSteps = false;
  for (const raw of text.split(/\r?\n/)) {
    if (raw === "steps:") {
      inSteps = true;
      continue;
    }
    if (!inSteps) continue;
    if (raw.length > 0 && !/^\s/.test(raw)) {
      inSteps = false;
      continue;
    }
    const trimmed = raw.trim();
    if (trimmed.startsWith("uses:")) {
      uses.push(trimmed.slice("uses:".length).trim());
    } else if (trimmed.startsWith("prompt:")) {
      prompts.push(trimmed.slice("prompt:".length).trim());
    }
  }
  return { uses, prompts };
}

function loadWorkflowSummaries(coreRoot: string): WorkflowSummary[] {
  const dir = join(coreRoot, "workflows");
  const summaries: WorkflowSummary[] = [];
  let files: string[];
  try {
    files = readdirSync(dir)
      .filter((f) => f.endsWith(".workflow.yaml"))
      .sort();
  } catch {
    return summaries;
  }
  for (const file of files) {
    const text = readFileSync(join(dir, file), "utf8");
    const path = `.ai/core/workflows/${file}`;
    const top = parseYamlTopLevelScalars(text, path);
    if (!top.ok) continue;
    const fields = top.value ?? {};
    const id = fields.id ?? "";
    const entrySkill = fields.entry_skill ?? "";
    const { uses, prompts } = parseWorkflowStepReferences(text);
    summaries.push({ id, entrySkill, uses, prompts });
  }
  return summaries;
}

function stripSkillVersion(idWithVersion: string): string {
  return idWithVersion.replace(/@\d+$/, "");
}

function pushUnique(target: string[], value: string): void {
  if (!target.includes(value)) target.push(value);
}

function buildCallGraph(
  coreRoot: string,
  commands: CommandContract[],
): Map<string, SkillCallGraph> {
  const graphs = new Map<string, SkillCallGraph>();

  function ensure(skillName: string): SkillCallGraph {
    let graph = graphs.get(skillName);
    if (!graph) {
      graph = {
        upstreamCommands: [],
        downstreamWorkflows: [],
        downstreamAgents: [],
        downstreamPlugins: [],
        downstreamPrompts: [],
      };
      graphs.set(skillName, graph);
    }
    return graph;
  }

  for (const cmd of commands) {
    const skillName = stripSkillVersion(cmd.skill);
    pushUnique(ensure(skillName).upstreamCommands, cmd.id);
  }

  for (const workflow of loadWorkflowSummaries(coreRoot)) {
    const skillName = stripSkillVersion(workflow.entrySkill);
    if (!skillName) continue;
    const graph = ensure(skillName);
    pushUnique(graph.downstreamWorkflows, workflow.id);
    for (const reference of workflow.uses) {
      if (reference.startsWith("agent:")) {
        pushUnique(graph.downstreamAgents, reference.slice("agent:".length));
      } else if (reference.startsWith("plugin:")) {
        pushUnique(graph.downstreamPlugins, reference.slice("plugin:".length));
      }
    }
    for (const prompt of workflow.prompts) {
      pushUnique(graph.downstreamPrompts, prompt);
    }
  }

  return graphs;
}

function loadAllCommandContracts(coreRoot: string): CommandContract[] {
  const result = loadCommandContracts(coreRoot);
  return result.ok ? (result.value ?? []) : [];
}

type IndexEntry = {
  command: string;
  skill: string;
  outputs: string[];
  workflows: string[];
  agents: string[];
  prompts: string[];
  plugins: string[];
};

function loadSkillOutputs(coreRoot: string, skillName: string): string[] {
  const skillFile = join(coreRoot, "skills", skillName, "skill.yaml");
  if (!existsSync(skillFile)) return [];
  const text = readFileSync(skillFile, "utf8");
  const parsed = parseProductSkillContract(text, `.ai/core/skills/${skillName}/skill.yaml`);
  return parsed.ok ? (parsed.value?.outputs ?? []) : [];
}

function buildIndexEntries(
  coreRoot: string,
  commands: CommandContract[],
  callGraphs: Map<string, SkillCallGraph>,
): IndexEntry[] {
  return commands.map((cmd) => {
    const skillName = stripSkillVersion(cmd.skill);
    const callGraph = callGraphs.get(skillName);
    return {
      command: cmd.id,
      skill: skillName,
      outputs: loadSkillOutputs(coreRoot, skillName),
      workflows: callGraph?.downstreamWorkflows ?? [],
      agents: callGraph?.downstreamAgents ?? [],
      prompts: callGraph?.downstreamPrompts ?? [],
      plugins: callGraph?.downstreamPlugins ?? [],
    };
  });
}

function renderIndexDoc(entries: IndexEntry[]): string {
  const headerSource = JSON.stringify(entries);
  const rows = entries.map((entry) => {
    const cells = [
      `/${entry.command}`,
      entry.skill,
      entry.workflows.join(", ") || "-",
      entry.agents.join(", ") || "-",
      entry.prompts.join(", ") || "-",
      entry.plugins.join(", ") || "-",
      entry.outputs.join(", ") || "-",
    ].map(escapeMarkdownTableCell);
    return `| ${cells.join(" | ")} |`;
  });
  return [
    "# kata 命令调用图",
    "",
    generatedHeader(headerSource).trimEnd(),
    "",
    "每行映射：command → skill → workflow → 下游 agents/prompts/plugins → 输出。冷启动时优先读取本表，无需遍历 commands/。",
    "",
    "| Command | Skill | Workflow | Agents | Prompts | Plugins | Outputs |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

function indexDocPath(runtime: ProjectionRuntime): string {
  return runtime === "codex" ? ".agents/INDEX.md" : ".claude/INDEX.md";
}

function renderRuntimeIndex(
  runtime: ProjectionRuntime,
  coreRoot: string,
): { path: string; content: string } | undefined {
  const commandsResult = loadCommandContracts(coreRoot);
  if (!commandsResult.ok) return undefined;
  const commands = commandsResult.value ?? [];
  const callGraphs = buildCallGraph(coreRoot, commands);
  const entries = buildIndexEntries(coreRoot, commands, callGraphs);
  return { path: indexDocPath(runtime), content: renderIndexDoc(entries) };
}

function renderSkills(
  runtime: ProjectionRuntime,
  coreRoot: string,
): AiCoreResult<RenderedSkillFile[]> {
  const files: RenderedSkillFile[] = [];
  const issues: AiCoreIssue[] = [];
  const callGraphs = buildCallGraph(coreRoot, loadAllCommandContracts(coreRoot));
  for (const skillRoot of productSkillRoots(coreRoot)) {
    const skillSource = readFileSync(join(skillRoot, "skill.yaml"), "utf8");
    const skillName = relative(coreRoot, skillRoot).split("/").pop() ?? "";
    const result = renderProductSkill({
      runtime,
      skillRoot,
      repoRelativeSkillRoot: `.ai/core/${relative(coreRoot, skillRoot)}`,
      generatedHeader: generatedHeader(skillSource),
      callGraph: callGraphs.get(skillName),
    });
    if (result.ok) files.push(...(result.value ?? []));
    else issues.push(...result.issues);
  }
  if (issues.length > 0) return { ok: false, issues };
  return { ok: true, value: files, issues: [] };
}

function runtimes(option: "all" | ProjectionRuntime): ProjectionRuntime[] {
  return option === "all" ? ["claude", "codex"] : [option];
}

function loadCommandContracts(coreRoot: string): AiCoreResult<CommandContract[]> {
  const commandsRoot = join(coreRoot, "commands");
  const issues: AiCoreIssue[] = [];
  let files: string[];
  try {
    files = readdirSync(commandsRoot)
      .filter((file) => file.endsWith(".command.yaml"))
      .sort();
  } catch {
    return {
      ok: false,
      issues: [
        {
          code: "projection.contract_invalid",
          severity: "error",
          message: "Command contracts directory is missing.",
          path: ".ai/core/commands",
        },
      ],
    };
  }
  const commands: CommandContract[] = [];
  const seenIds = new Set<string>();
  for (const file of files) {
    const source = readFileSync(join(commandsRoot, file), "utf8");
    const path = `.ai/core/commands/${file}`;
    const contract = parseYamlContract(source, path);
    const contractIssues = yamlIssues(contract);
    if (contractIssues.length > 0) {
      issues.push(...contractIssues);
      continue;
    }
    const values = {
      id: readOptionalScalar(contract, "id") ?? "",
      skill: readOptionalScalar(contract, "skill") ?? "",
      summary: readOptionalScalar(contract, "summary") ?? "",
      user_invocable: readOptionalScalar(contract, "user_invocable") ?? "",
    };
    if (!values.id || !values.skill || !values.summary || !values.user_invocable) {
      issues.push({
        code: "projection.contract_invalid",
        severity: "error",
        message: "Command contract requires id, skill, user_invocable, and summary.",
        path,
      });
      continue;
    }
    if (values.user_invocable !== "true" && values.user_invocable !== "false") {
      issues.push({
        code: "projection.contract_invalid",
        severity: "error",
        message: "Command contract user_invocable must be exactly true or false.",
        path,
      });
    }
    const expectedId = file.replace(/\.command\.yaml$/, "");
    if (values.id !== expectedId) {
      issues.push({
        code: "projection.contract_invalid",
        severity: "error",
        message: "Command contract id must match file basename.",
        path,
      });
    }
    if (seenIds.has(values.id)) {
      issues.push({
        code: "projection.contract_invalid",
        severity: "error",
        message: "Command contract id must be unique.",
        path,
      });
    }
    seenIds.add(values.id);
    commands.push({
      id: values.id,
      skill: values.skill,
      userInvocable: values.user_invocable as "true" | "false",
      summary: values.summary,
    });
  }
  for (const requiredId of COMMAND_INDEX_ORDER) {
    if (seenIds.has(requiredId)) continue;
    issues.push({
      code: "projection.contract_invalid",
      severity: "error",
      message: "Required command contract is missing.",
      path: `.ai/core/commands/${requiredId}.command.yaml`,
    });
  }
  if (issues.length > 0) return { ok: false, issues };
  return {
    ok: true,
    value: commands
      .filter((command) => command.userInvocable === "true")
      .sort((left, right) => commandOrder(left.id) - commandOrder(right.id)),
    issues: [],
  };
}

function parseYamlStringList(content: string, path: string, key: string): AiCoreResult<string[]> {
  const contract = parseYamlContract(content, path);
  const issues = yamlIssues(contract);
  if (issues.length > 0) return { ok: false, issues };
  return { ok: true, value: readOptionalStringList(contract, key), issues: [] };
}

function commandOrder(id: string): number {
  const index = COMMAND_INDEX_ORDER.indexOf(id);
  return index === -1 ? Number.MAX_SAFE_INTEGER : index;
}

function renderCommandIndexBlock(commands: CommandContract[]): string {
  return [
    COMMAND_INDEX_START,
    "| Command | Skill | Summary |",
    "| --- | --- | --- |",
    ...commands.map(
      (command) =>
        `| /${escapeMarkdownTableCell(command.id)} | ${escapeMarkdownTableCell(command.skill)} | ${escapeMarkdownTableCell(command.summary)} |`,
    ),
    COMMAND_INDEX_END,
  ].join("\n");
}

function escapeMarkdownTableCell(value: string): string {
  return value.replace(/\|/g, "\\|");
}

function rootRuntimeDocPath(runtime: ProjectionRuntime): string {
  return runtime === "codex" ? "AGENTS.md" : "CLAUDE.md";
}

// CLAUDE.md is permitted to be a sibling symlink to AGENTS.md so the same
// content serves both Claude Code and Codex/Cursor/Aider via the agents.md
// open standard. Writes through the symlink update the AGENTS.md target.
function isPermittedRuntimeDocSymlink(root: string, path: string): boolean {
  if (path !== "CLAUDE.md") return false;
  try {
    if (!lstatSync(join(root, path)).isSymbolicLink()) return false;
    return readlinkSync(join(root, path)) === "AGENTS.md";
  } catch {
    return false;
  }
}

type CommandIndexMarkerState =
  | { ok: true; completeBlocks: number }
  | { ok: false; message: string };

function commandIndexMarkerState(current: string): CommandIndexMarkerState {
  const starts = [...current.matchAll(new RegExp(escapeRegExp(COMMAND_INDEX_START), "g"))].map(
    (match) => match.index ?? 0,
  );
  const ends = [...current.matchAll(new RegExp(escapeRegExp(COMMAND_INDEX_END), "g"))].map(
    (match) => match.index ?? 0,
  );
  if (starts.length !== ends.length) {
    return { ok: false, message: "Root runtime doc command index markers are unbalanced." };
  }
  for (let index = 0; index < starts.length; index += 1) {
    if (ends[index] < starts[index]) {
      return { ok: false, message: "Root runtime doc command index markers are unbalanced." };
    }
  }
  return { ok: true, completeBlocks: starts.length };
}

function mergeCommandIndexBlock(
  coreRoot: string,
  current: string | undefined,
  block: string,
): AiCoreResult<string> {
  if (current === undefined || current.length === 0)
    return { ok: true, value: renderRootRuntimeDoc(coreRoot, block), issues: [] };
  const markerState = commandIndexMarkerState(current);
  if (!markerState.ok) {
    return {
      ok: false,
      issues: [
        {
          code: "projection.drift",
          severity: "error",
          message: markerState.message,
          path: "",
        },
      ],
    };
  }
  if (markerState.completeBlocks > 1) {
    return {
      ok: false,
      issues: [
        {
          code: "projection.drift",
          severity: "error",
          message: "Root runtime doc must contain at most one complete command index block.",
          path: "",
        },
      ],
    };
  }
  const legacy = mergeLegacyCommandIndexTable(current, block);
  if (legacy) return legacy;
  const pattern = new RegExp(
    `${escapeRegExp(COMMAND_INDEX_START)}[\\s\\S]*?${escapeRegExp(COMMAND_INDEX_END)}`,
  );
  if (pattern.test(current)) {
    const next = current.replace(pattern, block);
    const withRoutingGuard = ensureRoutingGuardSection(coreRoot, next);
    const withCaseArtifactQa = ensureCaseArtifactQaSection(withRoutingGuard);
    return {
      ok: true,
      value: withCaseArtifactQa.endsWith("\n") ? withCaseArtifactQa : `${withCaseArtifactQa}\n`,
      issues: [],
    };
  }
  const separator = current.endsWith("\n\n") ? "" : current.endsWith("\n") ? "\n" : "\n\n";
  const withRoutingGuard = ensureRoutingGuardSection(coreRoot, `${current}${separator}${block}\n`);
  const withCaseArtifactQa = ensureCaseArtifactQaSection(withRoutingGuard);
  return {
    ok: true,
    value: withCaseArtifactQa,
    issues: [],
  };
}

function caseArtifactQaSection(): string {
  return [
    "## 关键约束",
    "",
    "- **产物自检**：QA 产物（Archives/XMind/CSV）交付前必须自检字段一致性和可读性，详见 `.ai/core/rules/case-qa.md`。",
  ].join("\n");
}

function renderRootRuntimeDoc(coreRoot: string, commandIndexBlock: string): string {
  return [
    "<!-- generated by kata ai-core; do not edit -->",
    `<!-- ai-core-hash: ${sha256(commandIndexBlock)} -->`,
    "",
    "输入 `/workspace-manage` 查看功能菜单；首次安装见仓库根目录 `INSTALL.md`。",
    "",
    "`.claude/` 与 `.agents/` 是 kata runtime 投影目录；根目录 `AGENTS.md` 为公开 coding-agent 入口（唯一来源），`CLAUDE.md` 是其 symlink。",
    "",
    loadRoutingGuardSection(coreRoot),
    "",
    "## 命令索引",
    "",
    commandIndexBlock,
    "",
    "## 构建与测试",
    "",
    "- Runtime：[Bun](https://bun.sh) ≥ 1.3；装依赖：`bun install`（自动安装 workspaces：`engine`、`tools/dtstack-sdk`）。",
    "- 全量测试：`bun test`；局部：`bun test engine/tests/<area>`；子集：`bun run test:ai-core`。",
    "- Lint 检查：`bun run check`（biome）；自动修复：`bun run check:fix`。",
    "- 投影渲染：`bun engine/bin/kata ai-core projection render`（源契约变更后必须运行）。",
    "",
    "## 关键约束",
    "",
    "- **Worktree 优先**：所有改动走 `.worktrees/<slug>`，验证通过后合并回 main 并推送。详见 `.ai/core/rules/git-workflow.md`。",
    "- **改后即测**：代码/配置改动后必须跑相关测试；失败必须修复，不得跳过或推迟。详见 `.ai/core/rules/testing.md`。",
    "- **Commit 规范**：Conventional Commits（`type: emoji description`），type 小写，description ≤72 字符。",
    "- **命名规范**：Feature 目录 `YYYY-MM[-{customer}]-{module}-{slug}`。详见 `.ai/core/rules/naming-convention.md`。",
    "- **产物自检**：QA 产物（Archives/XMind/CSV）交付前必须自检字段一致性和可读性。详见 `.ai/core/rules/case-qa.md`。",
    "",
    "## 详细规则（按需加载）",
    "",
    "以下规则文件仅在相关任务时按需读取，不占用每次会话入口 token：",
    "",
    "| 规则 | 路径 | 适用场景 |",
    "|------|------|----------|",
    "| 测试规范 | `.ai/core/rules/testing.md` | 编写/修改测试 |",
    "| Git 工作流 | `.ai/core/rules/git-workflow.md` | 创建分支/合并 |",
    "| 命名约定 | `.ai/core/rules/naming-convention.md` | 创建 feature 目录 |",
    "| 产物 QA | `.ai/core/rules/case-qa.md` | 生成/编辑 QA 产物 |",
    "| 工作区边界 | `.ai/core/rules/workspace-boundary.md` | 读写 workspace 文件 |",
    "",
  ].join("\n");
}

function ensureCaseArtifactQaSection(current: string): string {
  const section = caseArtifactQaSection();
  const oldHeading = "## Case Artifact QA";
  const newHeading = "## 关键约束";

  if (current.includes(newHeading)) return current;

  if (current.includes(oldHeading)) {
    const existingIndex = current.indexOf(oldHeading);
    const afterExisting = current.slice(existingIndex + oldHeading.length);
    const nextHeadingMatch = afterExisting.match(/\n## [^\n]+/);
    const endIndex = nextHeadingMatch
      ? existingIndex + oldHeading.length + (nextHeadingMatch.index ?? 0)
      : current.length;
    const before = current.slice(0, existingIndex).replace(/\s*$/, "\n\n");
    const after = current.slice(endIndex).replace(/^\s*/, "");
    return `${before}${section}\n\n${after}`;
  }

  const anchor = "## 命令索引";
  const anchorIndex = current.indexOf(anchor);
  if (anchorIndex >= 0) {
    const afterAnchor = current.slice(anchorIndex + anchor.length);
    const nextHeadingMatch = afterAnchor.match(/\n## [^\n]+/);
    const insertIndex = nextHeadingMatch
      ? anchorIndex + anchor.length + (nextHeadingMatch.index ?? 0)
      : current.length;
    const before = current.slice(0, insertIndex).replace(/\s*$/, "\n\n");
    const after = current.slice(insertIndex).replace(/^\s*/, "");
    return `${before}${section}\n\n${after}`;
  }

  return current.endsWith("\n") ? `${current}${section}\n` : `${current}\n\n${section}\n`;
}

function ensureRoutingGuardSection(coreRoot: string, current: string): string {
  const section = loadRoutingGuardSection(coreRoot);
  const existingHeading = [ROUTING_HEADING, ROUTING_HEADING_CN, LEGACY_ROUTING_GUARD_HEADING].find((heading) =>
    current.includes(heading),
  );
  if (existingHeading) {
    const existingIndex = current.indexOf(existingHeading);
    const afterExisting = current.slice(existingIndex + existingHeading.length);
    const nextHeadingMatch = afterExisting.match(/\n## [^\n]+/);
    const endIndex = nextHeadingMatch
      ? existingIndex + existingHeading.length + (nextHeadingMatch.index ?? 0)
      : current.length;
    const before = current.slice(0, existingIndex).replace(/\s*$/, "\n\n");
    const after = current.slice(endIndex).replace(/^\s*/, "");
    return `${before}${section}\n\n${after}`;
  }
  const heading = "## 命令索引";
  const index = current.indexOf(heading);
  if (index < 0) return current;
  const before = current.slice(0, index).replace(/\s*$/, "\n\n");
  const after = current.slice(index).replace(/^\s*/, "");
  return `${before}${section}\n\n${after}`;
}

function mergeLegacyCommandIndexTable(
  current: string,
  block: string,
): AiCoreResult<string> | undefined {
  const heading = "## 命令索引";
  const headingIndex = current.indexOf(heading);
  if (headingIndex < 0) return undefined;
  const afterHeadingIndex = headingIndex + heading.length;
  const afterHeading = current.slice(afterHeadingIndex);
  const tableStartInAfterHeading = afterHeading.search(/\n[ \t]*\|/);
  if (tableStartInAfterHeading < 0) return undefined;
  if (afterHeading.slice(0, tableStartInAfterHeading).includes(COMMAND_INDEX_START))
    return undefined;
  const tableStart = afterHeadingIndex + tableStartInAfterHeading + 1;
  const tableEnd = findMarkdownTableEnd(current, tableStart);
  const table = current.slice(tableStart, tableEnd);
  if (!table.includes("|")) return undefined;

  const nonGaRows = table
    .split(/\r?\n/)
    .filter((line) => line.trim().startsWith("|"))
    .filter((line) => !isMarkdownSeparatorRow(line))
    .filter((line) => !isLegacyCommandHeaderRow(line))
    .filter((line) => !COMMAND_INDEX_IDS.has(commandIdFromLegacyRow(line)));
  const sections = [[heading, "", block].join("\n")];
  if (nonGaRows.length > 0) {
    sections.push(["## 其他命令", "", "| 命令 | 功能 |", "| --- | --- |", ...nonGaRows].join("\n"));
  }
  const replacement = sections.join("\n\n");
  const beforeHeading = current.slice(0, headingIndex);
  const afterTable = current
    .slice(tableEnd)
    .replace(
      new RegExp(
        `\\s*${escapeRegExp(COMMAND_INDEX_START)}[\\s\\S]*?${escapeRegExp(COMMAND_INDEX_END)}\\s*`,
      ),
      "\n\n",
    );
  const next = `${beforeHeading}${replacement}${afterTable.replace(/^\n{3,}/, "\n\n")}`;
  return { ok: true, value: next.endsWith("\n") ? next : `${next}\n`, issues: [] };
}

function findMarkdownTableEnd(content: string, tableStart: number): number {
  const rest = content.slice(tableStart);
  let offset = 0;
  for (const line of rest.split(/(?<=\n)/)) {
    if (!line.trim().startsWith("|")) break;
    offset += line.length;
  }
  return tableStart + offset;
}

function commandIdFromLegacyRow(line: string): string {
  const command = markdownTableCells(line)[0] ?? "";
  return command.replace(/`/g, "").replace(/^\//, "");
}

function isLegacyCommandHeaderRow(line: string): boolean {
  const firstCell = markdownTableCells(line)[0];
  return firstCell === "命令" || firstCell === "Command";
}

function isMarkdownSeparatorRow(line: string): boolean {
  const cells = markdownTableCells(line);
  return cells.length > 0 && cells.every((cell) => /^:?-{3,}:?$/.test(cell));
}

function markdownTableCells(line: string): string[] {
  return line
    .trim()
    .replace(/^\|/, "")
    .replace(/\|$/, "")
    .split("|")
    .map((cell) => cell.trim());
}

function extractCommandIndexBlock(current: string): string | undefined {
  const start = current.indexOf(COMMAND_INDEX_START);
  if (start < 0) return undefined;
  const end = current.indexOf(COMMAND_INDEX_END, start);
  if (end < 0) return undefined;
  return current.slice(start, end + COMMAND_INDEX_END.length);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function sorted(values: string[]): string[] {
  return [...values].sort();
}

function sameStringSet(left: string[], right: string[]): boolean {
  return JSON.stringify(sorted(left)) === JSON.stringify(sorted(right));
}

function _renderedGeneratedPaths(runtime: ProjectionRuntime, coreRoot: string): string[] {
  const rendered = renderSkills(runtime, coreRoot);
  if (!rendered.ok) return [];
  return [
    ...(rendered.value ?? []).map((file) => file.path),
    rootRuntimeDocPath(runtime),
    indexDocPath(runtime),
  ];
}

function defaultVendorRoot(): string {
  return join(repoRoot(), ".ai/vendor-skills");
}

function vendorRepoRoot(vendorRoot: string): string {
  return dirname(dirname(vendorRoot));
}

function vendorSourcePath(file: VendorManifestFile): string {
  return `.ai/vendor-skills/playwright-cli/files/${file.path}`;
}

function renderVendorSkill(
  runtime: ProjectionRuntime,
  vendorRoot: string,
  vendorFiles: VendorManifestFile[],
): VendorProjectionFile[] {
  const targetRoot = dirname(skillProjectionPath(runtime, "playwright-cli"));
  return vendorFiles.map((file) => ({
    path: join(targetRoot, file.path),
    content: readFileSync(join(vendorRoot, "playwright-cli/files", file.path)),
  }));
}

function renderedCopiedVendorPaths(
  runtime: ProjectionRuntime,
  vendorFiles: VendorManifestFile[],
): string[] {
  const targetRoot = dirname(skillProjectionPath(runtime, "playwright-cli"));
  return vendorFiles.map((file) => join(targetRoot, file.path));
}

function deletedInventoryRows(
  coreRoot: string,
  runtime: ProjectionRuntime,
): ProjectionInventoryRow[] {
  const inventory = parseProjectionInventory(
    readFileSync(join(coreRoot, "runtimes/projection-inventory.yaml"), "utf8"),
  );
  return inventory.filter((row) => row.runtime === runtime && row.disposition === "deleted");
}

function deletedInventoryPaths(coreRoot: string, runtime: ProjectionRuntime): string[] {
  return deletedInventoryRows(coreRoot, runtime).map((row) => row.path);
}

function walkRuntimeVendorFiles(root: string, displayRoot = root): string[] {
  const files: string[] = [];
  let entries: string[];
  try {
    entries = readdirSync(root).sort();
  } catch {
    return files;
  }
  for (const entry of entries) {
    const fullPath = join(root, entry);
    const stat = lstatSync(fullPath).isSymbolicLink() ? lstatSync(fullPath) : statSync(fullPath);
    if (stat.isDirectory()) files.push(...walkRuntimeVendorFiles(fullPath, displayRoot));
    if (stat.isFile() || stat.isSymbolicLink()) files.push(relative(displayRoot, fullPath));
  }
  return files;
}

function copiedVendorExtraIssues(
  root: string,
  runtime: ProjectionRuntime,
  vendorFiles: VendorManifestFile[],
): AiCoreIssue[] {
  const issues: AiCoreIssue[] = [];
  const targetRoot = dirname(skillProjectionPath(runtime, "playwright-cli"));
  const expected = new Set(vendorFiles.map((file) => file.path));
  for (const filePath of walkRuntimeVendorFiles(join(root, targetRoot))) {
    if (expected.has(filePath)) continue;
    issues.push({
      code: "projection.drift",
      severity: "error",
      message: "Copied vendor projection contains an unmanifested file.",
      path: join(targetRoot, filePath),
    });
  }
  return issues;
}

function copiedVendorRootIssue(root: string, runtime: ProjectionRuntime): AiCoreIssue | undefined {
  const targetRoot = dirname(skillProjectionPath(runtime, "playwright-cli"));
  const pathIssue = projectionVendorPathComponentIssue(root, runtime);
  if (pathIssue) return pathIssue;
  try {
    if (lstatSync(join(root, targetRoot)).isSymbolicLink()) {
      return {
        code: "projection.drift",
        severity: "error",
        message: "Copied vendor runtime skill root must not be a symlink.",
        path: targetRoot,
      };
    }
  } catch {
    return undefined;
  }
  return undefined;
}

function projectionVendorPathComponentIssue(
  root: string,
  runtime: ProjectionRuntime,
): AiCoreIssue | undefined {
  return symlinkPathComponentIssue({
    root,
    relativePath: dirname(skillProjectionPath(runtime, "playwright-cli")),
    code: "projection.drift",
    message: "Projection runtime vendor paths must not contain symlink components.",
  });
}

function projectionTargetPathIssue(root: string, relativePath: string): AiCoreIssue | undefined {
  const absoluteRoot = resolve(root);
  const absoluteTarget = resolve(absoluteRoot, relativePath);
  const targetRelativeToRoot = relative(absoluteRoot, absoluteTarget);
  if (
    targetRelativeToRoot === "" ||
    targetRelativeToRoot.startsWith("..") ||
    isAbsolute(targetRelativeToRoot)
  ) {
    return {
      code: "projection.drift",
      severity: "error",
      message: "Projection target path must stay under output root.",
      path: relativePath,
    };
  }
  return symlinkPathComponentIssue({
    root,
    relativePath,
    code: "projection.drift",
    message: "Projection target paths must not contain symlink components.",
  });
}

function pruneProjectionFile(root: string, relativePath: string): AiCoreIssue | undefined {
  const issue = projectionTargetPathIssue(root, relativePath);
  if (issue) return issue;
  const fullPath = join(root, relativePath);
  if (!existsSync(fullPath)) return undefined;
  if (lstatSync(fullPath).isDirectory()) {
    return {
      code: "projection.deleted_path_directory",
      severity: "error",
      message: "Deleted projection inventory paths must point to files, not directories.",
      path: relativePath,
    };
  }
  rmSync(fullPath, { force: true });
  return undefined;
}

function pruneDeletedRowIssues(row: ProjectionInventoryRow): AiCoreIssue[] {
  const issues: AiCoreIssue[] = [];
  if (!row.source || !row.reason) {
    issues.push({
      code: "projection.deleted_missing_metadata",
      severity: "error",
      message: "Deleted rows require source and reason before pruning.",
      path: row.path,
    });
  }
  if (!isExplicitRuntimeFilePath(row.path)) {
    issues.push({
      code: "projection.deleted_not_file_path",
      severity: "error",
      message: "Deleted rows must point to explicit runtime files before pruning.",
      path: row.path,
    });
  }
  return issues;
}

function isExplicitRuntimeFilePath(path: string): boolean {
  const fileName = path.split("/").filter(Boolean).at(-1) ?? "";
  return fileName.includes(".");
}

function deletedFilePresentIssues(
  root: string,
  coreRoot: string,
  runtime: ProjectionRuntime,
): AiCoreIssue[] {
  const issues: AiCoreIssue[] = [];
  for (const path of deletedInventoryPaths(coreRoot, runtime)) {
    const pathIssue = projectionTargetPathIssue(root, path);
    if (pathIssue) {
      issues.push(pathIssue);
      continue;
    }
    if (!existsSync(join(root, path))) continue;
    issues.push({
      code: "projection.deleted_file_present",
      severity: "error",
      message: "Runtime file is present but projection inventory marks it deleted.",
      path,
    });
  }
  return issues;
}

function writeProjectionFile(
  root: string,
  file: { path: string; content: string | Buffer },
): AiCoreIssue | undefined {
  const issue = projectionTargetPathIssue(root, file.path);
  if (issue) return issue;
  const fullPath = join(root, file.path);
  mkdirSync(dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, file.content);
  return undefined;
}

function checkProjectionContracts(
  coreRoot: string,
  selectedRuntimes: ProjectionRuntime[],
  vendorFiles?: VendorManifestFile[],
): AiCoreIssue[] {
  const issues: AiCoreIssue[] = [];
  const selected = new Set<ProjectionRuntime>(selectedRuntimes);
  const generatedByRuntime = new Map<ProjectionRuntime, RenderedSkillFile[]>();
  for (const runtime of selectedRuntimes) {
    const rendered = renderSkills(runtime, coreRoot);
    if (rendered.ok) generatedByRuntime.set(runtime, rendered.value ?? []);
    else issues.push(...rendered.issues);
  }
  const actualGeneratedPaths = selectedRuntimes.flatMap((runtime) => [
    ...(generatedByRuntime.get(runtime) ?? []).map((file) => file.path),
    rootRuntimeDocPath(runtime),
    indexDocPath(runtime),
  ]);
  const inventoryPath = join(coreRoot, "runtimes/projection-inventory.yaml");
  const inventoryResult = parseProjectionInventoryText(
    readFileSync(inventoryPath, "utf8"),
    ".ai/core/runtimes/projection-inventory.yaml",
  );
  if (!inventoryResult.ok) return [...issues, ...inventoryResult.issues];
  const inventory = inventoryResult.value ?? [];
  const inventoryGeneratedPaths = inventory
    .filter((row) => row.disposition === "generated" && selected.has(row.runtime))
    .map((row) => row.path);
  if (!sameStringSet(inventoryGeneratedPaths, actualGeneratedPaths)) {
    issues.push({
      code: "projection.inventory_mismatch",
      severity: "error",
      message: "Projection inventory generated files do not match renderer output.",
      path: ".ai/core/runtimes/projection-inventory.yaml",
    });
  }
  if (vendorFiles) {
    const actualCopiedVendorPaths = selectedRuntimes.flatMap((runtime) =>
      renderedCopiedVendorPaths(runtime, vendorFiles),
    );
    const inventoryCopiedVendorRows = inventory.filter(
      (row) => row.disposition === "copied_vendor" && selected.has(row.runtime),
    );
    const inventoryCopiedVendorPaths = inventoryCopiedVendorRows.map((row) => row.path);
    if (!sameStringSet(inventoryCopiedVendorPaths, actualCopiedVendorPaths)) {
      issues.push({
        code: "projection.inventory_mismatch",
        severity: "error",
        message: "Projection inventory copied vendor files do not match renderer output.",
        path: ".ai/core/runtimes/projection-inventory.yaml",
      });
    }
    const expectedSources = new Map<string, string>();
    for (const runtime of selectedRuntimes) {
      const targetRoot = dirname(skillProjectionPath(runtime, "playwright-cli"));
      for (const file of vendorFiles) {
        expectedSources.set(join(targetRoot, file.path), vendorSourcePath(file));
      }
    }
    if (inventoryCopiedVendorRows.some((row) => row.source !== expectedSources.get(row.path))) {
      issues.push({
        code: "projection.inventory_mismatch",
        severity: "error",
        message: "Projection inventory copied vendor source does not match frozen vendor artifact.",
        path: ".ai/core/runtimes/projection-inventory.yaml",
      });
    }
  }

  for (const runtime of selectedRuntimes) {
    const runtimePath = join(coreRoot, "runtimes", `${runtime}.yaml`);
    const runtimeContractPath = `.ai/core/runtimes/${runtime}.yaml`;
    const runtimeGeneratedFiles = parseYamlStringList(
      readFileSync(runtimePath, "utf8"),
      runtimeContractPath,
      "generated_files",
    );
    if (!runtimeGeneratedFiles.ok) {
      issues.push(...runtimeGeneratedFiles.issues);
      continue;
    }
    const runtimeRenderedGeneratedPaths = [
      ...(generatedByRuntime.get(runtime) ?? []).map((file) => file.path),
      rootRuntimeDocPath(runtime),
      indexDocPath(runtime),
    ];
    if (!sameStringSet(runtimeGeneratedFiles.value ?? [], runtimeRenderedGeneratedPaths)) {
      issues.push({
        code: "projection.runtime_mismatch",
        severity: "error",
        message: "Runtime generated_files do not match renderer output.",
        path: runtimeContractPath,
      });
    }
    if (vendorFiles) {
      const runtimeCopiedVendorFiles = parseYamlStringList(
        readFileSync(runtimePath, "utf8"),
        runtimeContractPath,
        "copied_vendor_files",
      );
      if (!runtimeCopiedVendorFiles.ok) {
        issues.push(...runtimeCopiedVendorFiles.issues);
        continue;
      }
      if (
        !sameStringSet(
          runtimeCopiedVendorFiles.value ?? [],
          renderedCopiedVendorPaths(runtime, vendorFiles),
        )
      ) {
        issues.push({
          code: "projection.runtime_mismatch",
          severity: "error",
          message: "Runtime copied_vendor_files do not match renderer output.",
          path: runtimeContractPath,
        });
      }
    }
  }
  return issues;
}

function _repoRootFromCoreRoot(coreRoot: string): string {
  return dirname(dirname(coreRoot));
}

function writeRootRuntimeDoc(
  root: string,
  runtime: ProjectionRuntime,
  commandIndexBlock: string,
  coreRoot: string,
): AiCoreIssue | undefined {
  const path = rootRuntimeDocPath(runtime);
  if (!isPermittedRuntimeDocSymlink(root, path)) {
    const pathIssue = projectionTargetPathIssue(root, path);
    if (pathIssue) return pathIssue;
  }
  const fullPath = join(root, path);
  const current = existsSync(fullPath) ? readFileSync(fullPath, "utf8") : undefined;
  const merged = mergeCommandIndexBlock(coreRoot, current, commandIndexBlock);
  if (!merged.ok) return { ...merged.issues[0], path };
  mkdirSync(dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, merged.value ?? "");
  return undefined;
}

function checkRootRuntimeDoc(
  root: string,
  runtime: ProjectionRuntime,
  commandIndexBlock: string,
): AiCoreIssue[] {
  const path = rootRuntimeDocPath(runtime);
  if (!isPermittedRuntimeDocSymlink(root, path)) {
    const pathIssue = projectionTargetPathIssue(root, path);
    if (pathIssue) return [pathIssue];
  }
  let current: string;
  try {
    current = readFileSync(join(root, path), "utf8");
  } catch {
    return [
      {
        code: "projection.drift",
        severity: "error",
        message: "Generated command index block is missing.",
        path,
      },
    ];
  }
  const markerState = commandIndexMarkerState(current);
  if (!markerState.ok) {
    return [
      {
        code: "projection.drift",
        severity: "error",
        message: markerState.message,
        path,
      },
    ];
  }
  if (markerState.completeBlocks !== 1) {
    return [
      {
        code: "projection.drift",
        severity: "error",
        message: "Root runtime doc must contain exactly one complete command index block.",
        path,
      },
    ];
  }
  if (extractCommandIndexBlock(current) !== commandIndexBlock) {
    return [
      {
        code: "projection.drift",
        severity: "error",
        message: "Generated command index block is stale.",
        path,
      },
    ];
  }
  return [];
}

export async function renderProjection(options: ProjectionOptions): Promise<AiCoreResult<null>> {
  const root = options.outputRoot ?? repoRoot();
  const coreRoot = options.coreRoot ?? defaultCoreRoot();
  const vendorRoot = options.vendorRoot ?? defaultVendorRoot();
  const vendorFiles = await readVendorSkillManifestFiles({
    id: "playwright-cli",
    root: vendorRepoRoot(vendorRoot),
    coreRoot,
  });
  if (!vendorFiles.ok) return { ok: false, issues: vendorFiles.issues };
  const commands = loadCommandContracts(coreRoot);
  if (!commands.ok) return { ok: false, issues: commands.issues };
  const commandIndexBlock = renderCommandIndexBlock(commands.value ?? []);
  const generatedByRuntime = new Map<ProjectionRuntime, RenderedSkillFile[]>();
  const generatedIssues: AiCoreIssue[] = [];
  for (const runtime of runtimes(options.runtime)) {
    const rendered = renderSkills(runtime, coreRoot);
    if (rendered.ok) generatedByRuntime.set(runtime, rendered.value ?? []);
    else generatedIssues.push(...rendered.issues);
  }
  if (generatedIssues.length > 0) return { ok: false, issues: generatedIssues };
  const pathIssues = runtimes(options.runtime).flatMap((runtime) => {
    const issue = projectionVendorPathComponentIssue(root, runtime);
    return issue ? [issue] : [];
  });
  if (pathIssues.length > 0) return { ok: false, issues: pathIssues };
  for (const runtime of runtimes(options.runtime)) {
    for (const file of generatedByRuntime.get(runtime) ?? []) {
      const issue = writeProjectionFile(root, file);
      if (issue) return { ok: false, issues: [issue] };
    }
    const rootDocIssue = writeRootRuntimeDoc(root, runtime, commandIndexBlock, coreRoot);
    if (rootDocIssue) return { ok: false, issues: [rootDocIssue] };
    const indexFile = renderRuntimeIndex(runtime, coreRoot);
    if (indexFile) {
      const indexIssue = writeProjectionFile(root, indexFile);
      if (indexIssue) return { ok: false, issues: [indexIssue] };
    }
    const vendorRootPathIssue = projectionTargetPathIssue(
      root,
      dirname(skillProjectionPath(runtime, "playwright-cli")),
    );
    if (vendorRootPathIssue) return { ok: false, issues: [vendorRootPathIssue] };
    rmSync(join(root, dirname(skillProjectionPath(runtime, "playwright-cli"))), {
      recursive: true,
      force: true,
    });
    for (const file of renderVendorSkill(runtime, vendorRoot, vendorFiles.value ?? [])) {
      const issue = writeProjectionFile(root, file);
      if (issue) return { ok: false, issues: [issue] };
    }
    if (options.prune === true) {
      const deletedRows = deletedInventoryRows(coreRoot, runtime);
      const deletedRowIssues = deletedRows.flatMap((row) => pruneDeletedRowIssues(row));
      if (deletedRowIssues.length > 0) return { ok: false, issues: deletedRowIssues };
      for (const row of deletedRows) {
        const issue = pruneProjectionFile(root, row.path);
        if (issue) return { ok: false, issues: [issue] };
      }
    }
  }
  return { ok: true, value: null, issues: [] };
}

export async function checkProjection(options: ProjectionOptions): Promise<AiCoreResult<null>> {
  const root = options.outputRoot ?? repoRoot();
  const coreRoot = options.coreRoot ?? defaultCoreRoot();
  const selectedRuntimes = runtimes(options.runtime);
  const vendorRoot = options.vendorRoot ?? defaultVendorRoot();
  const vendorFiles = await readVendorSkillManifestFiles({
    id: "playwright-cli",
    root: vendorRepoRoot(vendorRoot),
    coreRoot,
  });
  const issues: AiCoreIssue[] = checkProjectionContracts(
    coreRoot,
    selectedRuntimes,
    vendorFiles.ok ? vendorFiles.value : undefined,
  );
  if (!vendorFiles.ok) issues.push(...vendorFiles.issues);
  const commands = loadCommandContracts(coreRoot);
  const commandIndexBlock = commands.ok ? renderCommandIndexBlock(commands.value ?? []) : undefined;
  if (!commands.ok) issues.push(...commands.issues);
  const generatedByRuntime = new Map<ProjectionRuntime, RenderedSkillFile[]>();
  for (const runtime of selectedRuntimes) {
    const rendered = renderSkills(runtime, coreRoot);
    if (rendered.ok) generatedByRuntime.set(runtime, rendered.value ?? []);
    else issues.push(...rendered.issues);
  }
  for (const runtime of selectedRuntimes) {
    issues.push(...deletedFilePresentIssues(root, coreRoot, runtime));
    const runtimePathIssue = projectionVendorPathComponentIssue(root, runtime);
    if (runtimePathIssue) {
      issues.push(runtimePathIssue);
      continue;
    }
    for (const file of generatedByRuntime.get(runtime) ?? []) {
      const pathIssue = projectionTargetPathIssue(root, file.path);
      if (pathIssue) {
        issues.push(pathIssue);
        continue;
      }
      const fullPath = join(root, file.path);
      let current: string;
      try {
        current = readFileSync(fullPath, "utf8");
      } catch {
        issues.push({
          code: "projection.drift",
          severity: "error",
          message: "Generated projection content is missing.",
          path: file.path,
        });
        continue;
      }
      if (current !== file.content) {
        issues.push({
          code: "projection.drift",
          severity: "error",
          message: "Generated projection content is stale.",
          path: file.path,
        });
      }
    }
    if (commandIndexBlock) issues.push(...checkRootRuntimeDoc(root, runtime, commandIndexBlock));
    const indexFile = renderRuntimeIndex(runtime, coreRoot);
    if (indexFile) {
      const indexPathIssue = projectionTargetPathIssue(root, indexFile.path);
      if (indexPathIssue) issues.push(indexPathIssue);
      else {
        try {
          const currentIndex = readFileSync(join(root, indexFile.path), "utf8");
          if (currentIndex !== indexFile.content) {
            issues.push({
              code: "projection.drift",
              severity: "error",
              message: "Generated projection content is stale.",
              path: indexFile.path,
            });
          }
        } catch {
          issues.push({
            code: "projection.drift",
            severity: "error",
            message: "Generated projection content is missing.",
            path: indexFile.path,
          });
        }
      }
    }
    if (!vendorFiles.ok) continue;
    const copiedVendorRoot = copiedVendorRootIssue(root, runtime);
    if (copiedVendorRoot) {
      issues.push(copiedVendorRoot);
      continue;
    }
    issues.push(...copiedVendorExtraIssues(root, runtime, vendorFiles.value ?? []));
    for (const file of renderVendorSkill(runtime, vendorRoot, vendorFiles.value ?? [])) {
      const fullPath = join(root, file.path);
      let current: Buffer;
      try {
        if (lstatSync(fullPath).isSymbolicLink()) {
          issues.push({
            code: "projection.drift",
            severity: "error",
            message: "Copied vendor projection content must not be a symlink.",
            path: file.path,
          });
          continue;
        }
        const pathIssue = projectionTargetPathIssue(root, file.path);
        if (pathIssue) {
          issues.push(pathIssue);
          continue;
        }
        current = readFileSync(fullPath);
      } catch {
        issues.push({
          code: "projection.drift",
          severity: "error",
          message: "Copied vendor projection content is missing.",
          path: file.path,
        });
        continue;
      }
      if (!current.equals(file.content)) {
        issues.push({
          code: "projection.drift",
          severity: "error",
          message: "Copied vendor projection content is stale.",
          path: file.path,
        });
      }
    }
  }
  return { ok: issues.length === 0, value: null, issues };
}
