import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import type { ProjectionRuntime } from "../../runtime/projection-targets.ts";
import { repoRoot } from "../paths.ts";
import { parseProductSkillContract } from "../product-skill-contract.ts";
import {
  type RenderedSkillFile,
  renderProductSkill,
  type SkillCallGraph,
} from "../skill-renderer.ts";
import type { AiCoreIssue, AiCoreResult } from "../types.ts";
import { parseYamlTopLevelScalars } from "../yaml-contract.ts";
import { escapeMarkdownTableCell, loadCommandContracts } from "./command-contracts.ts";

export type ProjectionOptions = {
  runtime: "all" | ProjectionRuntime;
  outputRoot?: string;
  coreRoot?: string;
  vendorRoot?: string;
  prune?: boolean;
};

export type VendorProjectionFile = {
  path: string;
  content: Buffer;
};

export type CommandContract = {
  id: string;
  skill: string;
  userInvocable: "true" | "false";
  summary: string;
};

export const COMMAND_INDEX_START = "<!-- ai-core:start command-index -->";
export const COMMAND_INDEX_END = "<!-- ai-core:end command-index -->";
export const ROUTING_HEADING = "## Routing";
export const ROUTING_HEADING_CN = "## 路由规则";
export const LEGACY_ROUTING_GUARD_HEADING = "## Routing Guard";
export const ROUTING_GUARD_SOURCE_PATH = "rules/routing-guard.md";

export function loadRoutingGuardSection(coreRoot: string): string {
  const path = join(coreRoot, ROUTING_GUARD_SOURCE_PATH);
  return readFileSync(path, "utf8").replace(/\n+$/, "");
}
export const COMMAND_INDEX_ORDER = [
  "workspace-manage",
  "case-draft",
  "case-edit",
  "knowledge-curate",
  "bug-file",
  "conflict-analyze",
  "case-hotfix",
  "playwright-automation",
  "diff-scan",
  "infra-diagnose",
];
export const COMMAND_INDEX_IDS = new Set(COMMAND_INDEX_ORDER);

export function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

export function generatedHeader(source: string): string {
  return [
    "<!-- generated by kata ai-core; do not edit -->",
    `<!-- ai-core-hash: ${sha256(source)} -->`,
    "",
  ].join("\n");
}

export function defaultCoreRoot(): string {
  return join(repoRoot(), ".ai/core");
}

export function productSkillRoots(coreRoot: string): string[] {
  return readdirSync(join(coreRoot, "skills"), { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => join(coreRoot, "skills", entry.name))
    .filter((skillRoot) => {
      try {
        return statSync(join(skillRoot, "skill.yaml")).isFile();
      } catch {
        return false;
      }
    })
    .sort();
}

export type WorkflowSummary = {
  id: string;
  entrySkill: string;
  uses: string[];
  prompts: string[];
};

export function parseWorkflowStepReferences(text: string): { uses: string[]; prompts: string[] } {
  const uses: string[] = [];
  const prompts: string[] = [];
  let inSteps = false;
  for (const raw of text.split(/\r?\n/)) {
    if (raw === "steps:") {
      inSteps = true;
      continue;
    }
    if (!inSteps) continue;
    if (raw.length > 0 && !/^\s/.test(raw)) {
      inSteps = false;
      continue;
    }
    const trimmed = raw.trim();
    if (trimmed.startsWith("uses:")) {
      uses.push(trimmed.slice("uses:".length).trim());
    } else if (trimmed.startsWith("prompt:")) {
      prompts.push(trimmed.slice("prompt:".length).trim());
    }
  }
  return { uses, prompts };
}

export function loadWorkflowSummaries(coreRoot: string): WorkflowSummary[] {
  const dir = join(coreRoot, "workflows");
  const summaries: WorkflowSummary[] = [];
  let files: string[];
  try {
    files = readdirSync(dir)
      .filter((f) => f.endsWith(".workflow.yaml"))
      .sort();
  } catch {
    return summaries;
  }
  for (const file of files) {
    const text = readFileSync(join(dir, file), "utf8");
    const path = `.ai/core/workflows/${file}`;
    const top = parseYamlTopLevelScalars(text, path);
    if (!top.ok) continue;
    const fields = top.value ?? {};
    const id = fields.id ?? "";
    const entrySkill = fields.entry_skill ?? "";
    const { uses, prompts } = parseWorkflowStepReferences(text);
    summaries.push({ id, entrySkill, uses, prompts });
  }
  return summaries;
}

export function stripSkillVersion(idWithVersion: string): string {
  return idWithVersion.replace(/@\d+$/, "");
}

export function pushUnique(target: string[], value: string): void {
  if (!target.includes(value)) target.push(value);
}

export function buildCallGraph(
  coreRoot: string,
  commands: CommandContract[],
): Map<string, SkillCallGraph> {
  const graphs = new Map<string, SkillCallGraph>();

  function ensure(skillName: string): SkillCallGraph {
    let graph = graphs.get(skillName);
    if (!graph) {
      graph = {
        upstreamCommands: [],
        downstreamWorkflows: [],
        downstreamAgents: [],
        downstreamPlugins: [],
        downstreamPrompts: [],
      };
      graphs.set(skillName, graph);
    }
    return graph;
  }

  for (const cmd of commands) {
    const skillName = stripSkillVersion(cmd.skill);
    pushUnique(ensure(skillName).upstreamCommands, cmd.id);
  }

  for (const workflow of loadWorkflowSummaries(coreRoot)) {
    const skillName = stripSkillVersion(workflow.entrySkill);
    if (!skillName) continue;
    const graph = ensure(skillName);
    pushUnique(graph.downstreamWorkflows, workflow.id);
    for (const reference of workflow.uses) {
      if (reference.startsWith("agent:")) {
        pushUnique(graph.downstreamAgents, reference.slice("agent:".length));
      } else if (reference.startsWith("plugin:")) {
        pushUnique(graph.downstreamPlugins, reference.slice("plugin:".length));
      }
    }
    for (const prompt of workflow.prompts) {
      pushUnique(graph.downstreamPrompts, prompt);
    }
  }

  return graphs;
}

export function loadAllCommandContracts(coreRoot: string): CommandContract[] {
  const result = loadCommandContracts(coreRoot);
  return result.ok ? (result.value ?? []) : [];
}

export type IndexEntry = {
  command: string;
  skill: string;
  outputs: string[];
  workflows: string[];
  agents: string[];
  prompts: string[];
  plugins: string[];
};

export function loadSkillOutputs(coreRoot: string, skillName: string): string[] {
  const skillFile = join(coreRoot, "skills", skillName, "skill.yaml");
  if (!existsSync(skillFile)) return [];
  const text = readFileSync(skillFile, "utf8");
  const parsed = parseProductSkillContract(text, `.ai/core/skills/${skillName}/skill.yaml`);
  return parsed.ok ? (parsed.value?.outputs ?? []) : [];
}

export function buildIndexEntries(
  coreRoot: string,
  commands: CommandContract[],
  callGraphs: Map<string, SkillCallGraph>,
): IndexEntry[] {
  return commands.map((cmd) => {
    const skillName = stripSkillVersion(cmd.skill);
    const callGraph = callGraphs.get(skillName);
    return {
      command: cmd.id,
      skill: skillName,
      outputs: loadSkillOutputs(coreRoot, skillName),
      workflows: callGraph?.downstreamWorkflows ?? [],
      agents: callGraph?.downstreamAgents ?? [],
      prompts: callGraph?.downstreamPrompts ?? [],
      plugins: callGraph?.downstreamPlugins ?? [],
    };
  });
}

export function renderIndexDoc(entries: IndexEntry[]): string {
  const headerSource = JSON.stringify(entries);
  const rows = entries.map((entry) => {
    const cells = [
      `/${entry.command}`,
      entry.skill,
      entry.workflows.join(", ") || "-",
      entry.agents.join(", ") || "-",
      entry.prompts.join(", ") || "-",
      entry.plugins.join(", ") || "-",
      entry.outputs.join(", ") || "-",
    ].map(escapeMarkdownTableCell);
    return `| ${cells.join(" | ")} |`;
  });
  return [
    "# kata 命令调用图",
    "",
    generatedHeader(headerSource).trimEnd(),
    "",
    "每行映射：command → skill → workflow → 下游 agents/prompts/plugins → 输出。冷启动时优先读取本表，无需遍历 commands/。",
    "",
    "| Command | Skill | Workflow | Agents | Prompts | Plugins | Outputs |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

export function indexDocPath(runtime: ProjectionRuntime): string {
  return runtime === "codex" ? ".agents/INDEX.md" : ".claude/INDEX.md";
}

export function renderRuntimeIndex(
  runtime: ProjectionRuntime,
  coreRoot: string,
): { path: string; content: string } | undefined {
  const commandsResult = loadCommandContracts(coreRoot);
  if (!commandsResult.ok) return undefined;
  const commands = commandsResult.value ?? [];
  const callGraphs = buildCallGraph(coreRoot, commands);
  const entries = buildIndexEntries(coreRoot, commands, callGraphs);
  return { path: indexDocPath(runtime), content: renderIndexDoc(entries) };
}

export function renderSkills(
  runtime: ProjectionRuntime,
  coreRoot: string,
): AiCoreResult<RenderedSkillFile[]> {
  const files: RenderedSkillFile[] = [];
  const issues: AiCoreIssue[] = [];
  const callGraphs = buildCallGraph(coreRoot, loadAllCommandContracts(coreRoot));
  for (const skillRoot of productSkillRoots(coreRoot)) {
    const skillSource = readFileSync(join(skillRoot, "skill.yaml"), "utf8");
    const skillName = relative(coreRoot, skillRoot).split("/").pop() ?? "";
    const result = renderProductSkill({
      runtime,
      skillRoot,
      repoRelativeSkillRoot: `.ai/core/${relative(coreRoot, skillRoot)}`,
      generatedHeader: generatedHeader(skillSource),
      callGraph: callGraphs.get(skillName),
    });
    if (result.ok) files.push(...(result.value ?? []));
    else issues.push(...result.issues);
  }
  if (issues.length > 0) return { ok: false, issues };
  return { ok: true, value: files, issues: [] };
}

export function runtimes(option: "all" | ProjectionRuntime): ProjectionRuntime[] {
  return option === "all" ? ["claude", "codex"] : [option];
}
