import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { lintHandoffDoubleTrack } from "@shared/lint/handoff-double-track.ts";

describe("gate: handoff_double_track", () => {
  let scratch: string;
  beforeEach(() => {
    scratch = mkdtempSync(join(tmpdir(), "gate-hd-"));
  });
  afterEach(() => rmSync(scratch, { recursive: true, force: true }));

  function seedRun(opts: { json?: string; md?: string }) {
    const dir = join(
      scratch,
      "dataAssets/features/v6.4/【v6.4】feature-x/runs/20260510-1430-aaaaaaaa",
    );
    mkdirSync(dir, { recursive: true });
    if (opts.json !== undefined) writeFileSync(join(dir, "handoff.json"), opts.json);
    if (opts.md !== undefined) writeFileSync(join(dir, "handoff.md"), opts.md);
  }

  function validHandoff() {
    return {
      schema: "PlaywrightAutomationHandoff@2",
      feature_id: "2026-04-x",
      run_id: "20260510-1430-aaaaaaaa",
      status: "passed",
      intent_id: "SR-INTENT-X",
      source_refs: {
        intent: "SR-INTENT-X",
        env: "SR-ENV-PREFLIGHT-X",
        probe: "SR-UI-PROBE-X",
        self_run: "SR-SELF-RUN-X",
      },
      run_command: "npx playwright test",
      acceptance_command:
        "KATA_DATAASSETS_ENV=ltqc-local.yaml KATA_ACTIVE_PROJECT=dataAssets npx playwright test 'features/2026-04-x/tests/runners/full.spec.ts' --project=chromium --headed --reporter=line",
      run_exit_code: 0,
      results: {
        total: 1,
        passed: 1,
        failed: 0,
        skipped: 0,
        report_paths: {
          playwright_json: "results.json",
          allure: "allure-results",
          stdout: "stdout.log",
        },
      },
      quality_gates: [{ name: "handoff_double_track", status: "passed" }],
      platform_records: [
        {
          case_id: "P0-1",
          record_type: "standard-definition",
          record_name: "qa_auto_standard_20260702",
          evidence_path: "runs/20260510-1430-aaaaaaaa/allure-results/record.png",
        },
      ],
      unresolved_blockers: [],
      next_actions: [],
      excluded_cases: [],
    };
  }

  function validHandoffMd() {
    return [
      "<!-- generated by kata handoff render; do not edit -->",
      "<!-- source: handoff.json -->",
      "<!-- schema: PlaywrightAutomationHandoff@2 -->",
      "## Human Acceptance Command",
      "```bash",
      "KATA_DATAASSETS_ENV=ltqc-local.yaml KATA_ACTIVE_PROJECT=dataAssets npx playwright test 'features/2026-04-x/tests/runners/full.spec.ts' --project=chromium --headed --reporter=line",
      "```",
    ].join("\n");
  }

  it("passes when both files exist and md has generated header", () => {
    seedRun({
      json: JSON.stringify(validHandoff()),
      md: validHandoffMd(),
    });
    const r = lintHandoffDoubleTrack(scratch);
    expect(r.violations).toHaveLength(0);
  });

  it("reports md missing", () => {
    seedRun({ json: "{}" });
    const r = lintHandoffDoubleTrack(scratch);
    expect(r.violations.some((v) => v.rule === "handoff_md_missing")).toBe(true);
  });

  it("reports json missing", () => {
    seedRun({
      md: "<!-- generated by kata handoff render; do not edit -->",
    });
    const r = lintHandoffDoubleTrack(scratch);
    expect(r.violations.some((v) => v.rule === "handoff_json_missing")).toBe(true);
  });

  it("reports md without generated header", () => {
    seedRun({ json: "{}", md: "edited by hand" });
    const r = lintHandoffDoubleTrack(scratch);
    expect(r.violations.some((v) => v.rule === "handoff_md_header_missing")).toBe(true);
  });

  it("reports invalid handoff.json schema", () => {
    seedRun({
      json: JSON.stringify({ schema: "bad" }),
      md: "<!-- generated by kata handoff render; do not edit -->\n<!-- source: handoff.json -->\n<!-- schema: PlaywrightAutomationHandoff@2 -->\n",
    });
    const r = lintHandoffDoubleTrack(scratch);
    expect(r.violations.some((v) => v.rule === "handoff_json_schema_invalid")).toBe(true);
  });

  it("reports missing schema marker in generated markdown", () => {
    seedRun({
      json: JSON.stringify(validHandoff()),
      md: [
        "<!-- generated by kata handoff render; do not edit -->",
        "<!-- source: handoff.json -->",
        "## Human Acceptance Command",
        "npx playwright test tests/runners/full.spec.ts --headed",
      ].join("\n"),
    });
    const r = lintHandoffDoubleTrack(scratch);
    expect(r.violations.some((v) => v.rule === "handoff_md_schema_marker_missing")).toBe(true);
  });

  it("reports generated markdown missing the headed full acceptance command", () => {
    seedRun({
      json: JSON.stringify(validHandoff()),
      md: "<!-- generated by kata handoff render; do not edit -->\n<!-- source: handoff.json -->\n<!-- schema: PlaywrightAutomationHandoff@2 -->\nfoo",
    });
    const r = lintHandoffDoubleTrack(scratch);
    expect(r.violations.some((v) => v.rule === "handoff_md_acceptance_command_missing")).toBe(true);
    expect(r.violations.some((v) => v.rule === "handoff_md_acceptance_command_invalid")).toBe(true);
  });

  it("reports acceptance command that is not headed full", () => {
    seedRun({
      json: JSON.stringify(validHandoff()),
      md: [
        "<!-- generated by kata handoff render; do not edit -->",
        "<!-- source: handoff.json -->",
        "<!-- schema: PlaywrightAutomationHandoff@2 -->",
        "## Human Acceptance Command",
        "npx playwright test tests/runners/smoke.spec.ts",
      ].join("\n"),
    });
    const r = lintHandoffDoubleTrack(scratch);
    expect(r.violations.some((v) => v.rule === "handoff_md_acceptance_command_invalid")).toBe(true);
  });
});
