// Generated by kata automation coverage. Do not add business logic here.
import { loadPlaywrightAutomationConfig } from "../../../../../../../../runtime/automation/config/playwright";
import { orderAutomationCases } from "../../../../../../../../runtime/automation/runner/case-order";

const generatedCases: ReadonlyArray<{ readonly caseId: string; readonly module: string }> = [
  { caseId: "C0001", module: "../cases/c0001-historical-built-in-rule-status.spec.ts" },
  { caseId: "C0002", module: "../cases/c0002-monotonic-rule-status.spec.ts" },
  { caseId: "C0003", module: "../cases/c0003-time-difference-rule-status.spec.ts" },
];

const orderedCases = orderAutomationCases(
  generatedCases,
  loadPlaywrightAutomationConfig().sortCases,
);

for (const generatedCase of orderedCases) {
  await import(generatedCase.module);
}
