// Generated by kata automation coverage. Do not add business logic here.
import { loadPlaywrightAutomationConfig } from "../../../../../../../../lib/automation/playwright-config";
import { orderAutomationCases } from "../../../../../../../../lib/automation/case-order";

const generatedCases: ReadonlyArray<{ readonly caseId: string; readonly module: string }> = [
  { caseId: "C0001", module: "../cases/c0001-range-enum-and-numeric-flow.spec.ts" },
  { caseId: "C0002", module: "../cases/c0002-range-enum-or-save.spec.ts" },
  { caseId: "C0003", module: "../cases/c0003-range-only-save.spec.ts" },
  { caseId: "C0004", module: "../cases/c0004-enum-only-save.spec.ts" },
  { caseId: "C0005", module: "../cases/c0005-enum-not-in-save.spec.ts" },
  { caseId: "C0006", module: "../cases/c0006-existing-enum-not-in-option.spec.ts" },
  { caseId: "C0007", module: "../cases/c0007-string-range-enum-save.spec.ts" },
  { caseId: "C0008", module: "../cases/c0008-range-operator-required.spec.ts" },
  { caseId: "C0009", module: "../cases/c0009-enum-in-value-required.spec.ts" },
  { caseId: "C0010", module: "../cases/c0010-range-enum-relation-required.spec.ts" },
  { caseId: "C0011", module: "../cases/c0011-range-or-enum-required.spec.ts" },
  { caseId: "C0012", module: "../cases/c0012-edit-and-switch-relation.spec.ts" },
  { caseId: "C0013", module: "../cases/c0013-clone-range-enum-rule.spec.ts" },
  { caseId: "C0014", module: "../cases/c0014-filtered-rule-save.spec.ts" },
  { caseId: "C0016", module: "../cases/c0016-or-rule-passed-task.spec.ts" },
  { caseId: "C0017", module: "../cases/c0017-weak-rule-report-marker.spec.ts" },
  { caseId: "C0018", module: "../cases/c0018-range-enum-failed-log.spec.ts" },
  { caseId: "C0019", module: "../cases/c0019-range-enum-sampling.spec.ts" },
  { caseId: "C0020", module: "../cases/c0020-range-enum-partition.spec.ts" },
  { caseId: "C0021", module: "../cases/c0021-range-enum-built-in-rule.spec.ts" },
  { caseId: "C0022", module: "../cases/c0022-range-enum-failed-details.spec.ts" },
  { caseId: "C0023", module: "../cases/c0023-range-enum-failed-download.spec.ts" },
  { caseId: "C0024", module: "../cases/c0024-range-enum-passed-no-details.spec.ts" },
  { caseId: "C0025", module: "../cases/c0025-enum-in-passed-report.spec.ts" },
  { caseId: "C0026", module: "../cases/c0026-enum-in-failed-report.spec.ts" },
  { caseId: "C0027", module: "../cases/c0027-enum-not-in-failed-report.spec.ts" },
];

const orderedCases = orderAutomationCases(
  generatedCases,
  loadPlaywrightAutomationConfig().sortCases,
);

for (const generatedCase of orderedCases) {
  await import(generatedCase.module);
}
