// Generated by kata automation coverage. Do not add business logic here.
import "../cases/t06-c006.ts";
import "../cases/t07-c007.ts";
import "../cases/t08-c008.ts";
import "../cases/t09-c009.ts";
import "../cases/t10-c010.ts";
import "../cases/t11-c011.ts";
import "../cases/t12-c012.ts";
import "../cases/t13-c013.ts";
import "../cases/t14-c014.ts";
import "../cases/t37-c037.ts";
