// Generated by kata automation coverage. Do not add business logic here.
import { loadPlaywrightAutomationConfig } from "../../../../../../../../runtime/automation/config/playwright";
import { orderAutomationCases } from "../../../../../../../../runtime/automation/runner/case-order";

const generatedCases: ReadonlyArray<{ readonly caseId: string; readonly module: string }> = [
  { caseId: "C0001", module: "../cases/c0001-rule-set-independent-run.spec.ts" },
  { caseId: "C0002", module: "../cases/c0002-rule-set-edit-delete-prompt.spec.ts" },
  { caseId: "C0003", module: "../cases/c0003-field-integrity-rule-result.spec.ts" },
  { caseId: "C0004", module: "../cases/c0004-table-row-count-rule-result.spec.ts" },
];

const orderedCases = orderAutomationCases(
  generatedCases,
  loadPlaywrightAutomationConfig().sortCases,
);

for (const generatedCase of orderedCases) {
  await import(generatedCase.module);
}
