// spec: features/2099-01-lt-dq-main-flow/岚图主流程用例整理.md#L9073,#L9166,#L9259,#L9352,#L9445,#L9538,#L9631,#L9725,#L9862,#L10000,#L10093,#L10186,#L10279,#L10372,#L10465,#L10558,#L10651,#L10744,#L10837,#L10930,#L11023,#L11117,#L11210,#L11303,#L11441,#L11579,#L11672,#L11765,#L11858,#L11952,#L12046,#L12140,#L12234,#L12373,#L12467,#L12561,#L12699,#L12837,#L12930,#L13023,#L13116,#L13209,#L13302,#L13395,#L13533
// intent: SR-INTENT-2099-01-DQ-SPARKTHRIFT-VALIDATION-L9073-L13533
// probe: SR-UI-PROBE-20260527-DQ-SPARKTHRIFT-COMPLETENESS-001
// page: _shared/pages/2099-01-lt-dq-main-flow/data-quality-page.ts
// generated_at: 2026-05-27T00:00:00Z
// SourceRefs: SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L9073, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L9166, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L9259, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L9352, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L9445, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L9538, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L9631, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L9725, SR-2099-01-DQ-SPARKTHRIFT-COMPLETENESS-L9862, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10000, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10093, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10186, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10279, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10372, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10465, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10558, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10651, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10744, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10837, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L10930, SR-2099-01-DQ-SPARKTHRIFT-VALIDITY-L11023, SR-2099-01-DQ-SPARKTHRIFT-UNIQUENESS-L11117, SR-2099-01-DQ-SPARKTHRIFT-UNIQUENESS-L11210, SR-2099-01-DQ-SPARKTHRIFT-UNIQUENESS-L11303, SR-2099-01-DQ-SPARKTHRIFT-UNIQUENESS-L11441, SR-2099-01-DQ-SPARKTHRIFT-STATISTICAL-L11579, SR-2099-01-DQ-SPARKTHRIFT-STATISTICAL-L11672, SR-2099-01-DQ-SPARKTHRIFT-STATISTICAL-L11765, SR-2099-01-DQ-SPARKTHRIFT-CUSTOMSQL-L11858, SR-2099-01-DQ-SPARKTHRIFT-CUSTOMSQL-L11952, SR-2099-01-DQ-SPARKTHRIFT-CUSTOMSQL-L12046, SR-2099-01-DQ-SPARKTHRIFT-CUSTOMSQL-L12140, SR-2099-01-DQ-SPARKTHRIFT-CUSTOMSQL-L12234, SR-2099-01-DQ-SPARKTHRIFT-CUSTOMSQL-L12373, SR-2099-01-DQ-SPARKTHRIFT-CUSTOMSQL-L12467, SR-2099-01-DQ-SPARKTHRIFT-CONSISTENCY-L12561, SR-2099-01-DQ-SPARKTHRIFT-CONSISTENCY-L12699, SR-2099-01-DQ-SPARKTHRIFT-TIMELINESS-L12837, SR-2099-01-DQ-SPARKTHRIFT-TIMELINESS-L12930, SR-2099-01-DQ-SPARKTHRIFT-REASONABLENESS-L13023, SR-2099-01-DQ-SPARKTHRIFT-REASONABLENESS-L13116, SR-2099-01-DQ-SPARKTHRIFT-REASONABLENESS-L13209, SR-2099-01-DQ-SPARKTHRIFT-REASONABLENESS-L13302, SR-2099-01-DQ-SPARKTHRIFT-REASONABLENESS-L13395, SR-2099-01-DQ-SPARKTHRIFT-REASONABLENESS-L13533, SR-UI-PROBE-20260527-DQ-SPARKTHRIFT-COMPLETENESS-001
import { test } from "../../../../_shared/fixtures/step-screenshot";
import {
  expectSparkThriftQualityRuleValidationContract,
  type SparkThriftQualityRuleValidationScenario,
} from "../../../../_shared/pages/2099-01-lt-dq-main-flow/data-quality-page";
import { ensureSelectedDtstackPreconditionTables } from "../helpers/dtstack-preconditions";

test.use({
  storageState:
    process.env.UI_AUTOTEST_SESSION_PATH ??
    "workspace/dataAssets/.kata/auth/dataAssets/session-ltqc-local.json",
});
test.setTimeout(90 * 60 * 1000);

const PRECOND_TABLES_FILE =
  "workspace/dataAssets/features/2099-01-lt-dq-main-flow/tests/precond/sparkthrift-rule-validation-tables.yaml";

const scenarios: readonly SparkThriftQualityRuleValidationScenario[] = [
  {
    archiveLine: 9073,
    title: "完整性校验-字段级-空值数",
    tableName: "dwd_voyah_dq_rule_01_main",
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "空值数",
    fields: ["car_model_name"],
    expectation: { method: "固定值", operator: "=", value: "0" },
    description: "校验空值数分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_01_F003", "car_model_name"],
  },
  {
    archiveLine: 9166,
    title: "完整性校验-字段级-空值率",
    tableName: "dwd_voyah_dq_rule_02_main",
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "空值率",
    fields: ["car_model_name", "owner_phone"],
    fieldLogic: "or",
    expectation: { method: "固定值", operator: "<", value: "1%" },
    description: "校验空值率分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0%",
    failExpectedValue: "25%",
    dirtyEvidence: ["ORD_02_F003", "car_model_name"],
  },
  {
    archiveLine: 9259,
    title: "完整性校验-字段级-空串数",
    tableName: "dwd_voyah_dq_rule_03_main",
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "空串数",
    fields: ["delivery_center"],
    expectation: { method: "固定值", operator: "!=", value: "1" },
    description: "校验空串数分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_03_F003", "delivery_center"],
  },
  {
    archiveLine: 9352,
    title: "完整性校验-字段级-空串率",
    tableName: "dwd_voyah_dq_rule_04_main",
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "空串率",
    fields: ["delivery_center", "car_series_name"],
    fieldLogic: "and",
    expectation: { method: "固定值", operator: "<=", value: "0%" },
    description: "校验空串率分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0%",
    failExpectedValue: "25%",
    dirtyEvidence: ["ORD_04_F003", "delivery_center"],
  },
  {
    archiveLine: 9445,
    title: "完整性校验-字段级-字段取值校验",
    tableName: "dwd_voyah_dq_rule_05_main",
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "字段取值校验",
    fields: ["final_price", "power_type"],
    fieldLogic: "and",
    expectation: { method: "固定值", operator: ">=", value: "0" },
    description: "校验字段取值分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部 final_price >= 0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_05_F003", "-100.000"],
  },
  {
    archiveLine: 9538,
    title: "完整性校验-字段级-key范围校验",
    tableName: "dwd_voyah_dq_rule_06_main",
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "key范围校验",
    fields: ["json_payload"],
    expectation: { method: "不包含", value: "debug.errorCode" },
    description: "校验key范围分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "key 全部不存在",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_06_F003", "debug.errorCode"],
  },
  {
    archiveLine: 9631,
    title: "完整性校验-单表-表行数",
    tableName: "dwd_voyah_dq_rule_07_main",
    ruleCategory: "完整性校验",
    scope: "单表",
    statisticFunction: "表行数",
    fields: [],
    expectation: { method: "固定值", operator: "=", value: "4" },
    description: "校验表行数分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "4",
    failExpectedValue: "5",
    dirtyEvidence: ["5", "stat_date"],
  },
  {
    archiveLine: 9725,
    title: "完整性校验-多表数据行数对比",
    tableName: "dwd_voyah_dq_rule_08_main",
    comparisonTableName: "dwd_voyah_dq_rule_08_ref",
    ruleCategory: "完整性校验",
    scope: "多表",
    statisticFunction: "多表数据行数对比",
    fields: [],
    expectation: { method: "数量差异", operator: "<=", value: "0" },
    description: "校验多表行数分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "差异 0",
    failExpectedValue: "差异 1",
    dirtyEvidence: ["ORD_08_F004", "dwd_voyah_dq_rule_08_ref"],
  },
  {
    archiveLine: 9862,
    title: "完整性校验-多表数据内容对比",
    tableName: "dwd_voyah_dq_rule_09_main",
    comparisonTableName: "dwd_voyah_dq_rule_09_ref",
    ruleCategory: "完整性校验",
    scope: "多表",
    statisticFunction: "多表数据内容对比",
    fields: ["car_model_code", "power_type"],
    comparisonFields: ["car_model_code", "power_type"],
    primaryKeys: ["vin", "car_series_code"],
    comparisonPrimaryKeys: ["vin", "car_series_code"],
    fieldLogic: "and",
    expectation: { method: "in", value: "car_model_code" },
    description: "校验多表内容分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "内容差异 0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "MISMATCH_MODEL"],
  },
  {
    archiveLine: 10000,
    title: "有效性校验-数值-取值范围",
    tableName: "dwd_voyah_dq_rule_10_main",
    ruleCategory: "有效性校验",
    statisticFunction: "数值-取值范围",
    fields: ["final_price"],
    ruleInputs: [{ label: "期望值", value: ">= 0 且 <= 1000000" }],
    description: "校验数值范围分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部在 [0,1000000] 范围内",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_10_F003", "-100.000"],
  },
  {
    archiveLine: 10093,
    title: "有效性校验-格式-身份证号",
    tableName: "dwd_voyah_dq_rule_11_main",
    ruleCategory: "有效性校验",
    statisticFunction: "格式-身份证号",
    fields: ["owner_id_card"],
    expectation: { method: "固定值", operator: "=", value: "0" },
    description: "校验身份证格式分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部合法",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_11_F003", "ABC123"],
  },
  {
    archiveLine: 10186,
    title: "有效性校验-格式-手机号",
    tableName: "dwd_voyah_dq_rule_12_main",
    ruleCategory: "有效性校验",
    statisticFunction: "格式-手机号",
    fields: ["owner_phone"],
    expectation: { method: "固定值", operator: ">=", value: "4" },
    description: "校验手机号格式分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "手机号合法数 4",
    failExpectedValue: "手机号合法数 3",
    dirtyEvidence: ["ORD_12_F003", "10086"],
  },
  {
    archiveLine: 10279,
    title: "有效性校验-格式-邮箱",
    tableName: "dwd_voyah_dq_rule_13_main",
    ruleCategory: "有效性校验",
    statisticFunction: "格式-邮箱",
    fields: ["owner_email"],
    expectation: { method: "固定值", operator: "!=", value: "1" },
    description: "校验邮箱格式分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部合法",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_13_F003", "owner-at-example"],
  },
  {
    archiveLine: 10372,
    title: "有效性校验-字符串长度",
    tableName: "dwd_voyah_dq_rule_14_main",
    ruleCategory: "有效性校验",
    statisticFunction: "字符串长度",
    fields: ["vin"],
    expectation: { method: "固定值", operator: "<=", value: "17" },
    description: "校验字符串长度分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部长度 <= 17",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_14_F003", "LTV202601150003AATOOLONG"],
  },
  {
    archiveLine: 10465,
    title: "有效性校验-数据精度",
    tableName: "dwd_voyah_dq_rule_15_main",
    ruleCategory: "有效性校验",
    statisticFunction: "数据精度",
    fields: ["final_price"],
    ruleOptions: [{ label: /关系|逻辑关系/, value: "且" }],
    ruleInputs: [
      { label: "小数点前最大位", value: "18" },
      { label: "小数点后最大位", value: "2" },
    ],
    description: "校验数据精度分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部小数位 <= 2",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_15_F003", "252800.123"],
  },
  {
    archiveLine: 10558,
    title: "有效性校验-枚举值",
    tableName: "dwd_voyah_dq_rule_16_main",
    ruleCategory: "有效性校验",
    statisticFunction: "枚举值",
    fields: ["power_type"],
    ruleInputs: [{ label: "枚举值", value: "EV,PHEV,REEV" }],
    description: "校验枚举值分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部在枚举范围内",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_16_F003", "DIESEL"],
  },
  {
    archiveLine: 10651,
    title: "有效性校验-格式-日期格式-date",
    tableName: "dwd_voyah_dq_rule_17_main",
    ruleCategory: "有效性校验",
    statisticFunction: "格式-日期格式-date",
    fields: ["production_date"],
    ruleInputs: [{ label: "日期格式", value: "YYYY-MM-DD" }],
    expectation: { method: "固定值", operator: "=", value: "0" },
    description: "校验日期格式分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部符合 yyyy-MM-dd",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_17_F003", "2026/01/15"],
  },
  {
    archiveLine: 10744,
    title: "有效性校验-格式-日期格式-date time",
    tableName: "dwd_voyah_dq_rule_18_main",
    ruleCategory: "有效性校验",
    statisticFunction: "格式-日期格式-datetime",
    fields: ["delivery_time"],
    ruleInputs: [{ label: "日期时间格式", value: "YYYY-MM-DD HH:mm:ss" }],
    expectation: { method: "固定值", operator: ">=", value: "4" },
    description: "校验日期时间格式分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "日期时间格式合法数 4",
    failExpectedValue: "日期时间格式合法数 3",
    dirtyEvidence: ["ORD_18_F003", "2026/01/15 10:00"],
  },
  {
    archiveLine: 10837,
    title: "有效性校验-格式校验-自定义正则",
    tableName: "dwd_voyah_dq_rule_19_main",
    ruleCategory: "有效性校验",
    statisticFunction: "格式校验-自定义规则",
    fields: ["vin"],
    ruleOptions: [{ label: /自定义规则|规则名称/, value: "VIN_LTV格式" }],
    expectation: { method: "固定值", operator: "!=", value: "1" },
    description: "校验自定义正则分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部匹配正则",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_19_F003", "BAD202601150003AA"],
  },
  {
    archiveLine: 10930,
    title: "有效性校验-取值范围&枚举范围",
    tableName: "dwd_voyah_dq_rule_20_main",
    ruleCategory: "有效性校验",
    statisticFunction: "取值范围&枚举范围",
    fields: ["final_price"],
    ruleOptions: [{ label: /取值范围和枚举值的关系|关系|逻辑关系/, value: "且" }],
    ruleInputs: [
      { label: "取值范围", value: ">= 0 且 <= 1000000" },
      { label: "枚举值", value: "299000.00,308000.00,317000.00,326000.00" },
    ],
    description: "校验范围枚举分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "异常记录数实际值为 0",
    failExpectedValue: "异常记录数实际值为 1",
    dirtyEvidence: ["ORD_20_F003", "-100.000"],
  },
  {
    archiveLine: 11023,
    title: "有效性校验-格式-json格式校验",
    tableName: "dwd_voyah_dq_rule_21_main",
    ruleCategory: "有效性校验",
    statisticFunction: "格式-json格式校验",
    fields: ["json_payload"],
    ruleOptions: [{ label: /校验key|key/, value: "vehicle-vin" }],
    description: "校验json格式分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "JSON 合法且 key 存在",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_21_F003", "json_payload"],
  },
  {
    archiveLine: 11117,
    title: "唯一性校验-重复数",
    tableName: "dwd_voyah_dq_rule_22_main",
    ruleCategory: "唯一性校验",
    statisticFunction: "重复数",
    fields: ["vin"],
    expectation: { method: "固定值", operator: "!=", value: "1" },
    description: "校验重复数分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "重复"],
  },
  {
    archiveLine: 11210,
    title: "唯一性校验-重复率",
    tableName: "dwd_voyah_dq_rule_23_main",
    ruleCategory: "唯一性校验",
    statisticFunction: "重复率",
    fields: ["vin", "order_id"],
    fieldLogic: "or",
    expectation: { method: "固定值", operator: "<", value: "1%" },
    description: "校验重复率分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0%",
    failExpectedValue: "25%",
    dirtyEvidence: ["LTV202601150003AA", "重复"],
  },
  // archive-title: 验证【唯一性校验-多表唯一性判断】质量规则任务校验正常(唯一+或+单字段)
  {
    archiveLine: 11303,
    title: "唯一性校验-多表唯一性判断(唯一+或)",
    tableName: "dwd_voyah_dq_rule_24_main",
    comparisonTableName: "dwd_voyah_dq_rule_24_ref",
    ruleCategory: "唯一性校验",
    statisticFunction: "多表唯一性判断",
    fields: ["vin"],
    comparisonFields: ["vin"],
    ruleOptions: [
      { label: /校验字段逻辑|字段逻辑/, value: "唯一" },
      { label: /和其他表的校验关系|校验关系|关系/, value: "或" },
    ],
    description: "校验多表唯一或分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "dwd_voyah_dq_rule_24_ref"],
  },
  // archive-title: 验证【唯一性校验-多表唯一性判断】质量规则任务校验正常(允许重复+且+多字段)
  {
    archiveLine: 11441,
    title: "唯一性校验-多表唯一性判断(允许重复+且)",
    tableName: "dwd_voyah_dq_rule_25_main",
    comparisonTableName: "dwd_voyah_dq_rule_25_ref",
    ruleCategory: "唯一性校验",
    statisticFunction: "多表唯一性判断",
    fields: ["vin", "order_id"],
    comparisonFields: ["vin", "order_id"],
    fieldLogic: "and",
    ruleOptions: [
      { label: /校验字段逻辑|字段逻辑/, value: "允许重复" },
      { label: /和其他表的校验关系|校验关系|关系/, value: "且" },
    ],
    description: "校验多表重复且分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["vin", "order_id"],
  },
  {
    archiveLine: 11579,
    title: "统计性校验-异常值检测-IQR离群点数量",
    tableName: "dwd_voyah_dq_rule_26_main",
    ruleCategory: "统计性校验",
    statisticFunction: "异常值检测",
    fields: ["final_price"],
    expectation: { method: "IQR离群点数量", operator: "=", value: "0" },
    description: "校验IQR数量分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_26_F004", "999999.000"],
  },
  {
    archiveLine: 11672,
    title: "统计性校验-异常值检测-IQR离群点占比",
    tableName: "dwd_voyah_dq_rule_27_main",
    ruleCategory: "统计性校验",
    statisticFunction: "异常值检测",
    fields: ["final_price"],
    expectation: { method: "IQR离群点占比", operator: "<", value: "1%" },
    description: "校验IQR占比分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: ">0",
    dirtyEvidence: ["ORD_27_F004", "999999.000"],
  },
  {
    archiveLine: 11765,
    title: "统计性校验-异常值检测-Z-score置信区间",
    tableName: "dwd_voyah_dq_rule_28_main",
    ruleCategory: "统计性校验",
    statisticFunction: "异常值检测",
    fields: ["final_price"],
    expectation: { method: "Z-score置信区间", operator: ">=", value: "-1.96 且 <= 1.96" },
    description: "校验Z-score分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_28_F004", "999999.000"],
  },
  {
    archiveLine: 11858,
    title: "自定义SQL-完整性校验",
    tableName: "dwd_voyah_dq_rule_29_main",
    ruleCategory: "完整性校验",
    sourceRefKind: "CUSTOMSQL",
    statisticFunction: "自定义SQL",
    fields: ["car_model_name"],
    customSqlTemplate: {
      ruleName: "自定义SQL完整性空值数模板",
      ruleType: 1,
      relationRange: 3,
      ruleDesc: "自定义SQL-完整性校验模板",
      customConfiguration: "select count(*) from ${test_table} where car_model_name is null;",
      params: [{ param: "${test_table}", type: 4, paramName: "当前校验表", description: "当前任务主表" }],
    },
    expectation: { method: "固定值", operator: "=", value: "0" },
    description: "校验完整性校验SQL结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_29_F003", "car_model_name"],
  },
  {
    archiveLine: 11952,
    title: "自定义SQL-有效性校验",
    tableName: "dwd_voyah_dq_rule_30_main",
    ruleCategory: "有效性校验",
    sourceRefKind: "CUSTOMSQL",
    statisticFunction: "自定义SQL",
    fields: ["final_price"],
    customSqlTemplate: {
      ruleName: "自定义SQL有效性取值范围模板",
      ruleType: 3,
      relationRange: 3,
      ruleDesc: "自定义SQL-有效性校验模板",
      customConfiguration: "select count(*) from ${test_table} where final_price >= 0;",
      params: [{ param: "${test_table}", type: 4, paramName: "当前校验表", description: "当前任务主表" }],
    },
    expectation: { method: "固定值", operator: ">", value: "3" },
    description: "校验有效性校验SQL结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_30_F003", "-100.000"],
  },
  {
    archiveLine: 12046,
    title: "自定义SQL-唯一性校验",
    tableName: "dwd_voyah_dq_rule_31_main",
    ruleCategory: "唯一性校验",
    sourceRefKind: "CUSTOMSQL",
    statisticFunction: "自定义SQL",
    fields: ["vin"],
    customSqlTemplate: {
      ruleName: "自定义SQL唯一性重复VIN模板",
      ruleType: 2,
      relationRange: 3,
      ruleDesc: "自定义SQL-唯一性校验模板",
      customConfiguration: "select count(distinct vin) from ${test_table};",
      params: [{ param: "${test_table}", type: 4, paramName: "当前校验表", description: "当前任务主表" }],
    },
    expectation: { method: "固定值", operator: ">=", value: "4" },
    description: "校验唯一性校验SQL结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "重复"],
  },
  {
    archiveLine: 12140,
    title: "自定义SQL-统计性校验",
    tableName: "dwd_voyah_dq_rule_32_main",
    ruleCategory: "统计性校验",
    sourceRefKind: "CUSTOMSQL",
    statisticFunction: "自定义SQL",
    fields: ["final_price"],
    customSqlTemplate: {
      ruleName: "自定义SQL统计性异常价格模板",
      ruleType: 6,
      relationRange: 3,
      ruleDesc: "自定义SQL-统计性校验模板",
      customConfiguration: "select count(*) from ${test_table} where final_price > 900000;",
      params: [{ param: "${test_table}", type: 4, paramName: "当前校验表", description: "当前任务主表" }],
    },
    expectation: { method: "固定值", operator: "<", value: "1" },
    description: "校验统计性校验SQL结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_32_F004", "999999.000"],
  },
  {
    archiveLine: 12234,
    title: "自定义SQL-一致性校验",
    tableName: "dwd_voyah_dq_rule_33_main",
    comparisonTableName: "dwd_voyah_dq_rule_33_ref",
    ruleCategory: "一致性校验",
    sourceRefKind: "CUSTOMSQL",
    statisticFunction: "自定义SQL",
    fields: ["car_model_code"],
    customSqlTemplate: {
      ruleName: "自定义SQL一致性主外表差异模板",
      ruleType: 7,
      relationRange: 1,
      ruleDesc: "自定义SQL-一致性校验模板",
      customConfiguration:
        "select count(*) from ${test_table} t left join ${ref_table} r on t.vin = r.vin where t.car_model_code <> r.car_model_code or r.vin is null;",
      params: [
        { param: "${test_table}", type: 4, paramName: "当前校验表", description: "当前任务主表" },
        { param: "${ref_table}", type: 6, paramName: "对比表", description: "对比表表名" },
      ],
    },
    ruleInputs: [{ label: "对比表", value: "dwd_voyah_dq_rule_33_ref" }],
    expectation: { method: "固定值", operator: "<=", value: "0" },
    description: "校验一致性校验SQL结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "car_model_code"],
  },
  {
    archiveLine: 12373,
    title: "自定义SQL-时效性校验",
    tableName: "dwd_voyah_dq_rule_34_main",
    ruleCategory: "时效性校验",
    sourceRefKind: "CUSTOMSQL",
    statisticFunction: "自定义SQL",
    fields: ["delivery_time", "order_time"],
    customSqlTemplate: {
      ruleName: "自定义SQL时效性超时交付模板",
      ruleType: 8,
      relationRange: 3,
      ruleDesc: "自定义SQL-时效性校验模板",
      customConfiguration: "select count(*) from ${test_table} where datediff(to_date(delivery_time), to_date(order_time)) > 1;",
      params: [{ param: "${test_table}", type: 4, paramName: "当前校验表", description: "当前任务主表" }],
    },
    expectation: { method: "固定值", operator: "!=", value: "1" },
    description: "校验时效性校验SQL结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_34_F003", "2026-01-13 08:00:00"],
  },
  {
    archiveLine: 12467,
    title: "自定义SQL-合理性校验",
    tableName: "dwd_voyah_dq_rule_35_main",
    ruleCategory: "合理性校验",
    sourceRefKind: "CUSTOMSQL",
    statisticFunction: "自定义SQL",
    fields: ["final_price", "guide_price", "discount_amount"],
    customSqlTemplate: {
      ruleName: "自定义SQL合理性价格公式模板",
      ruleType: 9,
      relationRange: 3,
      ruleDesc: "自定义SQL-合理性校验模板",
      customConfiguration: "select count(*) from ${test_table} where final_price <> guide_price - discount_amount;",
      params: [{ param: "${test_table}", type: 4, paramName: "当前校验表", description: "当前任务主表" }],
    },
    expectation: { method: "固定值", operator: "=", value: "0" },
    description: "校验合理性校验SQL结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_35_F003", "final_price"],
  },
  {
    archiveLine: 12561,
    title: "一致性校验-多表数据一致性比对",
    tableName: "dwd_voyah_dq_rule_36_main",
    comparisonTableName: "dwd_voyah_dq_rule_36_ref",
    ruleCategory: "一致性校验",
    statisticFunction: "多表数据一致性比对",
    fields: ["car_model_code", "power_type"],
    comparisonFields: ["car_model_code", "power_type"],
    primaryKeys: ["vin"],
    comparisonPrimaryKeys: ["vin"],
    fieldLogic: "and",
    ruleInputs: [{ label: "比对细节设置", value: "数值差异绝对值 <= 0" }],
    description: "校验多表一致分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "car_model_code", "power_type"],
  },
  {
    archiveLine: 12699,
    title: "一致性校验-多表数据一致性比对(多主键+or)",
    tableName: "dwd_voyah_dq_rule_36_multi_main",
    comparisonTableName: "dwd_voyah_dq_rule_36_multi_ref",
    ruleCategory: "一致性校验",
    statisticFunction: "多表数据一致性比对",
    fields: ["car_model_code", "power_type"],
    comparisonFields: ["car_model_code", "power_type"],
    primaryKeys: ["vin", "car_series_code"],
    comparisonPrimaryKeys: ["vin", "car_series_code"],
    fieldLogic: "or",
    ruleInputs: [{ label: "比对细节设置", value: "数值差异绝对值 <= 0" }],
    description: "校验多表一致分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "PASSION", "car_model_code"],
  },
  {
    archiveLine: 12837,
    title: "时效性校验-周期性校验（单字段时间差校验）",
    tableName: "dwd_voyah_dq_rule_37_main",
    ruleCategory: "时效性校验",
    statisticFunction: "周期性校验（单字段时间差校验）",
    fields: ["delivery_time"],
    ruleOptions: [{ label: /排序字段/, value: "event_time" }],
    ruleInputs: [{ label: "时间差", value: "<= 1 天" }],
    description: "校验单字段时间差分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部 <= 1 天",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_37_F003", "2026-01-13 08:00:00"],
  },
  {
    archiveLine: 12930,
    title: "时效性校验-及时性校验（多字段时间差校验）",
    tableName: "dwd_voyah_dq_rule_38_main",
    ruleCategory: "时效性校验",
    statisticFunction: "及时性校验（多字段时间差校验）",
    fields: ["order_time", "payment_time"],
    ruleOptions: [
      { label: /对比字段组|字段组/, value: "order_time,payment_time" },
      { label: /大小关系/, value: "order_time < payment_time" },
    ],
    ruleInputs: [{ label: "时间差", value: "> 0 分钟 且 <= 60 分钟" }],
    description: "校验多字段时间差分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部 > 0 分钟且 <= 60 分钟",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_38_F003", "90"],
  },
  {
    archiveLine: 13023,
    title: "合理性校验-数据变化趋势-单调递增",
    tableName: "dwd_voyah_dq_rule_39_main",
    ruleCategory: "合理性校验",
    statisticFunction: "数据变化趋势",
    fields: ["mileage"],
    ruleOptions: [
      { label: /排序字段/, value: "event_time" },
      { label: /校验方法|趋势|比较方式/, value: "单调递增" },
    ],
    description: "校验单调递增分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "里程按 event_time 单调递增",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_39_F003", "mileage"],
  },
  {
    archiveLine: 13116,
    title: "合理性校验-数据变化趋势-单调递减",
    tableName: "dwd_voyah_dq_rule_40_main",
    ruleCategory: "合理性校验",
    statisticFunction: "数据变化趋势",
    fields: ["battery_loss_rate"],
    ruleOptions: [
      { label: /排序字段/, value: "event_time" },
      { label: /校验方法|趋势|比较方式/, value: "单调递减" },
    ],
    description: "校验单调递减分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "电池衰减率按 event_time 单调递减",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_40_F003", "battery_loss_rate"],
  },
  {
    archiveLine: 13209,
    title: "合理性校验-字段值计算对比-计算结果与字段对比",
    tableName: "dwd_voyah_dq_rule_41_main",
    ruleCategory: "合理性校验",
    statisticFunction: "字段值计算对比",
    fields: ["final_price"],
    ruleInputs: [{ label: "计算逻辑配置", value: "guide_price - discount_amount" }],
    ruleOptions: [
      { label: /对比方法/, value: "计算结果与字段对比" },
      { label: /比较关系/, value: "final_price = 计算逻辑结果" },
    ],
    description: "校验字段计算对比分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_41_F003", "final_price"],
  },
  {
    archiveLine: 13302,
    title: "合理性校验-字段值计算对比-计算结果值判断",
    tableName: "dwd_voyah_dq_rule_42_main",
    ruleCategory: "合理性校验",
    statisticFunction: "字段值计算对比",
    fields: ["final_price"],
    ruleInputs: [
      { label: "计算逻辑配置", value: "guide_price - final_price" },
      { label: "结果值", value: ">= 0" },
    ],
    ruleOptions: [{ label: /对比方法/, value: "计算结果值判断" }],
    description: "校验字段计算判断分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部 >= 0",
    failExpectedValue: "1",
    dirtyEvidence: ["ORD_42_F003", "guide_price-final_price"],
  },
  {
    archiveLine: 13395,
    title: "合理性校验-多表字段值对比-计算结果对比",
    tableName: "dwd_voyah_dq_rule_43_main",
    comparisonTableName: "dwd_voyah_dq_rule_43_ref",
    ruleCategory: "合理性校验",
    statisticFunction: "多表字段值对比",
    fields: ["final_price"],
    primaryKeys: ["vin", "car_series_code"],
    comparisonPrimaryKeys: ["vin", "car_series_code"],
    ruleInputs: [
      { label: "计算逻辑配置", value: "guide_price - discount_amount" },
      { label: "计算逻辑配置2", value: "guide_price - discount_amount" },
    ],
    ruleOptions: [
      { label: /对比方法/, value: "计算结果对比" },
      { label: /比较关系/, value: "计算逻辑1 = 计算逻辑2" },
    ],
    description: "校验多表计算对比分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "0",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "计算结果不一致"],
  },
  {
    archiveLine: 13533,
    title: "合理性校验-多表字段值对比-计算结果值判断",
    tableName: "dwd_voyah_dq_rule_44_main",
    comparisonTableName: "dwd_voyah_dq_rule_44_ref",
    ruleCategory: "合理性校验",
    statisticFunction: "多表字段值对比",
    fields: ["final_price"],
    primaryKeys: ["vin"],
    comparisonPrimaryKeys: ["vin"],
    ruleInputs: [
      { label: "计算逻辑配置", value: "guide_price - final_price" },
      { label: "结果值", value: "<= 1000000" },
    ],
    ruleOptions: [{ label: /对比方法/, value: "计算结果值判断" }],
    description: "校验多表计算判断分区结果",
    passPartition: "stat_date='20260116'",
    failPartition: "stat_date='20260115'",
    passExpectedValue: "全部 <= 1000000",
    failExpectedValue: "1",
    dirtyEvidence: ["LTV202601150003AA", "1000000"],
  },
];

function sourceRefKindFor(scenario: SparkThriftQualityRuleValidationScenario): string {
  if (scenario.sourceRefKind) return scenario.sourceRefKind;
  const { ruleCategory } = scenario;
  if (ruleCategory === "有效性校验") return "VALIDITY";
  if (ruleCategory === "唯一性校验") return "UNIQUENESS";
  if (ruleCategory === "统计性校验") return "STATISTICAL";
  if (ruleCategory === "一致性校验") return "CONSISTENCY";
  if (ruleCategory === "时效性校验") return "TIMELINESS";
  if (ruleCategory === "合理性校验") return "REASONABLENESS";
  return "COMPLETENESS";
}

for (const scenario of scenarios) {
  test(`【P0】数据质量${scenario.title}质量规则任务校验正常`, async ({ page, step }) => {
    await step(`步骤1-8: ${scenario.title} 规则集、规则任务、通过分区与失败分区校验`, async () => {
      ensureSparkThriftScenarioPreconditions(
        scenario,
        `SR-2099-01-DQ-SPARKTHRIFT-${sourceRefKindFor(scenario)}-L${scenario.archiveLine}`,
      );
      await expectSparkThriftQualityRuleValidationContract(
        page,
        `SR-2099-01-DQ-SPARKTHRIFT-${sourceRefKindFor(scenario)}-L${scenario.archiveLine}`,
        scenario,
      );
    });
  });
}

function ensureSparkThriftScenarioPreconditions(
  scenario: SparkThriftQualityRuleValidationScenario,
  sourceRef: string,
): void {
  const tableNames = [scenario.tableName, scenario.comparisonTableName]
    .filter((name): name is string => Boolean(name))
    .sort();
  const groupKey = tableNames.join(",");
  ensureSelectedDtstackPreconditionTables(groupKey, PRECOND_TABLES_FILE, tableNames, sourceRef);
}
