import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { type FeatureRow, runFeaturesLs } from "./features-ls.ts";

export interface FeaturesIndexContext {
  project: string;
  workspaceRoot: string;
  now?: Date;
}

function groupBy<T, K extends string | number>(rows: T[], keyFn: (r: T) => K): Map<K, T[]> {
  const m = new Map<K, T[]>();
  for (const r of rows) {
    const k = keyFn(r);
    const arr = m.get(k) ?? [];
    arr.push(r);
    m.set(k, arr);
  }
  return m;
}

export async function runFeaturesIndex(ctx: FeaturesIndexContext): Promise<void> {
  const rows = await runFeaturesLs({ project: ctx.project, workspaceRoot: ctx.workspaceRoot });
  const now = (ctx.now ?? new Date()).toISOString();

  const lines: string[] = [];
  lines.push("<!-- generated by kata features index; do not edit -->");
  lines.push(`<!-- last_generated: ${now} -->`);
  lines.push(`<!-- feature_count: ${rows.length} -->`);
  lines.push("");
  lines.push("# Features Index");
  lines.push("");

  const byStatus = groupBy(rows, (r) => r.status);
  lines.push("## By Status");
  for (const [status, items] of byStatus) {
    lines.push(`- ${status} (${items.length})`);
  }
  lines.push("");

  const byModule = new Map<string, FeatureRow[]>();
  for (const r of rows) {
    for (const m of r.modules) {
      const arr = byModule.get(m) ?? [];
      arr.push(r);
      byModule.set(m, arr);
    }
  }
  lines.push("## By Module");
  for (const [mod, items] of byModule) {
    lines.push(`- ${mod} (${items.length})`);
  }
  lines.push("");

  lines.push("## All Features");
  lines.push("| ID | Display Name | Modules | Status | Automation | Last Run |");
  lines.push("|---|---|---|---|---|---|");
  for (const r of rows) {
    lines.push(
      `| [${r.id}](${r.id}/) | ${r.displayName} | ${r.modules.join(",")} | ${r.status} | ${r.automationStatus} | ${r.lastRunStatus} |`,
    );
  }

  writeFileSync(
    join(ctx.workspaceRoot, ctx.project, "features", "INDEX.md"),
    `${lines.join("\n")}\n`,
    "utf-8",
  );
}
