import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runFeaturesArchive } from "@shared/cli/features-archive.ts";
import { stringify } from "yaml";

// ─── 辅助：写入最小可用 FeatureMetadata@2 ───
function writeMinimalMeta(dir: string, id: string) {
  writeFileSync(
    join(dir, "metadata.yaml"),
    stringify({
      schema: "FeatureMetadata@2",
      id,
      display_name: id,
      status: "active",
      created_at: "2026-01-01",
      updated_at: "2026-01-01",
      modules: [],
      customers: [],
      versions: [],
      owners: [],
      inputs: [],
      relates_to: [],
      emits: {},
      case_drafting: { status: "not-started", requirement_atoms: [] },
      automation: { status: "not-started", intents: [] },
      files: {},
    }),
  );
}

describe("kata features archive", () => {
  let scratch: string;

  beforeEach(() => {
    scratch = mkdtempSync(join(tmpdir(), "kata-feat-archive-"));
    // 构建两层结构：features/v6.4.10/<feature-a> + <feature-b>
    const vDir = join(scratch, "dataAssets/features/v6.4.10");
    for (const name of ["feat-a", "feat-b"]) {
      const dir = join(vDir, name);
      mkdirSync(dir, { recursive: true });
      writeMinimalMeta(dir, name);
      // 模拟 runs/ 里有未追踪的 run 文件
      mkdirSync(join(dir, "runs/20260101-0000-run-01"), { recursive: true });
      writeFileSync(join(dir, "runs/20260101-0000-run-01/report.json"), "{}");
    }
    // 建 features/INDEX.md 占位，archive 后会被重新生成
    writeFileSync(join(scratch, "dataAssets/features/INDEX.md"), "<!-- placeholder -->\n");
  });

  afterEach(() => rmSync(scratch, { recursive: true, force: true }));

  it("moves version dir to _archived/<version> and regenerates INDEX", async () => {
    const result = await runFeaturesArchive({
      project: "dataAssets",
      workspaceRoot: scratch,
      version: "v6.4.10",
      // inject renameSync so tests don't need git
      move: (from, to) => {
        // use node:fs rename (sync) via dynamic import workaround
        const { renameSync } = require("node:fs");
        renameSync(from, to);
      },
    });

    // from 目录消失
    expect(existsSync(result.from)).toBe(false);
    // to 目录存在
    expect(existsSync(result.to)).toBe(true);
    // 两个 feature 子目录都在归档位置
    expect(existsSync(join(result.to, "feat-a"))).toBe(true);
    expect(existsSync(join(result.to, "feat-b"))).toBe(true);
    // runs 内容保留
    expect(existsSync(join(result.to, "feat-a/runs/20260101-0000-run-01/report.json"))).toBe(true);
    // INDEX.md 被重新生成（不再是 placeholder）
    const { readFileSync } = require("node:fs");
    const idx = readFileSync(join(scratch, "dataAssets/features/INDEX.md"), "utf-8");
    expect(idx).toContain("generated by kata features index");
  });

  it("throws on invalid version string", async () => {
    await expect(
      runFeaturesArchive({
        project: "dataAssets",
        workspaceRoot: scratch,
        version: "invalid",
      }),
    ).rejects.toThrow(/invalid version/i);
  });

  it("throws when version dir does not exist", async () => {
    await expect(
      runFeaturesArchive({
        project: "dataAssets",
        workspaceRoot: scratch,
        version: "v9.9.9",
      }),
    ).rejects.toThrow(/not found/i);
  });

  it("throws when version is already archived", async () => {
    const archivedDir = join(scratch, "dataAssets/features/_archived/v6.4.10");
    mkdirSync(archivedDir, { recursive: true });
    await expect(
      runFeaturesArchive({
        project: "dataAssets",
        workspaceRoot: scratch,
        version: "v6.4.10",
      }),
    ).rejects.toThrow(/already archived/i);
  });
});
