import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runFeaturesIndex } from "@shared/cli/features-index.ts";
import { stringify } from "yaml";

// 统一使用 FeatureMetadata@2，features 落版本层目录
function seed(
  scratch: string,
  group: string,
  dirName: string,
  opts: { modules?: string[]; status?: string; displayName?: string },
) {
  const dir = join(scratch, "dataAssets/features", group, dirName);
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    join(dir, "metadata.yaml"),
    stringify({
      schema: "FeatureMetadata@2",
      id: dirName,
      display_name: opts.displayName ?? dirName,
      status: opts.status ?? "active",
      created_at: "2026-04-01",
      updated_at: "2026-04-01",
      modules: opts.modules ?? [],
      customers: [],
      versions: [],
      owners: [],
      inputs: [],
      relates_to: [],
      emits: { cases_xmind: true, archive: true, playwright_tests: true },
      case_drafting: { status: "not-started" },
      automation: { status: "not-started", intents: [], last_run_status: "not-run" },
      files: {},
    }),
  );
}

describe("kata features index", () => {
  let scratch: string;
  beforeEach(() => {
    scratch = mkdtempSync(join(tmpdir(), "kata-feat-idx-"));
    seed(scratch, "v6.4.10", "2026-04-dq-a", {
      modules: ["dq"],
      status: "active",
      displayName: "数据质量A",
    });
    seed(scratch, "v6.4.10", "2026-04-sec-b", { modules: ["security"], status: "active" });
    seed(scratch, "v6.4.10", "2026-03-old", { modules: ["dq"], status: "archived" });
  });
  afterEach(() => rmSync(scratch, { recursive: true, force: true }));

  it("writes INDEX.md with feature_count = 3", async () => {
    await runFeaturesIndex({
      project: "dataAssets",
      workspaceRoot: scratch,
      now: new Date("2026-05-14T10:00:00Z"),
    });
    const content = readFileSync(join(scratch, "dataAssets/features/INDEX.md"), "utf-8");
    expect(content).toContain("<!-- feature_count: 3 -->");
    expect(content).toContain("数据质量A");
    expect(content).toContain("## By Module");
    expect(content).toContain("dq");
    expect(content).toContain("security");
  });

  it("includes a 'do not edit' header", async () => {
    await runFeaturesIndex({ project: "dataAssets", workspaceRoot: scratch });
    const content = readFileSync(join(scratch, "dataAssets/features/INDEX.md"), "utf-8");
    expect(content).toContain("<!-- generated by kata features index; do not edit -->");
  });

  it("groups features by version in the index", async () => {
    await runFeaturesIndex({ project: "dataAssets", workspaceRoot: scratch });
    const content = readFileSync(join(scratch, "dataAssets/features/INDEX.md"), "utf-8");
    expect(content).toContain("## v6.4.10");
  });
});
