import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { gitMove, runFeaturesArchive } from "@shared/cli/features-archive.ts";
import { stringify } from "yaml";

// ─── 辅助：写入最小可用 FeatureMetadata@2 ───
function writeMinimalMeta(dir: string, id: string) {
  writeFileSync(
    join(dir, "metadata.yaml"),
    stringify({
      schema: "FeatureMetadata@2",
      id,
      display_name: id,
      status: "active",
      created_at: "2026-01-01",
      updated_at: "2026-01-01",
      modules: [],
      customers: [],
      versions: [],
      owners: [],
      inputs: [],
      relates_to: [],
      emits: {},
      case_drafting: { status: "not-started", requirement_atoms: [] },
      automation: { status: "not-started", intents: [] },
      files: {},
    }),
  );
}

describe("kata features archive", () => {
  let scratch: string;

  beforeEach(() => {
    scratch = mkdtempSync(join(tmpdir(), "kata-feat-archive-"));
    // 构建两层结构：features/v6.4.10/<feature-a> + <feature-b>
    const vDir = join(scratch, "dataAssets/features/v6.4.10");
    for (const name of ["feat-a", "feat-b"]) {
      const dir = join(vDir, name);
      mkdirSync(dir, { recursive: true });
      writeMinimalMeta(dir, name);
      // 模拟 runs/ 里有未追踪的 run 文件
      mkdirSync(join(dir, "runs/20260101-0000-run-01"), { recursive: true });
      writeFileSync(join(dir, "runs/20260101-0000-run-01/report.json"), "{}");
    }
    // 建 features/INDEX.md 占位，archive 后会被重新生成
    writeFileSync(join(scratch, "dataAssets/features/INDEX.md"), "<!-- placeholder -->\n");
  });

  afterEach(() => rmSync(scratch, { recursive: true, force: true }));

  it("moves version dir to _archived/<version> and regenerates INDEX", async () => {
    const result = await runFeaturesArchive({
      project: "dataAssets",
      workspaceRoot: scratch,
      version: "v6.4.10",
      // inject renameSync so tests don't need git
      move: (from, to) => {
        // use node:fs rename (sync) via dynamic import workaround
        const { renameSync } = require("node:fs");
        renameSync(from, to);
      },
    });

    // from 目录消失
    expect(existsSync(result.from)).toBe(false);
    // to 目录存在
    expect(existsSync(result.to)).toBe(true);
    // 两个 feature 子目录都在归档位置
    expect(existsSync(join(result.to, "feat-a"))).toBe(true);
    expect(existsSync(join(result.to, "feat-b"))).toBe(true);
    // runs 内容保留
    expect(existsSync(join(result.to, "feat-a/runs/20260101-0000-run-01/report.json"))).toBe(true);
    // INDEX.md 被重新生成（不再是 placeholder）
    const { readFileSync } = require("node:fs");
    const idx = readFileSync(join(scratch, "dataAssets/features/INDEX.md"), "utf-8");
    expect(idx).toContain("generated by kata features index");
  });

  it("throws on invalid version string", async () => {
    await expect(
      runFeaturesArchive({
        project: "dataAssets",
        workspaceRoot: scratch,
        version: "invalid",
      }),
    ).rejects.toThrow(/invalid version/i);
  });

  it("throws when version dir does not exist", async () => {
    await expect(
      runFeaturesArchive({
        project: "dataAssets",
        workspaceRoot: scratch,
        version: "v9.9.9",
      }),
    ).rejects.toThrow(/not found/i);
  });

  it("throws when version is already archived", async () => {
    const archivedDir = join(scratch, "dataAssets/features/_archived/v6.4.10");
    mkdirSync(archivedDir, { recursive: true });
    await expect(
      runFeaturesArchive({
        project: "dataAssets",
        workspaceRoot: scratch,
        version: "v6.4.10",
      }),
    ).rejects.toThrow(/already archived/i);
  });
});

// ─── git 一致性回归：归档在真实 git repo 内不得留 husk / 重复 / RD 孤儿 ───
// 该用例钉死「archive 用 gitMove 整目录搬移是安全的」这一保证（与 migrate 不同）。
// migrate 因逐路径搬 ignored 文件 + 预删 manifest，整目录 git mv 失败回退 renameSync，
// 留下 flat husk + 重复副本 + RD 孤儿。archive 只做一次整目录 move、不预删、不区内
// reorg，所以不继承那个根因：git mv 整目录是目录级 rename，会把 ignored runs/ 一并
// 物理搬走，旧位置不留壳、index 一致（status 显示干净的 R）。安全性论证见
// features-archive.ts 的 gitMove 注释。
describe("git-consistent archive (husk regression)", () => {
  let gitRoot: string;
  let gitFeaturesDir: string;

  beforeEach(() => {
    gitRoot = mkdtempSync(join(tmpdir(), "kata-archive-git-"));
    execFileSync("git", ["init"], { cwd: gitRoot, stdio: "pipe" });
    execFileSync("git", ["config", "user.email", "test@test.com"], { cwd: gitRoot, stdio: "pipe" });
    execFileSync("git", ["config", "user.name", "Test"], { cwd: gitRoot, stdio: "pipe" });
    gitFeaturesDir = join(gitRoot, "dataAssets", "features");
    mkdirSync(gitFeaturesDir, { recursive: true });
    writeFileSync(join(gitFeaturesDir, "INDEX.md"), "<!-- placeholder -->\n");
    // runs/ 是 ignored runtime 目录（与真实项目一致）。git mv 搬不动单个 ignored 文件，
    // 只有整目录级 rename 才能把它们带到 _archived 层。
    writeFileSync(join(gitRoot, ".gitignore"), "**/runs/\n");
  });

  afterEach(() => rmSync(gitRoot, { recursive: true, force: true }));

  // 在版本目录下建一个含 tracked 用例产物 + ignored runs/ 的 feature
  function buildFeature(versionDir: string, name: string): string {
    const dir = join(versionDir, name);
    mkdirSync(join(dir, "cases"), { recursive: true });
    writeFileSync(
      join(dir, "metadata.yaml"),
      stringify({ schema: "FeatureMetadata@2", id: name, status: "active" }),
    );
    writeFileSync(
      join(dir, "cases", "archive.md"),
      `# ${name} cases\n\ndistinct payload so rename detection has a real signal\n`,
    );
    // ignored 的 runtime run 产物
    mkdirSync(join(dir, "runs", "20260101-0000-run-01"), { recursive: true });
    writeFileSync(join(dir, "runs", "20260101-0000-run-01", "report.json"), '{"ok":true}\n');
    return dir;
  }

  it("git mv path: carries ignored runs/, leaves no husk, keeps index consistent", async () => {
    const featAdir = buildFeature(join(gitFeaturesDir, "v6.4.10"), "feat-a");
    const featBdir = buildFeature(join(gitFeaturesDir, "v6.4.10"), "feat-b");
    execFileSync("git", ["add", "-A"], { cwd: gitRoot, stdio: "pipe" });
    execFileSync("git", ["commit", "-m", "init"], { cwd: gitRoot, stdio: "pipe" });

    // 以生产真实路径执行：注入真实 gitMove（git mv 优先、renameSync 兜底）
    const result = await runFeaturesArchive({
      project: "dataAssets",
      workspaceRoot: gitRoot,
      version: "v6.4.10",
      move: gitMove,
    });

    const archivedDir = join(gitFeaturesDir, "_archived", "v6.4.10");

    // ① 无 husk：旧版本目录整体消失，不留任何残壳
    expect(existsSync(result.from)).toBe(false);
    expect(existsSync(featAdir)).toBe(false);
    expect(existsSync(featBdir)).toBe(false);

    // ② tracked 用例产物到归档位置
    expect(existsSync(join(archivedDir, "feat-a", "cases", "archive.md"))).toBe(true);
    expect(existsSync(join(archivedDir, "feat-b", "cases", "archive.md"))).toBe(true);

    // ③ ignored runs/ 也被整目录搬过去（git mv 单独搬不动，靠目录级 rename）
    expect(
      existsSync(join(archivedDir, "feat-a", "runs", "20260101-0000-run-01", "report.json")),
    ).toBe(true);
    expect(
      existsSync(join(archivedDir, "feat-b", "runs", "20260101-0000-run-01", "report.json")),
    ).toBe(true);

    // ④ git index 一致：无 untracked(??)、无 RD 孤儿（INDEX.md 被重生成只算普通 modify）
    const status = execFileSync("git", ["status", "--porcelain"], {
      cwd: gitRoot,
      encoding: "utf-8",
    });
    for (const line of status.split("\n").filter(Boolean)) {
      const xy = line.slice(0, 2);
      expect(xy).not.toBe("??"); // 不得有未暂存的重复副本
      expect(xy).not.toBe("RD"); // 不得有「index 指向已不存在工作树路径」的孤儿
    }

    // ⑤ tracked 索引里旧版本路径彻底消失，只存在于归档层
    const tracked = execFileSync("git", ["ls-files"], { cwd: gitRoot, encoding: "utf-8" });
    const oldRel = "dataAssets/features/v6.4.10/";
    const archivedRel = "dataAssets/features/_archived/v6.4.10/";
    for (const f of tracked.split("\n").filter(Boolean)) {
      expect(f.startsWith(oldRel)).toBe(false);
    }
    expect(tracked).toContain(`${archivedRel}feat-a/cases/archive.md`);

    // ⑥ 暂存 INDEX 重生成后提交，工作树彻底干净
    execFileSync("git", ["add", "-A"], { cwd: gitRoot, stdio: "pipe" });
    execFileSync("git", ["commit", "-m", "archive"], { cwd: gitRoot, stdio: "pipe" });
    const afterCommit = execFileSync("git", ["status", "--porcelain"], {
      cwd: gitRoot,
      encoding: "utf-8",
    });
    expect(afterCommit.trim()).toBe("");

    // ⑦ 内容未变的用例产物移动后历史可追溯（git 在提交时做 rename 检测）
    const log = execFileSync(
      "git",
      ["log", "--follow", "--format=%s", "--", `${archivedRel}feat-a/cases/archive.md`],
      { cwd: gitRoot, encoding: "utf-8" },
    );
    expect(log).toContain("init");
  });

  it("renameSync fallback path: version dir with only ignored files stays husk-free", async () => {
    // 版本目录只有 ignored runs/、没有任何 tracked 文件 → git mv 报「源目录为空」失败，
    // 回退 renameSync。renameSync 同样是整目录 rename，照样把 ignored 搬走、不留 husk。
    const versionDir = join(gitFeaturesDir, "v6.4.10");
    mkdirSync(join(versionDir, "feat-a", "runs", "run-01"), { recursive: true });
    writeFileSync(join(versionDir, "feat-a", "runs", "run-01", "report.json"), "{}\n");
    execFileSync("git", ["add", "-A"], { cwd: gitRoot, stdio: "pipe" });
    execFileSync("git", ["commit", "-m", "init"], { cwd: gitRoot, stdio: "pipe" });

    // 前置确认：版本目录里确实没有 tracked 文件（否则就不是 fallback 场景）
    const trackedBefore = execFileSync("git", ["ls-files", "dataAssets/features/v6.4.10"], {
      cwd: gitRoot,
      encoding: "utf-8",
    });
    expect(trackedBefore.trim()).toBe("");

    const result = await runFeaturesArchive({
      project: "dataAssets",
      workspaceRoot: gitRoot,
      version: "v6.4.10",
      move: gitMove,
    });

    const archivedDir = join(gitFeaturesDir, "_archived", "v6.4.10");
    // 无 husk：旧目录消失
    expect(existsSync(result.from)).toBe(false);
    // ignored 文件被搬到归档层
    expect(existsSync(join(archivedDir, "feat-a", "runs", "run-01", "report.json"))).toBe(true);
    expect(
      readFileSync(join(archivedDir, "feat-a", "runs", "run-01", "report.json"), "utf-8"),
    ).toBe("{}\n");

    // index 一致：无 ??/RD（被搬的都是 ignored，git 不追踪，status 仅含 INDEX.md 的 modify）
    const status = execFileSync("git", ["status", "--porcelain"], {
      cwd: gitRoot,
      encoding: "utf-8",
    });
    for (const line of status.split("\n").filter(Boolean)) {
      const xy = line.slice(0, 2);
      expect(xy).not.toBe("??");
      expect(xy).not.toBe("RD");
    }
  });
});
