import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runHandoffRender } from "@skills/playwright-automation/scripts/handoff-render.ts";

describe("kata handoff render", () => {
  let scratch: string;
  beforeEach(() => {
    scratch = mkdtempSync(join(tmpdir(), "kata-handoff-"));
    const runDir = join(
      scratch,
      "dataAssets/features/v6.4/【v6.4】feature-x/runs/20260510-1430-run-01",
    );
    mkdirSync(runDir, { recursive: true });
    writeFileSync(
      join(runDir, "handoff.json"),
      JSON.stringify({
        schema: "PlaywrightAutomationHandoff@2",
        feature_id: "2026-04-x",
        run_id: "20260510-1430-run-01",
        status: "passed",
        intent_id: "SR-INTENT-X",
        source_refs: {
          intent: "SR-INTENT-X",
          env: "SR-ENV-PREFLIGHT-X",
          probe: "SR-UI-PROBE-X",
          self_run: "SR-SELF-RUN-X",
        },
        run_command: "npx playwright test ...",
        acceptance_command:
          "kata env run ltqc-local -- npx playwright test 'features/2026-04-x/tests/runners/full.spec.ts' --project=chromium --headed --reporter=line",
        run_exit_code: 0,
        results: {
          total: 5,
          passed: 5,
          failed: 0,
          skipped: 0,
          report_paths: { playwright_json: "x", allure: "y", stdout: "z" },
        },
        quality_gates: [{ name: "no_weak_assertions", status: "passed" }],
        platform_records: [
          {
            case_id: "P0-1",
            record_type: "standard-definition",
            record_name: "qa_auto_standard_20260702",
            status: "已上线",
            evidence_path: "runs/20260510-1430-run-01/allure-results/record.png",
          },
        ],
        unresolved_blockers: [],
        next_actions: [],
        excluded_cases: [
          {
            case_id: "P0-3",
            reason_category: "data_prep",
            detail: "需后台任务完成",
          },
        ],
      }),
    );
  });
  afterEach(() => rmSync(scratch, { recursive: true, force: true }));

  it("renders excluded cases section", async () => {
    await runHandoffRender({
      project: "dataAssets",
      featureId: "【v6.4】feature-x",
      runId: "20260510-1430-run-01",
      workspaceRoot: scratch,
    });
    const md = readFileSync(
      join(
        scratch,
        "dataAssets/features/v6.4/【v6.4】feature-x/runs/20260510-1430-run-01/handoff.md",
      ),
      "utf-8",
    );
    expect(md).toContain("## Excluded Cases");
    expect(md).toContain("[data_prep] case=P0-3");
    expect(md).toContain("需后台任务完成");
  });

  it("renders handoff.md with generated header and key fields", async () => {
    await runHandoffRender({
      project: "dataAssets",
      featureId: "【v6.4】feature-x",
      runId: "20260510-1430-run-01",
      workspaceRoot: scratch,
    });
    const md = readFileSync(
      join(
        scratch,
        "dataAssets/features/v6.4/【v6.4】feature-x/runs/20260510-1430-run-01/handoff.md",
      ),
      "utf-8",
    );
    expect(md).toContain("<!-- generated by kata handoff render; do not edit -->");
    expect(md).toContain("<!-- schema: PlaywrightAutomationHandoff@2 -->");
    expect(md).toContain("status: passed");
    expect(md).toContain("SR-INTENT-X");
    expect(md).toContain("5/5 passed");
    expect(md).toContain("## Platform Records");
    expect(md).toContain("qa_auto_standard_20260702");
    expect(md).toContain("## Human Acceptance Command");
    expect(md).toContain("--headed --reporter=line");
    expect(md).toContain("features/2026-04-x/tests/runners/full.spec.ts");
  });
});
