// Generated by kata automation coverage. Do not add business logic here.
import { loadPlaywrightAutomationConfig } from "../../../../../../../../runtime/automation/config/playwright";
import { orderAutomationCases } from "../../../../../../../../runtime/automation/runner/case-order";

const generatedCases: ReadonlyArray<{ readonly caseId: string; readonly module: string }> = [
  { caseId: "C0001", module: "../cases/c0001-asset-platform-first-entry-guide.spec.ts" },
  { caseId: "C0002", module: "../cases/c0002-connected-data-source-statistics.spec.ts" },
  { caseId: "C0003", module: "../cases/c0003-data-map-distribution.spec.ts" },
  { caseId: "C0004", module: "../cases/c0004-data-catalog-distribution.spec.ts" },
  { caseId: "C0005", module: "../cases/c0005-data-value-ranking.spec.ts" },
  { caseId: "C0006", module: "../cases/c0006-storage-resource-statistics.spec.ts" },
  { caseId: "C0007", module: "../cases/c0007-metadata-change-trend.spec.ts" },
  { caseId: "C0008", module: "../cases/c0008-asset-query-trend.spec.ts" },
  { caseId: "C0009", module: "../cases/c0009-data-map-level-one-ui.spec.ts" },
  { caseId: "C0010", module: "../cases/c0010-data-map-search-interactions.spec.ts" },
  { caseId: "C0011", module: "../cases/c0011-data-table-search-results.spec.ts" },
  { caseId: "C0012", module: "../cases/c0012-offline-task-search-results.spec.ts" },
  { caseId: "C0013", module: "../cases/c0013-realtime-task-search-results.spec.ts" },
  { caseId: "C0014", module: "../cases/c0014-api-search-results.spec.ts" },
  { caseId: "C0015", module: "../cases/c0015-smart-tag-search-results.spec.ts" },
  { caseId: "C0016", module: "../cases/c0016-metric-search-results.spec.ts" },
  { caseId: "C0017", module: "../cases/c0017-recent-query.spec.ts" },
  { caseId: "C0018", module: "../cases/c0018-asset-type-icons-and-counts.spec.ts" },
  { caseId: "C0019", module: "../cases/c0019-data-table-count.spec.ts" },
  { caseId: "C0020", module: "../cases/c0020-offline-task-count.spec.ts" },
  { caseId: "C0021", module: "../cases/c0021-realtime-task-count.spec.ts" },
  { caseId: "C0022", module: "../cases/c0022-api-count.spec.ts" },
  { caseId: "C0023", module: "../cases/c0023-smart-tag-count.spec.ts" },
  { caseId: "C0024", module: "../cases/c0024-metric-count.spec.ts" },
  { caseId: "C0025", module: "../cases/c0025-asset-page-interactions.spec.ts" },
  { caseId: "C0026", module: "../cases/c0026-data-source-type-count-order.spec.ts" },
  { caseId: "C0027", module: "../cases/c0027-table-source-count.spec.ts" },
  { caseId: "C0028", module: "../cases/c0028-asset-page-secondary-interactions.spec.ts" },
  { caseId: "C0029", module: "../cases/c0029-tag-empty-state-and-usage.spec.ts" },
  { caseId: "C0030", module: "../cases/c0030-table-tags.spec.ts" },
  { caseId: "C0031", module: "../cases/c0031-field-tags.spec.ts" },
  { caseId: "C0032", module: "../cases/c0032-view-tags.spec.ts" },
  { caseId: "C0033", module: "../cases/c0033-history-query-color-coding.spec.ts" },
  { caseId: "C0034", module: "../cases/c0034-query-keyword-size.spec.ts" },
  { caseId: "C0035", module: "../cases/c0035-query-keyword-count.spec.ts" },
  { caseId: "C0036", module: "../cases/c0036-query-keyword-navigation.spec.ts" },
  { caseId: "C0037", module: "../cases/c0037-data-map-level-two-table-ui.spec.ts" },
  { caseId: "C0038", module: "../cases/c0038-combined-filter-search.spec.ts" },
  { caseId: "C0039", module: "../cases/c0039-catalog-actions-and-filters.spec.ts" },
  { caseId: "C0040", module: "../cases/c0040-catalog-add.spec.ts" },
  { caseId: "C0041", module: "../cases/c0041-catalog-search.spec.ts" },
  { caseId: "C0042", module: "../cases/c0042-catalog-edit.spec.ts" },
];

const orderedCases = orderAutomationCases(
  generatedCases,
  loadPlaywrightAutomationConfig().sortCases,
);

for (const generatedCase of orderedCases) {
  await import(generatedCase.module);
}
