import { describe, expect, test } from "bun:test";
import { renderBugReport, renderConflictReport } from "@shared/lib/bug-report-render.ts";
import { validateBugReport, validateConflictReport } from "@shared/lib/bug-report-validate.ts";
import bugFixture from "./bug-report.fixture.json";
import conflictFixture from "./conflict-report.fixture.json";

describe("renderBugReport", () => {
  // zentao 是禅道富文本兼容片段：裸 <table>，无 DOCTYPE；zentao 现为默认且唯一 variant
  test("renders zentao as a ZenTao rich-text fragment (no DOCTYPE) with no unresolved handlebars", () => {
    const html = renderBugReport(validateBugReport(bugFixture), "zentao");
    expect(html).toContain("<table");
    expect(html).not.toContain("<!DOCTYPE html>");
    expect(html).toContain(bugFixture.title);
    expect(html).not.toContain("{{");
  });

  // 不传 variant 时默认走 zentao
  test("defaults to zentao variant when none is given", () => {
    const html = renderBugReport(validateBugReport(bugFixture));
    expect(html).toContain("<table");
    expect(html).not.toContain("<!DOCTYPE html>");
    expect(html).not.toContain("{{");
  });

  test("zentao variant: new layout, drops framework/java_version/source_ref, renders all suggestions, analysis/evidence, diff", () => {
    const report = validateBugReport({
      title: "示例 NPE",
      summary: "字段为空触发 NPE",
      problem_type: "代码问题",
      severity: "major",
      confidence: "high",
      confidence_reason: "不应展示",
      environment: {
        deploy_env: "http://shuzhan63-test.k8s.dtstack.cn/",
        framework: "Spring",
        java_version: "1.8",
        source_ref: "abc123",
        tenant: "DT_demo",
        account: "admin@dtstack.com / pw",
        datasource: "Hive(default)",
      },
      error_info: {
        curl: "curl 'http://x' -H 'Cookie: a=b'",
        log: "java.lang.NullPointerException",
      },
      reproduction_steps: ["进入页面", "运行任务", "查看日志"],
      expected: "运行成功",
      actual: "运行失败 NPE",
      stack_trace: {
        exception_type: "java.lang.NullPointerException",
        call_chain: [{ class: "X", method: "run", line: 1, is_root: true }],
      },
      code_location: {
        file: "X.java",
        line: 142,
        analysis: "字段 ctx 未判空导致 NPE",
        evidence: "X.run 第 142 行直接解引用 ctx",
        snippet_lines: [
          { no: 141, text: "ctx", error: false },
          { no: 142, text: "npe here", error: true },
        ],
      },
      fix_suggestions: [
        {
          title: "加判空",
          location: "X.java:142",
          action: "在解引用前判空",
          reason: "避免 NPE",
          diff_lines: [
            { sign: " ", text: "for(...)" },
            { sign: "-", text: "old" },
            { sign: "+", text: "new" },
          ],
        },
        { title: "补单测（应渲染第二条）" },
      ],
    });
    const html = renderBugReport(report, "zentao");
    expect(html).toContain("环境信息");
    expect(html).toContain("报错信息");
    expect(html).toContain("CURL信息");
    expect(html).toContain("日志信息");
    expect(html).toContain("复现步骤");
    expect(html).toContain("预期结果");
    expect(html).toContain("实际结果");
    expect(html).toContain("根因分析");
    expect(html).toContain("DT_demo");
    expect(html).toContain("admin@dtstack.com");
    expect(html).toContain("Hive(default)");
    expect(html).not.toContain("JDK 版本");
    expect(html).not.toContain("框架");
    expect(html).not.toContain("源码参考");
    expect(html).not.toContain("不应展示");
    // 全部修复建议都渲染（含第二条）
    expect(html).toContain("加判空");
    expect(html).toContain("补单测（应渲染第二条）");
    // 修复建议补齐 location/action/reason
    expect(html).toContain("X.java:142");
    expect(html).toContain("在解引用前判空");
    expect(html).toContain("避免 NPE");
    // 根因分析渲染 analysis/evidence 文本
    expect(html).toContain("字段 ctx 未判空导致 NPE");
    expect(html).toContain("X.run 第 142 行直接解引用 ctx");
    expect(html).toContain("background:#14321f");
    expect(html).toContain("background:#3f1d1d");
    expect(html).toContain("background:#7f1d1d");
    expect(html).not.toContain("Generated by kata");
    expect(html).not.toContain("{{");
    expect(html).not.toContain("undefined");
  });
});

describe("renderConflictReport", () => {
  test("renders conflict report with no unresolved handlebars", () => {
    const html = renderConflictReport(validateConflictReport(conflictFixture));
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain(conflictFixture.title);
    expect(html).toContain(conflictFixture.manual_decision_list[0].description);
    expect(html).not.toContain("{{");
  });
});
