import { describe, expect, test } from "bun:test";
import { renderBugReport, renderConflictReport } from "@shared/lib/bug-report-render.ts";
import { validateBugReport, validateConflictReport } from "@shared/lib/bug-report-validate.ts";
import bugFixture from "./bug-report.fixture.json";
import conflictFixture from "./conflict-report.fixture.json";

describe("renderBugReport", () => {
  // simple / full 是完整 HTML 文档
  for (const variant of ["simple", "full"] as const) {
    test(`renders ${variant} as a full HTML document with no unresolved handlebars`, () => {
      const html = renderBugReport(validateBugReport(bugFixture), variant);
      expect(html).toContain("<!DOCTYPE html>");
      expect(html).toContain(bugFixture.title);
      expect(html).not.toContain("{{");
    });
  }

  // zentao 是禅道富文本兼容片段：裸 <table>，无 DOCTYPE
  test("renders zentao as a ZenTao rich-text fragment (no DOCTYPE) with no unresolved handlebars", () => {
    const html = renderBugReport(validateBugReport(bugFixture), "zentao");
    expect(html).toContain("<table");
    expect(html).not.toContain("<!DOCTYPE html>");
    expect(html).toContain(bugFixture.title);
    expect(html).not.toContain("{{");
  });

  // severityClass 由 severity 计算注入（minor -> low）；simple 模版真实把它渲染进 badge class
  test("injects computed severityClass (minor -> low) into the rendered badge", () => {
    const html = renderBugReport(validateBugReport({ ...bugFixture, severity: "minor" }), "simple");
    expect(html).toContain("badge severity-low");
    expect(html).not.toContain("{{");
  });

  test("zentao variant: new layout, drops framework/java_version/source_ref, single suggestion, diff", () => {
    const report = validateBugReport({
      title: "示例 NPE",
      summary: "字段为空触发 NPE",
      problem_type: "代码问题",
      severity: "major",
      confidence: "high",
      confidence_reason: "不应展示",
      environment: {
        deploy_env: "http://shuzhan63-test.k8s.dtstack.cn/",
        framework: "Spring",
        java_version: "1.8",
        source_ref: "abc123",
        tenant: "DT_demo",
        account: "admin@dtstack.com / pw",
        datasource: "Hive(default)",
      },
      error_info: {
        curl: "curl 'http://x' -H 'Cookie: a=b'",
        log: "java.lang.NullPointerException",
      },
      reproduction_steps: ["进入页面", "运行任务", "查看日志"],
      expected: "运行成功",
      actual: "运行失败 NPE",
      stack_trace: {
        exception_type: "java.lang.NullPointerException",
        call_chain: [{ class: "X", method: "run", line: 1, is_root: true }],
      },
      code_location: {
        file: "X.java",
        snippet_lines: [
          { no: 141, text: "ctx", error: false },
          { no: 142, text: "npe here", error: true },
        ],
      },
      fix_suggestions: [
        {
          title: "加判空",
          diff_lines: [
            { sign: " ", text: "for(...)" },
            { sign: "-", text: "old" },
            { sign: "+", text: "new" },
          ],
        },
        { title: "补单测（不应出现）" },
      ],
    });
    const html = renderBugReport(report, "zentao");
    expect(html).toContain("环境信息");
    expect(html).toContain("报错信息");
    expect(html).toContain("CURL信息");
    expect(html).toContain("日志信息");
    expect(html).toContain("复现步骤");
    expect(html).toContain("预期结果");
    expect(html).toContain("实际结果");
    expect(html).toContain("根因分析");
    expect(html).toContain("DT_demo");
    expect(html).toContain("admin@dtstack.com");
    expect(html).toContain("Hive(default)");
    expect(html).not.toContain("JDK 版本");
    expect(html).not.toContain("框架");
    expect(html).not.toContain("源码参考");
    expect(html).not.toContain("不应展示");
    expect(html).not.toContain("补单测（不应出现）");
    expect(html).toContain("background:#14321f");
    expect(html).toContain("background:#3f1d1d");
    expect(html).toContain("background:#7f1d1d");
    expect(html).not.toContain("Generated by kata");
    expect(html).not.toContain("{{");
    expect(html).not.toContain("undefined");
  });
});

describe("renderConflictReport", () => {
  test("renders conflict report with no unresolved handlebars", () => {
    const html = renderConflictReport(validateConflictReport(conflictFixture));
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain(conflictFixture.title);
    expect(html).toContain(conflictFixture.manual_decision_list[0].description);
    expect(html).not.toContain("{{");
  });
});
