import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface ScaffoldResult {
  created: string[];
  skipped: string[];
  overwritten: string[];
}

const SUBDIRS = ["cases", "runners", "pages", "flows", "assertions", "fixtures", "sql"];

const SMOKE_SPEC = `// smoke test - aggregate P0 case imports
// Generated by kata automation scaffold. Edit the import list manually.
`;

const FULL_SPEC = `// full regression - aggregate all feature case imports
// Generated by kata automation scaffold. Edit the import list manually.
`;

export function scaffoldAutomation(
  featureDir: string,
  opts: { force?: boolean } = {},
): ScaffoldResult {
  const result: ScaffoldResult = { created: [], skipped: [], overwritten: [] };
  const testsDir = join(featureDir, "automation", "tests");

  for (const sub of SUBDIRS) {
    const dir = join(testsDir, sub);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
      result.created.push(dir);
    }
  }

  const smoke = join(testsDir, "runners", "smoke.spec.ts");
  if (!existsSync(smoke)) {
    writeFileSync(smoke, SMOKE_SPEC);
    result.created.push(smoke);
  } else if (opts.force) {
    writeFileSync(smoke, SMOKE_SPEC);
    result.overwritten.push(smoke);
  } else {
    result.skipped.push(smoke);
  }

  const full = join(testsDir, "runners", "full.spec.ts");
  if (!existsSync(full)) {
    writeFileSync(full, FULL_SPEC);
    result.created.push(full);
  } else if (opts.force) {
    writeFileSync(full, FULL_SPEC);
    result.overwritten.push(full);
  } else {
    result.skipped.push(full);
  }

  return result;
}
