import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface ScaffoldResult {
  created: string[];
  skipped: string[];
  overwritten: string[];
}

const SUBDIRS = ["cases", "runners", "pages", "flows", "assertions", "fixtures", "sql"];

const SMOKE_SPEC = `// smoke test - aggregate P0 case imports
// Generated by kata automation scaffold. Edit the import list manually.
`;

const FULL_SPEC = `// full regression - aggregate all feature case imports
// Generated by kata automation scaffold. Edit the import list manually.
`;

const CASES_README = `# 用例索引

每条用例使用四位 \`case_id\`（如 \`C0001\`），并在 YAML 中显式映射到
\`automation/tests/cases/c0001-<english-slug>.spec.ts\`。slug 只允许小写字母、数字与横杆；
由模型在生成用例时判断并持久化，标题后续调整不会自动改名。
`;

export function scaffoldAutomation(
  featureDir: string,
  opts: { force?: boolean } = {},
): ScaffoldResult {
  const result: ScaffoldResult = { created: [], skipped: [], overwritten: [] };
  const testsDir = join(featureDir, "automation", "tests");

  for (const sub of SUBDIRS) {
    const dir = join(testsDir, sub);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
      result.created.push(dir);
    }
  }

  const smoke = join(testsDir, "runners", "smoke.spec.ts");
  if (!existsSync(smoke)) {
    writeFileSync(smoke, SMOKE_SPEC);
    result.created.push(smoke);
  } else if (opts.force) {
    writeFileSync(smoke, SMOKE_SPEC);
    result.overwritten.push(smoke);
  } else {
    result.skipped.push(smoke);
  }

  const full = join(testsDir, "runners", "full.spec.ts");
  if (!existsSync(full)) {
    writeFileSync(full, FULL_SPEC);
    result.created.push(full);
  } else if (opts.force) {
    writeFileSync(full, FULL_SPEC);
    result.overwritten.push(full);
  } else {
    result.skipped.push(full);
  }

  const readme = join(testsDir, "cases", "README.md");
  if (!existsSync(readme)) {
    writeFileSync(readme, CASES_README);
    result.created.push(readme);
  } else {
    result.skipped.push(readme);
  }

  return result;
}
