import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";

import {
  checkRuntimeWorkflow,
  formatRuntimeWorkflowReport,
} from "@shared/lib/skills/runtime-workflow.ts";

const tempRoots: string[] = [];

function makeRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "kata-runtime-workflow-"));
  tempRoots.push(root);
  return root;
}

function writeRuntimeFile(root: string, rel: string, body: string): void {
  const path = join(root, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body, "utf8");
}

function writeWorkflowEntries(root: string): void {
  const shared = [
    "保留主工作树现有改动。",
    "使用 git worktree add -b 创建任务分支工作树。",
    "清理前盘点 ignored runtime。",
    "通过 git merge --no-ff 合入 main。",
    "不得自动 push。",
    "最后 git worktree remove 本任务工作树。",
    "DataAssets 环境只存 config/env/<env>.yaml。",
  ].join("\n");
  writeRuntimeFile(root, "CLAUDE.md", `# CLAUDE.md\n\n${shared}\n`);
  writeWorkflowRuleFile(root, shared);
}

function writeLegacyDetachedEntries(root: string): void {
  // CLAUDE.md with only legacy content (missing all required workflow phrases)
  const legacy = ["Claude 与 Codex 同等优先。", "不要求两边文件逐字一致。"].join("\n");
  writeRuntimeFile(root, "CLAUDE.md", `# CLAUDE.md\n\n${legacy}\n`);
}

function writeWorkflowRuleFile(root: string, body: string): void {
  writeRuntimeFile(root, `.claude/rules/git-workflow.md`, body);
}

function writeSkill(root: string, runtimeDir: ".claude", name: string, body = ""): void {
  writeRuntimeFile(
    root,
    `${runtimeDir}/skills/${name}/SKILL.md`,
    `---\nname: ${name}\ndescription: example\n---\n# ${name}\n${body}\n`,
  );
}

describe("runtime workflow check", () => {
  afterEach(() => {
    for (const root of tempRoots.splice(0)) {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("passes current runtime workflow entries and clean skills", () => {
    const root = makeRoot();
    writeWorkflowEntries(root);
    writeRuntimeFile(root, ".claude/INDEX.md", "# Claude index\n");
    writeSkill(root, ".claude", "case-draft");
    writeRuntimeFile(
      root,
      ".claude/skills/case-draft/references/fewshots/case-format-sample.md",
      "# Case format sample\n\nUse readable archive fields.\n",
    );

    const report = checkRuntimeWorkflow(root);
    expect(report.passed).toBe(true);
    expect(report.violations).toEqual([]);
    expect(formatRuntimeWorkflowReport(report, root)).toBe("runtime workflow passed");
  });

  test("flags CLAUDE.md symlink and CLAUDE.local.md", () => {
    const root = makeRoot();
    writeRuntimeFile(root, "CLAUDE.md.source", "# source\n");
    symlinkSync("CLAUDE.md.source", join(root, "CLAUDE.md"));
    writeRuntimeFile(root, "CLAUDE.local.md", "# local\n");

    const report = checkRuntimeWorkflow(root);
    expect(report.passed).toBe(false);
    expect(report.violations.some((v) => v.rule === "RUNTIME_ENTRY_SYMLINK")).toBe(true);
    expect(report.violations.some((v) => v.rule === "RUNTIME_LOCAL_ENTRY_PRESENT")).toBe(true);
  });

  test("flags missing synchronization rule in entry files", () => {
    const root = makeRoot();
    writeRuntimeFile(root, "CLAUDE.md", "# CLAUDE.md\n");

    const report = checkRuntimeWorkflow(root);
    expect(report.violations.some((v) => v.rule === "RUNTIME_SYNC_RULE_MISSING")).toBe(true);
  });

  test("flags missing code-change workflow guardrails in entry files", () => {
    const root = makeRoot();
    writeLegacyDetachedEntries(root);

    const report = checkRuntimeWorkflow(root);
    expect(report.violations).toContainEqual(
      expect.objectContaining({
        rule: "RUNTIME_SYNC_RULE_MISSING",
        path: join(root, "CLAUDE.md"),
      }),
    );
  });

  test("flags missing code-change workflow guardrails in the detailed rule file", () => {
    const root = makeRoot();
    writeWorkflowEntries(root);
    writeWorkflowRuleFile(root, "# Rules\n\nOnly old worktree guidance.\n");

    const report = checkRuntimeWorkflow(root);
    expect(report.violations).toContainEqual(
      expect.objectContaining({
        rule: "RUNTIME_SYNC_RULE_MISSING",
        path: join(root, ".claude/rules/git-workflow.md"),
      }),
    );
  });

  test("flags generated markers and active retired source references", () => {
    const root = makeRoot();
    writeWorkflowEntries(root);
    writeRuntimeFile(
      root,
      ".claude/skills/case-edit/SKILL.md",
      [
        "---",
        "name: case-edit",
        "description: example",
        "---",
        "<!-- generated by kata legacy runtime; do not edit -->",
        "<!-- legacy-runtime-hash: abc123 -->",
        "详见 legacy-runtime-source/skills/case-draft/references/retired-format.md",
      ].join("\n"),
    );

    const report = checkRuntimeWorkflow(root);
    expect(report.violations.some((v) => v.rule === "RUNTIME_GENERATED_MARKER")).toBe(true);
    expect(report.violations.some((v) => v.rule === "RUNTIME_RETIRED_SOURCE_REFERENCE")).toBe(true);
  });

  test("flags active retired source references in nested skill reference markdown", () => {
    const root = makeRoot();
    writeWorkflowEntries(root);
    writeRuntimeFile(
      root,
      ".claude/skills/case-draft/references/fewshots/case-format-sample.md",
      "# Case format sample\n\nSSOT: legacy-runtime-source/skills/case-draft/references/retired-format.md\n",
    );

    const report = checkRuntimeWorkflow(root);
    expect(report.passed).toBe(false);
    expect(report.violations).toContainEqual(
      expect.objectContaining({
        rule: "RUNTIME_RETIRED_SOURCE_REFERENCE",
        path: join(root, ".claude/skills/case-draft/references/fewshots/case-format-sample.md"),
      }),
    );
  });

  test("formats workflow failures with relative paths", () => {
    const root = makeRoot();
    writeRuntimeFile(root, "CLAUDE.md", "# CLAUDE.md\n");

    const text = formatRuntimeWorkflowReport(checkRuntimeWorkflow(root), root);
    expect(text).toContain("runtime workflow failed");
    expect(text).toContain("CLAUDE.md");
  });
});
