import { existsSync, lstatSync, readdirSync, readFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

export type RuntimeDetachRule =
  | "RUNTIME_ENTRY_MISSING"
  | "RUNTIME_ENTRY_SYMLINK"
  | "RUNTIME_LOCAL_ENTRY_PRESENT"
  | "RUNTIME_SYNC_RULE_MISSING"
  | "RUNTIME_GENERATED_MARKER"
  | "RUNTIME_AI_CORE_REFERENCE";

export interface RuntimeDetachViolation {
  rule: RuntimeDetachRule;
  path: string;
  message: string;
}

export interface RuntimeDetachReport {
  passed: boolean;
  violations: RuntimeDetachViolation[];
}

const ENTRY_FILES = ["AGENTS.md", "CLAUDE.md"] as const;
// Uses includes() substring matching so minor formatting differences do not break the contract.
const ENTRY_REQUIRED_PHRASES = [
  "Claude 与 Codex 同等优先",
  "同步评估另一套",
  "不得把",
  "作为当前规范来源",
] as const;
const GENERATED_MARKERS = ["generated by kata ai-core", "ai-core-hash"] as const;
const ACTIVE_AI_CORE_REFERENCES = [".ai/core", "projection render", "projection lock"] as const;

export function checkRuntimeDetach(root: string): RuntimeDetachReport {
  const absoluteRoot = resolve(root);
  const violations: RuntimeDetachViolation[] = [];

  checkEntryFiles(absoluteRoot, violations);
  checkLocalEntry(absoluteRoot, violations);
  checkRuntimeTextFiles(absoluteRoot, violations);

  return { passed: violations.length === 0, violations };
}

function checkEntryFiles(root: string, violations: RuntimeDetachViolation[]): void {
  for (const relPath of ENTRY_FILES) {
    const path = join(root, relPath);

    if (!existsSync(path)) {
      violations.push({
        rule: "RUNTIME_ENTRY_MISSING",
        path,
        message: `${relPath} is required`,
      });
      continue;
    }

    const stat = lstatSync(path);
    if (stat.isSymbolicLink()) {
      violations.push({
        rule: "RUNTIME_ENTRY_SYMLINK",
        path,
        message: `${relPath} must be a regular file, not a symlink`,
      });
      continue;
    }

    if (!stat.isFile()) {
      violations.push({
        rule: "RUNTIME_SYNC_RULE_MISSING",
        path,
        message: `${relPath} must be a readable text file with runtime synchronization rules`,
      });
      continue;
    }

    const body = readFileSync(path, "utf8");
    const missingPhrases = ENTRY_REQUIRED_PHRASES.filter((phrase) => !body.includes(phrase));
    if (missingPhrases.length > 0) {
      violations.push({
        rule: "RUNTIME_SYNC_RULE_MISSING",
        path,
        message: `missing required runtime synchronization phrases: ${missingPhrases.join(", ")}`,
      });
    }
  }
}

function checkLocalEntry(root: string, violations: RuntimeDetachViolation[]): void {
  const path = join(root, "CLAUDE.local.md");
  if (!existsSync(path)) return;

  violations.push({
    rule: "RUNTIME_LOCAL_ENTRY_PRESENT",
    path,
    message: "CLAUDE.local.md must not exist in detached runtime",
  });
}

function checkRuntimeTextFiles(root: string, violations: RuntimeDetachViolation[]): void {
  for (const path of collectRuntimeTextFiles(root)) {
    if (!existsSync(path)) continue;

    const stat = lstatSync(path);
    if (!stat.isFile()) continue;

    const body = readFileSync(path, "utf8");
    const generatedMarkers = GENERATED_MARKERS.filter((marker) => body.includes(marker));
    if (generatedMarkers.length > 0) {
      violations.push({
        rule: "RUNTIME_GENERATED_MARKER",
        path,
        message: `runtime text file contains generated marker: ${generatedMarkers.join(", ")}`,
      });
    }

    const activeReferences = ACTIVE_AI_CORE_REFERENCES.filter((reference) =>
      body.includes(reference),
    );
    if (activeReferences.length > 0) {
      violations.push({
        rule: "RUNTIME_AI_CORE_REFERENCE",
        path,
        message: `runtime text file contains active ai-core reference: ${activeReferences.join(", ")}`,
      });
    }
  }
}

function collectRuntimeTextFiles(root: string): string[] {
  return [
    ...ENTRY_FILES.map((entry) => join(root, entry)),
    join(root, ".claude", "INDEX.md"),
    join(root, ".agents", "INDEX.md"),
    ...collectSkillFiles(root, ".claude"),
    ...collectSkillFiles(root, ".agents"),
  ];
}

function collectSkillFiles(root: string, runtimeDir: ".claude" | ".agents"): string[] {
  const skillsRoot = join(root, runtimeDir, "skills");
  if (!existsSync(skillsRoot)) return [];

  const stat = lstatSync(skillsRoot);
  if (!stat.isDirectory() || stat.isSymbolicLink()) return [];

  return collectMarkdownFiles(skillsRoot);
}

function collectMarkdownFiles(dir: string): string[] {
  const paths: string[] = [];

  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    if (entry.isSymbolicLink()) continue;

    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      paths.push(...collectMarkdownFiles(path));
      continue;
    }

    if (entry.isFile() && entry.name.endsWith(".md")) {
      paths.push(path);
    }
  }

  return paths;
}

export function formatRuntimeDetachReport(report: RuntimeDetachReport, root: string): string {
  if (report.passed) return "runtime detach passed";

  const absoluteRoot = resolve(root);
  return [
    "runtime detach failed",
    ...report.violations.map((violation) => {
      return `${violation.rule} ${formatViolationPath(violation.path, absoluteRoot)} ${violation.message}`;
    }),
  ].join("\n");
}

function formatViolationPath(path: string, root: string): string {
  if (path === root || path.startsWith(`${root}/`)) return relative(root, path);
  return path;
}
