import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { loadHandoffV2Validator } from "../schemas/loaders.ts";
import type { Violation } from "./types.ts";

const REQUIRED_HEADER = "<!-- generated by kata handoff render; do not edit -->";
const REQUIRED_SOURCE = "<!-- source: handoff.json -->";
const REQUIRED_SCHEMA = "<!-- schema: PlaywrightAutomationHandoff@2 -->";
const REQUIRED_ACCEPTANCE_HEADING = "## Human Acceptance Command";
const validateHandoff = loadHandoffV2Validator();

function collectResultDirs(workspaceRoot: string): string[] {
  const featuresDir = join(workspaceRoot, "dataAssets/features");
  if (!existsSync(featuresDir)) return [];
  const dirs: string[] = [];
  for (const feat of readdirSync(featuresDir)) {
    const featureDir = join(featuresDir, feat);
    const resultsDir = join(featureDir, "results");
    if (!existsSync(resultsDir)) continue;
    const manifestPath = join(featureDir, "manifest.json");
    if (existsSync(manifestPath)) {
      try {
        const manifest = JSON.parse(readFileSync(manifestPath, "utf-8"));
        const latest = manifest?.files?.latest_results;
        if (typeof latest === "string" && latest.startsWith("results/")) {
          const latestDir = join(featureDir, latest);
          if (existsSync(latestDir) && statSync(latestDir).isDirectory()) {
            dirs.push(latestDir);
            continue;
          }
        }
      } catch {
        // Fall back to scanning all result directories when manifest cannot be read.
      }
    }
    for (const run of readdirSync(resultsDir)) {
      const runDir = join(resultsDir, run);
      if (statSync(runDir).isDirectory()) {
        dirs.push(runDir);
      }
    }
  }
  return dirs;
}

export function lintHandoffDoubleTrack(workspaceRoot: string): { violations: Violation[] } {
  const violations: Violation[] = [];
  for (const runDir of collectResultDirs(workspaceRoot)) {
    const json = join(runDir, "handoff.json");
    const md = join(runDir, "handoff.md");
    const hasJson = existsSync(json);
    const hasMd = existsSync(md);
    if (hasJson && !hasMd) {
      violations.push({
        file: runDir,
        rule: "handoff_md_missing",
        message: "handoff.json without handoff.md",
      });
    }
    if (!hasJson && hasMd) {
      violations.push({
        file: runDir,
        rule: "handoff_json_missing",
        message: "handoff.md without handoff.json",
      });
    }
    if (hasMd) {
      const content = readFileSync(md, "utf-8");
      if (!content.startsWith(REQUIRED_HEADER)) {
        violations.push({
          file: md,
          rule: "handoff_md_header_missing",
          message: "handoff.md must start with the generated header",
        });
      }
      if (!content.includes(REQUIRED_SOURCE)) {
        violations.push({
          file: md,
          rule: "handoff_md_source_marker_missing",
          message: "handoff.md must include source: handoff.json marker",
        });
      }
      if (!content.includes(REQUIRED_SCHEMA)) {
        violations.push({
          file: md,
          rule: "handoff_md_schema_marker_missing",
          message: "handoff.md must include schema: PlaywrightAutomationHandoff@2 marker",
        });
      }
      if (!content.includes(REQUIRED_ACCEPTANCE_HEADING)) {
        violations.push({
          file: md,
          rule: "handoff_md_acceptance_command_missing",
          message: "handoff.md must include a human acceptance command section",
        });
      }
      if (!content.includes("full.spec.ts") || !content.includes("--headed")) {
        violations.push({
          file: md,
          rule: "handoff_md_acceptance_command_invalid",
          message: "handoff.md acceptance command must target full.spec.ts and include --headed",
        });
      }
    }
    if (hasJson) {
      try {
        const parsed = JSON.parse(readFileSync(json, "utf-8"));
        if (!validateHandoff(parsed)) {
          violations.push({
            file: json,
            rule: "handoff_json_schema_invalid",
            message: JSON.stringify(validateHandoff.errors),
          });
        }
      } catch (error) {
        violations.push({
          file: json,
          rule: "handoff_json_schema_invalid",
          message: error instanceof Error ? error.message : String(error),
        });
      }
    }
  }
  return { violations };
}
