import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { type FeatureRow, runFeaturesLs } from "./features-ls.ts";

export interface FeaturesIndexContext {
  readonly project: string;
  readonly workspaceRoot: string;
  /** Accepted for compatibility; generated indexes intentionally contain no timestamp. */
  readonly now?: Date;
  readonly write?: boolean;
}

export interface FeaturesIndexResult {
  readonly path: string;
  readonly content: string;
  readonly written: boolean;
  readonly featureCount: number;
}

function groupBy<T, K extends string | number>(
  rows: T[],
  keyFn: (row: T) => K,
): Map<K, T[]> {
  const groups = new Map<K, T[]>();
  for (const row of rows) {
    const key = keyFn(row);
    const items = groups.get(key) ?? [];
    items.push(row);
    groups.set(key, items);
  }
  return groups;
}

function markdownCell(value: unknown): string {
  return String(value ?? "").replaceAll("|", "\\|").replaceAll("\n", " ");
}

export async function runFeaturesIndex(
  ctx: FeaturesIndexContext,
): Promise<FeaturesIndexResult> {
  const rows = await runFeaturesLs({
    project: ctx.project,
    workspaceRoot: ctx.workspaceRoot,
  });
  const lines: string[] = [];
  lines.push("<!-- generated by kata features index; do not edit -->");
  lines.push(`<!-- feature_count: ${rows.length} -->`);
  lines.push("");
  lines.push("# Features Index");
  lines.push("");

  const byStatus = groupBy(rows, (row) => row.status);
  lines.push("## By Status");
  for (const [status, items] of byStatus) lines.push(`- ${status} (${items.length})`);
  lines.push("");

  const byModule = new Map<string, FeatureRow[]>();
  for (const row of rows) {
    for (const module of row.modules) {
      const items = byModule.get(module) ?? [];
      items.push(row);
      byModule.set(module, items);
    }
  }
  lines.push("## By Module");
  for (const [module, items] of byModule) lines.push(`- ${module} (${items.length})`);
  lines.push("");

  const byGroup = groupBy(rows, (row) => row.group);
  const groupOrder = [...byGroup.keys()].sort((left, right) => {
    const rank = (group: string): number =>
      group.startsWith("_archived") ? 2 : group === "_standing" ? 1 : 0;
    return rank(left) - rank(right) || right.localeCompare(left, undefined, { numeric: true });
  });

  for (const group of groupOrder) {
    const items = byGroup.get(group) ?? [];
    const header = group || "(未分层 legacy)";
    lines.push(`## ${header} (${items.length})`);
    lines.push("| Feature | Display Name | Status | Automation | Last Run | 产物 |");
    lines.push("| --- | --- | --- | --- | --- | --- |");
    for (const row of items) {
      const relativePath = row.group
        ? `${row.group}/${row.dirName}/`
        : `${row.dirName}/`;
      const areas =
        [
          row.areas.cases && "cases",
          row.areas.automation && "auto",
          row.areas.runs && "runs",
        ]
          .filter(Boolean)
          .join("+") || "-";
      lines.push(
        `| [${markdownCell(row.dirName)}](${encodeURI(relativePath)}) | ${markdownCell(row.displayName)} | ${markdownCell(row.status)} | ${markdownCell(row.automationStatus)} | ${markdownCell(row.lastRunStatus)} | ${areas} |`,
      );
    }
    lines.push("");
  }

  const path = join(ctx.workspaceRoot, ctx.project, "features", "INDEX.md");
  const content = `${lines.join("\n")}\n`;
  const written = ctx.write !== false;
  if (written) writeFileSync(path, content, "utf8");
  return { path, content, written, featureCount: rows.length };
}
