import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { type FeatureRow, runFeaturesLs } from "./features-ls.ts";

export interface FeaturesIndexContext {
  project: string;
  workspaceRoot: string;
  now?: Date;
}

function groupBy<T, K extends string | number>(rows: T[], keyFn: (r: T) => K): Map<K, T[]> {
  const m = new Map<K, T[]>();
  for (const r of rows) {
    const k = keyFn(r);
    const arr = m.get(k) ?? [];
    arr.push(r);
    m.set(k, arr);
  }
  return m;
}

export async function runFeaturesIndex(ctx: FeaturesIndexContext): Promise<void> {
  const rows = await runFeaturesLs({ project: ctx.project, workspaceRoot: ctx.workspaceRoot });
  const now = (ctx.now ?? new Date()).toISOString();

  const lines: string[] = [];
  lines.push("<!-- generated by kata features index; do not edit -->");
  lines.push(`<!-- last_generated: ${now} -->`);
  lines.push(`<!-- feature_count: ${rows.length} -->`);
  lines.push("");
  lines.push("# Features Index");
  lines.push("");

  // By Status 统计段
  const byStatus = groupBy(rows, (r) => r.status);
  lines.push("## By Status");
  for (const [status, items] of byStatus) {
    lines.push(`- ${status} (${items.length})`);
  }
  lines.push("");

  // By Module 统计段
  const byModule = new Map<string, FeatureRow[]>();
  for (const r of rows) {
    for (const m of r.modules) {
      const arr = byModule.get(m) ?? [];
      arr.push(r);
      byModule.set(m, arr);
    }
  }
  lines.push("## By Module");
  for (const [mod, items] of byModule) {
    lines.push(`- ${mod} (${items.length})`);
  }
  lines.push("");

  // 按 group（版本目录）分组渲染，版本号降序在前，_standing 次之，_archived/* 最后
  const byGroup = groupBy(rows, (r) => r.group);
  const groupOrder = [...byGroup.keys()].sort((a, b) => {
    const rank = (g: string) => (g.startsWith("_archived") ? 2 : g === "_standing" ? 1 : 0);
    return rank(a) - rank(b) || b.localeCompare(a, undefined, { numeric: true });
  });

  for (const group of groupOrder) {
    const items = byGroup.get(group) ?? [];
    const header = group || "(未分层 legacy)";
    lines.push(`## ${header} (${items.length})`);
    lines.push("| Feature | Display Name | Status | Automation | Last Run | 产物 |");
    lines.push("|---|---|---|---|---|---|");
    for (const r of items) {
      const rel = r.group ? `${r.group}/${r.dirName}/` : `${r.dirName}/`;
      const areas =
        [r.areas.cases && "cases", r.areas.automation && "auto", r.areas.runs && "runs"]
          .filter(Boolean)
          .join("+") || "-";
      lines.push(
        `| [${r.dirName}](${encodeURI(rel)}) | ${r.displayName} | ${r.status} | ${r.automationStatus} | ${r.lastRunStatus} | ${areas} |`,
      );
    }
    lines.push("");
  }

  writeFileSync(
    join(ctx.workspaceRoot, ctx.project, "features", "INDEX.md"),
    `${lines.join("\n")}\n`,
    "utf-8",
  );
}
