// Generated by kata automation coverage. Do not add business logic here.
import { loadPlaywrightAutomationConfig } from "../../../../../../../../runtime/automation/playwright-config";
import { orderAutomationCases } from "../../../../../../../../runtime/automation/case-order";

const generatedCases: ReadonlyArray<{ readonly caseId: string; readonly module: string }> = [
  { caseId: "C0001", module: "../cases/c0001-json-rule-option-order.spec.ts" },
  { caseId: "C0002", module: "../cases/c0002-json-rule-no-help-icon.spec.ts" },
  { caseId: "C0003", module: "../cases/c0003-json-rule-visible-for-field-types.spec.ts" },
  { caseId: "C0004", module: "../cases/c0004-select-configured-value-format-keys.spec.ts" },
  { caseId: "C0005", module: "../cases/c0005-validation-key-multi-select.spec.ts" },
  { caseId: "C0006", module: "../cases/c0006-search-validation-keys.spec.ts" },
  { caseId: "C0007", module: "../cases/c0007-large-key-list-initial-load.spec.ts" },
  { caseId: "C0008", module: "../cases/c0008-key-selection-current-level-only.spec.ts" },
  { caseId: "C0009", module: "../cases/c0009-hover-show-all-key-names.spec.ts" },
  { caseId: "C0010", module: "../cases/c0010-value-format-preview-pagination.spec.ts" },
  { caseId: "C0011", module: "../cases/c0011-json-rule-disabled-for-other-types.spec.ts" },
  { caseId: "C0012", module: "../cases/c0012-require-validation-key.spec.ts" },
  { caseId: "C0013", module: "../cases/c0013-saved-rule-config-fields.spec.ts" },
  { caseId: "C0014", module: "../cases/c0014-json-format-passed-flow.spec.ts" },
  { caseId: "C0015", module: "../cases/c0015-json-format-failed-flow.spec.ts" },
  { caseId: "C0016", module: "../cases/c0016-json-rule-sparkthrift.spec.ts" },
  { caseId: "C0017", module: "../cases/c0017-json-rule-doris.spec.ts" },
  { caseId: "C0018", module: "../cases/c0018-json-rule-hive.spec.ts" },
  { caseId: "C0019", module: "../cases/c0019-large-json-key-validation.spec.ts" },
  { caseId: "C0020", module: "../cases/c0020-delete-referenced-key-config.spec.ts" },
  { caseId: "C0021", module: "../cases/c0021-delete-referenced-key-preview-execution.spec.ts" },
  { caseId: "C0022", module: "../cases/c0022-json-rule-with-sampling.spec.ts" },
  { caseId: "C0023", module: "../cases/c0023-json-rule-partition-validation.spec.ts" },
  { caseId: "C0024", module: "../cases/c0024-json-rule-built-in-rule.spec.ts" },
  { caseId: "C0025", module: "../cases/c0025-failed-detail-download-marked-fields.spec.ts" },
  { caseId: "C0026", module: "../cases/c0026-passed-validation-no-details.spec.ts" },
  { caseId: "C0027", module: "../cases/c0027-failed-validation-log.spec.ts" },
  { caseId: "C0028", module: "../cases/c0028-passed-json-quality-report.spec.ts" },
  { caseId: "C0029", module: "../cases/c0029-failed-json-quality-report.spec.ts" },
];

const orderedCases = orderAutomationCases(
  generatedCases,
  loadPlaywrightAutomationConfig().sortCases,
);

for (const generatedCase of orderedCases) {
  await import(generatedCase.module);
}
