// Generated by kata automation coverage. Do not add business logic here.
import { loadPlaywrightAutomationConfig } from "../../../../../../../../runtime/automation/config/playwright";
import { orderAutomationCases } from "../../../../../../../../runtime/automation/runner/case-order";

const generatedCases: ReadonlyArray<{ readonly caseId: string; readonly module: string }> = [
];

const orderedCases = orderAutomationCases(
  generatedCases,
  loadPlaywrightAutomationConfig().sortCases,
);

for (const generatedCase of orderedCases) {
  await import(generatedCase.module);
}
