// Generated by kata automation coverage. Do not add business logic here.
import "../cases/t01-rule-base-entry.ts";
import "../cases/t02-monitor-new-rule-categories.ts";
import "../cases/t03-new-builtins-function-contract.ts";
import "../cases/t04-c004.ts";
import "../cases/t05-c005.ts";
import "../cases/t06-c006.ts";
import "../cases/t07-c007.ts";
import "../cases/t08-c008.ts";
import "../cases/t09-c009.ts";
