// Generated by kata automation coverage. Do not add business logic here.
import { loadPlaywrightAutomationConfig } from "../../../../../../../../runtime/automation/playwright-config";
import { orderAutomationCases } from "../../../../../../../../runtime/automation/case-order";

const generatedCases: ReadonlyArray<{ readonly caseId: string; readonly module: string }> = [
  { caseId: "C0001", module: "../cases/c0001-starrocks-import-authorize-and-select.spec.ts" },
  { caseId: "C0002", module: "../cases/c0002-starrocks-overview-task-statistics.spec.ts" },
  { caseId: "C0003", module: "../cases/c0003-starrocks-batch-rule-package-run.spec.ts" },
  { caseId: "C0004", module: "../cases/c0004-starrocks-table-row-count-rule.spec.ts" },
  { caseId: "C0005", module: "../cases/c0005-starrocks-null-count-single-field.spec.ts" },
  { caseId: "C0006", module: "../cases/c0006-starrocks-null-count-multi-field.spec.ts" },
  { caseId: "C0007", module: "../cases/c0007-starrocks-null-rate-single-field.spec.ts" },
  { caseId: "C0008", module: "../cases/c0008-starrocks-null-rate-multi-field.spec.ts" },
  { caseId: "C0009", module: "../cases/c0009-starrocks-empty-string-count-single-field.spec.ts" },
  { caseId: "C0010", module: "../cases/c0010-starrocks-empty-string-count-multi-field.spec.ts" },
  { caseId: "C0011", module: "../cases/c0011-starrocks-empty-string-rate-single-field.spec.ts" },
  { caseId: "C0012", module: "../cases/c0012-starrocks-empty-string-rate-multi-field.spec.ts" },
  { caseId: "C0013", module: "../cases/c0013-starrocks-sum-rule.spec.ts" },
  { caseId: "C0014", module: "../cases/c0014-starrocks-average-rule.spec.ts" },
  { caseId: "C0015", module: "../cases/c0015-starrocks-negative-ratio-rule.spec.ts" },
  { caseId: "C0017", module: "../cases/c0017-starrocks-positive-ratio-rule.spec.ts" },
  { caseId: "C0018", module: "../cases/c0018-starrocks-numeric-range-rule.spec.ts" },
  { caseId: "C0019", module: "../cases/c0019-starrocks-numeric-enum-range-rule.spec.ts" },
  { caseId: "C0020", module: "../cases/c0020-starrocks-numeric-enum-count-rule.spec.ts" },
  { caseId: "C0021", module: "../cases/c0021-starrocks-string-max-length-rule.spec.ts" },
  { caseId: "C0022", module: "../cases/c0022-starrocks-string-min-length-rule.spec.ts" },
  { caseId: "C0023", module: "../cases/c0023-starrocks-id-card-format-rule.spec.ts" },
  { caseId: "C0024", module: "../cases/c0024-starrocks-phone-format-rule.spec.ts" },
  { caseId: "C0025", module: "../cases/c0025-starrocks-email-format-rule.spec.ts" },
  { caseId: "C0026", module: "../cases/c0026-starrocks-duplicate-count-single-field.spec.ts" },
  { caseId: "C0027", module: "../cases/c0027-starrocks-duplicate-count-multi-field.spec.ts" },
  { caseId: "C0028", module: "../cases/c0028-starrocks-duplicate-rate-single-field.spec.ts" },
  { caseId: "C0029", module: "../cases/c0029-starrocks-duplicate-rate-multi-field.spec.ts" },
  { caseId: "C0030", module: "../cases/c0030-starrocks-distinct-count-rule.spec.ts" },
  { caseId: "C0031", module: "../cases/c0031-starrocks-distinct-ratio-rule.spec.ts" },
  { caseId: "C0032", module: "../cases/c0032-starrocks-custom-sql-single-table-delete-error.spec.ts" },
  { caseId: "C0033", module: "../cases/c0033-starrocks-custom-sql-cross-table-missing.spec.ts" },
  { caseId: "C0034", module: "../cases/c0034-starrocks-table-compare-field-consistency.spec.ts" },
  { caseId: "C0035", module: "../cases/c0035-starrocks-table-compare-value-difference.spec.ts" },
  { caseId: "C0036", module: "../cases/c0036-starrocks-table-compare-case-insensitive.spec.ts" },
  { caseId: "C0037", module: "../cases/c0037-starrocks-table-compare-null-equivalence.spec.ts" },
  { caseId: "C0038", module: "../cases/c0038-starrocks-table-compare-anomaly-categories.spec.ts" },
  { caseId: "C0039", module: "../cases/c0039-starrocks-rule-config-search-filter.spec.ts" },
  { caseId: "C0040", module: "../cases/c0040-starrocks-rule-task-edit-rerun.spec.ts" },
  { caseId: "C0041", module: "../cases/c0041-starrocks-rule-task-delete.spec.ts" },
  { caseId: "C0042", module: "../cases/c0042-starrocks-task-instance-details.spec.ts" },
  { caseId: "C0043", module: "../cases/c0043-starrocks-dirty-data-storage-retention.spec.ts" },
];

const orderedCases = orderAutomationCases(
  generatedCases,
  loadPlaywrightAutomationConfig().sortCases,
);

for (const generatedCase of orderedCases) {
  await import(generatedCase.module);
}
