import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { stringify } from "yaml";
import { runFeaturesIndex } from "../../src/cli/features-index.ts";

function seed(
  scratch: string,
  id: string,
  opts: { modules?: string[]; status?: string; displayName?: string },
) {
  const dir = join(scratch, "dataAssets/features", id);
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    join(dir, "metadata.yaml"),
    stringify({
      schema: "FeatureMetadata@1",
      id,
      display_name: opts.displayName ?? id,
      status: opts.status ?? "active",
      created_at: "2026-04-01",
      updated_at: "2026-04-01",
      modules: opts.modules ?? [],
      customers: [],
      versions: [],
      owners: [],
      inputs: [],
      relates_to: [],
      emits: { cases_xmind: true, archive: true, playwright_tests: true },
    }),
  );
  writeFileSync(
    join(dir, "manifest.json"),
    JSON.stringify({
      schema: "FeatureManifest@2",
      feature_id: id,
      case_drafting: { status: "completed" },
      automation: { status: "ready", intents: [], last_run_status: "passing" },
      files: {},
    }),
  );
}

describe("kata features index", () => {
  let scratch: string;
  beforeEach(() => {
    scratch = mkdtempSync(join(tmpdir(), "kata-feat-idx-"));
    seed(scratch, "2026-04-dq-a", { modules: ["dq"], status: "active", displayName: "数据质量A" });
    seed(scratch, "2026-04-sec-b", { modules: ["security"], status: "active" });
    seed(scratch, "2026-03-old", { modules: ["dq"], status: "archived" });
  });
  afterEach(() => rmSync(scratch, { recursive: true, force: true }));

  it("writes INDEX.md with feature_count = 3", async () => {
    await runFeaturesIndex({
      project: "dataAssets",
      workspaceRoot: scratch,
      now: new Date("2026-05-14T10:00:00Z"),
    });
    const content = readFileSync(join(scratch, "dataAssets/features/INDEX.md"), "utf-8");
    expect(content).toContain("<!-- feature_count: 3 -->");
    expect(content).toContain("数据质量A");
    expect(content).toContain("## By Module");
    expect(content).toContain("dq");
    expect(content).toContain("security");
  });

  it("includes a 'do not edit' header", async () => {
    await runFeaturesIndex({ project: "dataAssets", workspaceRoot: scratch });
    const content = readFileSync(join(scratch, "dataAssets/features/INDEX.md"), "utf-8");
    expect(content).toContain("<!-- generated by kata features index; do not edit -->");
  });
});
