import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { listFeatureDirs, runsDir } from "@shared/lib/features/layout.ts";
import { handoffV2SemanticErrors, loadHandoffV2Validator } from "@shared/schemas/loaders.ts";
import type { Violation } from "./types.ts";

const REQUIRED_HEADER = "<!-- generated by kata handoff render; do not edit -->";
const REQUIRED_SOURCE = "<!-- source: handoff.json -->";
const REQUIRED_SCHEMA = "<!-- schema: PlaywrightAutomationHandoff@2 -->";
const REQUIRED_ACCEPTANCE_HEADING = "## Human Acceptance Command";
const validateHandoff = loadHandoffV2Validator();

function collectResultDirs(workspaceRoot: string): string[] {
  // 扫所有项目下的 features/，支持版本层（三区布局）和 legacy-flat 两种结构
  const dirs: string[] = [];
  if (!existsSync(workspaceRoot)) return dirs;
  let projects: string[];
  try {
    projects = readdirSync(workspaceRoot, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name);
  } catch {
    return dirs;
  }
  for (const project of projects) {
    const featuresDir = join(workspaceRoot, project, "features");
    if (!existsSync(featuresDir)) continue;
    for (const entry of listFeatureDirs(featuresDir)) {
      const runsDirPath = runsDir(entry.dir);
      if (!existsSync(runsDirPath)) continue;
      try {
        for (const run of readdirSync(runsDirPath)) {
          const runDir = join(runsDirPath, run);
          try {
            if (statSync(runDir).isDirectory()) dirs.push(runDir);
          } catch {
            /* 跳过不可访问的目录 */
          }
        }
      } catch {
        /* 跳过不可访问的目录 */
      }
    }
  }
  return dirs;
}

export function lintHandoffDoubleTrack(workspaceRoot: string): {
  violations: Violation[];
} {
  const violations: Violation[] = [];
  for (const runDir of collectResultDirs(workspaceRoot)) {
    const json = join(runDir, "handoff.json");
    const md = join(runDir, "handoff.md");
    const hasJson = existsSync(json);
    const hasMd = existsSync(md);
    if (hasJson && !hasMd) {
      violations.push({
        file: runDir,
        rule: "handoff_md_missing",
        message: "handoff.json without handoff.md",
      });
    }
    if (!hasJson && hasMd) {
      violations.push({
        file: runDir,
        rule: "handoff_json_missing",
        message: "handoff.md without handoff.json",
      });
    }
    if (hasMd) {
      const content = readFileSync(md, "utf-8");
      if (!content.startsWith(REQUIRED_HEADER)) {
        violations.push({
          file: md,
          rule: "handoff_md_header_missing",
          message: "handoff.md must start with the generated header",
        });
      }
      if (!content.includes(REQUIRED_SOURCE)) {
        violations.push({
          file: md,
          rule: "handoff_md_source_marker_missing",
          message: "handoff.md must include source: handoff.json marker",
        });
      }
      if (!content.includes(REQUIRED_SCHEMA)) {
        violations.push({
          file: md,
          rule: "handoff_md_schema_marker_missing",
          message: "handoff.md must include schema: PlaywrightAutomationHandoff@2 marker",
        });
      }
      if (!content.includes(REQUIRED_ACCEPTANCE_HEADING)) {
        violations.push({
          file: md,
          rule: "handoff_md_acceptance_command_missing",
          message: "handoff.md must include a human acceptance command section",
        });
      }
      if (!content.includes("full.spec.ts") || !content.includes("--headed")) {
        violations.push({
          file: md,
          rule: "handoff_md_acceptance_command_invalid",
          message: "handoff.md acceptance command must target full.spec.ts and include --headed",
        });
      }
    }
    if (hasJson) {
      try {
        const parsed = JSON.parse(readFileSync(json, "utf-8"));
        if (!validateHandoff(parsed)) {
          violations.push({
            file: json,
            rule: "handoff_json_schema_invalid",
            message: JSON.stringify(validateHandoff.errors),
          });
        } else {
          const semanticErrors = handoffV2SemanticErrors(parsed);
          if (semanticErrors.length > 0) {
            violations.push({
              file: json,
              rule: "handoff_json_semantic_invalid",
              message: semanticErrors.join("; "),
            });
          }
        }
      } catch (error) {
        violations.push({
          file: json,
          rule: "handoff_json_schema_invalid",
          message: error instanceof Error ? error.message : String(error),
        });
      }
    }
  }
  return { violations };
}
