// Generated by kata automation coverage. Do not add business logic here.
import { loadPlaywrightAutomationConfig } from "../../../../../../../../runtime/automation/config/playwright";
import { orderAutomationCases } from "../../../../../../../../runtime/automation/runner/case-order";

const generatedCases: ReadonlyArray<{ readonly caseId: string; readonly module: string }> = [
  { caseId: "C0001", module: "../cases/c0001-metadata-sync-record-actions.spec.ts" },
  { caseId: "C0003", module: "../cases/c0003-data-model-design-and-elements.spec.ts" },
  { caseId: "C0004", module: "../cases/c0004-quality-project-search-and-pin.spec.ts" },
];

const orderedCases = orderAutomationCases(
  generatedCases,
  loadPlaywrightAutomationConfig().sortCases,
);

for (const generatedCase of orderedCases) {
  await import(generatedCase.module);
}
