// Generated by kata automation coverage. Do not add business logic here.
import "../cases/t01-json-checkbox-export.ts";
import "../cases/t02-c002.ts";
import "../cases/t03-c003.ts";
import "../cases/t04-c004.ts";
import "../cases/t05-c005.ts";
import "../cases/t06-c006.ts";
import "../cases/t07-c007.ts";
import "../cases/t08-c008.ts";
import "../cases/t09-c009.ts";
