// Generated by kata automation coverage. Do not add business logic here.
import { loadPlaywrightAutomationConfig } from "../../../../../../../../lib/automation/playwright-config";
import { orderAutomationCases } from "../../../../../../../../lib/automation/case-order";

const generatedCases: ReadonlyArray<{ readonly caseId: string; readonly module: string }> = [
  { caseId: "C0001", module: "../cases/c0001-export-selected-json-records.spec.ts" },
];

const orderedCases = orderAutomationCases(
  generatedCases,
  loadPlaywrightAutomationConfig().sortCases,
);

for (const generatedCase of orderedCases) {
  await import(generatedCase.module);
}
