import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { basename, join, relative } from "node:path";
import { writeFileAtomic } from "./atomic-writer.ts";
import { parseCasesYaml } from "./cases/parse.ts";

export interface AutomationCaseLink {
  id: string;
  title: string;
  specFile?: string;
}

export interface AutomationCoverage {
  yamlPath: string;
  cases: AutomationCaseLink[];
  missingSpecFile: string[];
  missingScript: string[];
  orphanScripts: string[];
  duplicateSpecFile: string[];
}

function findYaml(featureDir: string): string {
  const dir = join(featureDir, "cases");
  const files = existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith(".yaml")) : [];
  if (files.length !== 1) throw new Error(`cases/ 下 yaml 必须唯一，当前为 ${files.length}`);
  return join(dir, files[0]);
}

function scriptFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  const walk = (current: string): void => {
    for (const name of readdirSync(current)) {
      const path = join(current, name);
      if (name === ".gitkeep") continue;
      if (statSync(path).isDirectory()) walk(path);
      else if (name.endsWith(".ts")) out.push(relative(dir, path).split("\\").join("/"));
    }
  };
  walk(dir);
  return out.sort();
}

export function inspectAutomationCoverage(featureDir: string): AutomationCoverage {
  const yamlPath = findYaml(featureDir);
  const file = parseCasesYaml(readFileSync(yamlPath, "utf8"));
  const scripts = scriptFiles(join(featureDir, "automation", "tests", "cases"));
  const byBase = new Map(scripts.map((path) => [basename(path), path]));
  const cases = file.cases.map((item) => ({
    id: item.id,
    title: item.title,
    specFile: item.automation?.spec_file,
  }));
  const missingSpecFile = cases.filter((item) => !item.specFile).map((item) => item.id);
  const missingScript = cases
    .filter((item) => item.specFile && !byBase.has(item.specFile))
    .map((item) => `${item.id}:${item.specFile}`);
  const linked = new Set(cases.flatMap((item) => (item.specFile ? [item.specFile] : [])));
  const orphanScripts = scripts.filter((path) => !linked.has(basename(path)));
  const specCounts = new Map<string, number>();
  for (const item of cases) {
    if (item.specFile) specCounts.set(item.specFile, (specCounts.get(item.specFile) ?? 0) + 1);
  }
  const duplicateSpecFile = [...specCounts.entries()]
    .filter(([, count]) => count > 1)
    .map(([specFile]) => specFile)
    .sort();
  return { yamlPath, cases, missingSpecFile, missingScript, orphanScripts, duplicateSpecFile };
}

export function generateAutomationRunner(
  featureDir: string,
  opts: { apply?: boolean } = {},
): { path: string; imports: string[]; coverage: AutomationCoverage } {
  const coverage = inspectAutomationCoverage(featureDir);
  if (coverage.missingSpecFile.length || coverage.missingScript.length) {
    throw new Error(
      `自动化覆盖不完整: missing spec_file=${coverage.missingSpecFile.join(",")}; missing script=${coverage.missingScript.join(",")}`,
    );
  }
  const casesDir = join(featureDir, "automation", "tests", "cases");
  const scripts = scriptFiles(casesDir);
  const full = join(featureDir, "automation", "tests", "runners", "full.spec.ts");
  const fullText = existsSync(full) ? readFileSync(full, "utf8") : "";
  const existingRunnerScripts = new Set(
    [...fullText.matchAll(/(?:\.\.?\/cases\/)([^\s"']+\.ts)/g)].map((match) => basename(match[1])),
  );
  const imports = coverage.cases
    .filter((item) => !existingRunnerScripts.has(item.specFile ?? ""))
    .map((item) => {
      const path = scripts.find((candidate) => basename(candidate) === item.specFile);
      if (!path) throw new Error(`找不到自动化脚本: ${item.specFile}`);
      return `../cases/${path}`;
    });
  const runner = join(featureDir, "automation", "tests", "runners", "generated.spec.ts");
  const content = [
    "// Generated by kata automation coverage. Do not add business logic here.",
    ...[...new Set(imports)].sort().map((path) => `import ${JSON.stringify(path)};`),
    "",
  ].join("\n");
  if (opts.apply) {
    writeFileAtomic(runner, content);
    const full = join(featureDir, "automation", "tests", "runners", "full.spec.ts");
    if (existsSync(full)) {
      if (!fullText.includes("./generated.spec")) {
        writeFileAtomic(full, `import "./generated.spec";\n${fullText}`);
      }
    }
  }
  return { path: runner, imports: [...new Set(imports)].sort(), coverage };
}
