import { test } from "../../../../../../_shared/automation/fixtures/step-screenshot";
import { expect } from "@playwright/test";
import { type SparkThriftQualityRuleValidationScenario } from "../../../../../../_shared/automation/pages/data-quality/page-context";
import { expectSparkThriftQualityRuleMatrixContract } from "../../../../../../_shared/automation/pages/data-quality/sparkthrift-rule-validation";

test.setTimeout(45 * 60 * 1000);

const COMMON_SCENARIO = {
  tableName: "test_return2",
  passPartition: "dt='2025-11-07'",
  failPartition: "dt='2025-11-08'",
  passExpectedValue: "",
  failExpectedValue: "",
  dirtyEvidence: [],
} as const;

type RuleSpec = Omit<SparkThriftQualityRuleValidationScenario, "datasourceKey"> & { key: string };

const RULES: readonly RuleSpec[] = [
  {
    key: "completeness_row_count",
    archiveLine: 1550,
    title: "v700-完整性-表行数",
    ...COMMON_SCENARIO,
    ruleCategory: "完整性校验",
    scope: "单表",
    statisticFunction: "表行数",
    fields: [],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "固定值", operator: ">", value: "0" },
    description: "v700-完整性-表行数",
  },
  {
    key: "completeness_null_count",
    archiveLine: 1562,
    title: "v700-完整性-空值数",
    ...COMMON_SCENARIO,
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "空值数",
    fields: ["id"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "固定值", operator: "<=", value: "0" },
    description: "v700-完整性-空值数",
  },
  {
    key: "completeness_null_rate",
    archiveLine: 1573,
    title: "v700-完整性-空值率",
    ...COMMON_SCENARIO,
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "空值率",
    fields: ["id"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "固定值", operator: "<=", value: "0" },
    description: "v700-完整性-空值率",
  },
  {
    key: "completeness_empty_count",
    archiveLine: 1584,
    title: "v700-完整性-空串数",
    ...COMMON_SCENARIO,
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "空串数",
    fields: ["name"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "固定值", operator: "=", value: "0" },
    description: "v700-完整性-空串数",
  },
  {
    key: "completeness_empty_rate",
    archiveLine: 1595,
    title: "v700-完整性-空串率",
    ...COMMON_SCENARIO,
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "空串率",
    fields: ["name"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "固定值", operator: "=", value: "0" },
    description: "v700-完整性-空串率",
  },
  {
    key: "completeness_value_range",
    archiveLine: 1606,
    title: "v700-完整性-字段取值范围",
    ...COMMON_SCENARIO,
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "字段取值范围校验",
    fields: ["id"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "固定值", operator: ">", value: "0" },
    description: "v700-完整性-字段取值范围",
  },
  {
    key: "completeness_key_range",
    archiveLine: 1616,
    title: "v700-完整性-key范围",
    ...COMMON_SCENARIO,
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "key范围校验",
    fields: ["info"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }, { label: "校验内容", value: "key1，key2" }],
    ruleOptions: [{ label: /校验方法/, value: "包含" }],
    description: "v700-完整性-key范围",
  },
  {
    key: "completeness_row_compare",
    archiveLine: 1627,
    title: "v700-完整性-多表行数",
    ...COMMON_SCENARIO,
    comparisonTableName: "test_schema4",
    ruleCategory: "完整性校验",
    scope: "多表",
    statisticFunction: "多表行数比对",
    fields: [],
    ruleInputs: [{ label: "分区", value: "dt='2025-11-07'" }],
    description: "v700-完整性-多表行数",
  },
  {
    key: "completeness_content_compare",
    archiveLine: 1636,
    title: "v700-完整性-多表内容",
    ...COMMON_SCENARIO,
    comparisonTableName: "test_schema4",
    ruleCategory: "完整性校验",
    scope: "多表",
    statisticFunction: "多表数据内容对比",
    fields: ["id"],
    comparisonFields: ["vin"],
    primaryKeys: ["id"],
    comparisonPrimaryKeys: ["vin"],
    fieldLogic: "and",
    ruleInputs: [{ label: "期望值", value: "<=100" }, { label: "对比表期望值", value: "<=100" }],
    description: "v700-完整性-多表内容",
  },
  {
    key: "validity_numeric_range",
    archiveLine: 1656,
    title: "v700-有效性-数值范围",
    ...COMMON_SCENARIO,
    ruleCategory: "有效性校验",
    scope: "字段级",
    statisticFunction: "数值-取值范围",
    fields: ["id"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }, { label: "期望值", value: ">0且<=99" }],
    description: "v700-有效性-数值范围",
  },
  {
    key: "validity_enum_count",
    archiveLine: 1665,
    title: "v700-有效性-枚举个数",
    ...COMMON_SCENARIO,
    ruleCategory: "有效性校验",
    scope: "字段级",
    statisticFunction: "数值-枚举个数",
    fields: ["id"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "固定值", operator: ">=", value: "1" },
    description: "v700-有效性-枚举个数",
  },
  {
    key: "validity_id_number",
    archiveLine: 1675,
    title: "v700-有效性-身份证号",
    ...COMMON_SCENARIO,
    ruleCategory: "有效性校验",
    scope: "字段级",
    statisticFunction: "格式-身份证号",
    fields: ["id_number"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "占比", operator: ">=", value: "0%" },
    description: "v700-有效性-身份证号",
  },
  {
    key: "validity_phone",
    archiveLine: 1685,
    title: "v700-有效性-手机号",
    ...COMMON_SCENARIO,
    ruleCategory: "有效性校验",
    scope: "字段级",
    statisticFunction: "格式-手机号",
    fields: ["phone"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "固定值", operator: ">=", value: "0" },
    description: "v700-有效性-手机号",
  },
  {
    key: "validity_email",
    archiveLine: 1695,
    title: "v700-有效性-邮箱",
    ...COMMON_SCENARIO,
    ruleCategory: "有效性校验",
    scope: "字段级",
    statisticFunction: "格式-邮箱",
    fields: ["email"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "固定值", operator: ">=", value: "0" },
    description: "v700-有效性-邮箱",
  },
  {
    key: "validity_string_length",
    archiveLine: 1705,
    title: "v700-有效性-字符串长度",
    ...COMMON_SCENARIO,
    ruleCategory: "有效性校验",
    scope: "字段级",
    statisticFunction: "字符串长度",
    fields: ["name"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "固定值", operator: ">=", value: "0" },
    description: "v700-有效性-字符串长度",
  },
  {
    key: "validity_precision",
    archiveLine: 1715,
    title: "v700-有效性-数据精度",
    ...COMMON_SCENARIO,
    ruleCategory: "有效性校验",
    scope: "字段级",
    statisticFunction: "数据精度",
    fields: ["money"],
    ruleInputs: [{ label: "小数点前最大位", value: "=4" }, { label: "过滤条件", value: "id < 100" }],
    description: "v700-有效性-数据精度",
  },
  {
    key: "validity_enum_value",
    archiveLine: 1725,
    title: "v700-有效性-枚举值",
    ...COMMON_SCENARIO,
    ruleCategory: "有效性校验",
    scope: "字段级",
    statisticFunction: "枚举值",
    fields: ["id"],
    ruleInputs: [{ label: "枚举值信息", value: "in 2/3/4/5/7/8/9/10" }, { label: "过滤条件", value: "id < 100" }],
    description: "v700-有效性-枚举值",
  },
  {
    key: "validity_date",
    archiveLine: 1734,
    title: "v700-有效性-date格式",
    ...COMMON_SCENARIO,
    ruleCategory: "有效性校验",
    scope: "字段级",
    statisticFunction: "格式校验-日期格式date",
    fields: ["create_time"],
    ruleOptions: [{ label: /日期格式/, value: "YYYY-MM-DD" }],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "占比", operator: "=", value: "100%" },
    description: "v700-有效性-date格式",
  },
  {
    key: "validity_datetime",
    archiveLine: 1745,
    title: "v700-有效性-datetime格式",
    ...COMMON_SCENARIO,
    ruleCategory: "有效性校验",
    scope: "字段级",
    statisticFunction: "格式校验-日期格式datetime",
    fields: ["create_datetime1"],
    ruleOptions: [{ label: /日期格式/, value: "YYYY-MM-DD hh:mm:ss" }],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "占比", operator: "<=", value: "100%" },
    description: "v700-有效性-datetime格式",
  },
  {
    key: "validity_custom_regex",
    archiveLine: 1756,
    title: "v700-有效性-自定义正则",
    ...COMMON_SCENARIO,
    ruleCategory: "有效性校验",
    scope: "字段级",
    statisticFunction: "格式校验-自定义正则",
    fields: ["id"],
    ruleOptions: [{ label: /自定义规则/, value: "正整数" }, { label: /校验格式/, value: "占比" }],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "占比", operator: "=", value: "100%" },
    description: "v700-有效性-自定义正则",
  },
  {
    key: "validity_range_enum",
    archiveLine: 1767,
    title: "v700-有效性-范围枚举",
    ...COMMON_SCENARIO,
    ruleCategory: "有效性校验",
    scope: "字段级",
    statisticFunction: "取值范围&枚举范围",
    fields: ["id"],
    ruleOptions: [
      { label: /取值范围设置/, value: "期望值>1且<=10" },
      { label: /枚举值设置/, value: "not in 1" },
      { label: /取值范围和枚举值的关系/, value: "且" },
    ],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    description: "v700-有效性-范围枚举",
  },
  {
    key: "validity_json",
    archiveLine: 1778,
    title: "v700-有效性-json格式",
    ...COMMON_SCENARIO,
    ruleCategory: "有效性校验",
    scope: "字段级",
    statisticFunction: "格式-json格式校验：key1-name，key2",
    fields: ["info"],
    ruleInputs: [{ label: "过滤条件", value: "id <=4" }],
    description: "v700-有效性-json格式",
  },
  {
    key: "uniqueness_duplicate_count",
    archiveLine: 1795,
    title: "v700-唯一性-重复数",
    ...COMMON_SCENARIO,
    ruleCategory: "唯一性校验",
    scope: "字段级",
    statisticFunction: "重复数",
    fields: ["id"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "固定值", operator: "=", value: "0" },
    description: "v700-唯一性-重复数",
  },
  {
    key: "uniqueness_duplicate_rate",
    archiveLine: 1805,
    title: "v700-唯一性-重复率",
    ...COMMON_SCENARIO,
    ruleCategory: "唯一性校验",
    scope: "字段级",
    statisticFunction: "重复率",
    fields: ["id"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "固定值", operator: "=", value: "0%" },
    description: "v700-唯一性-重复率",
  },
  {
    key: "uniqueness_multi_table",
    archiveLine: 1815,
    title: "v700-唯一性-多表判断",
    ...COMMON_SCENARIO,
    comparisonTableName: "test_schema4",
    ruleCategory: "唯一性校验",
    scope: "多表",
    statisticFunction: "多表唯一性判断",
    fields: ["id"],
    comparisonFields: ["vin"],
    ruleOptions: [
      { label: /校验字段逻辑/, value: "唯一" },
      { label: /和其他表的关系|和其他表的校验关系/, value: "且" },
    ],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    description: "v700-唯一性-多表判断",
  },
  {
    key: "statistics_iqr_count",
    archiveLine: 1834,
    title: "v700-统计性-IQR数量",
    ...COMMON_SCENARIO,
    ruleCategory: "统计性校验",
    scope: "字段级",
    statisticFunction: "异常值检测",
    fields: ["id"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "IQR离群点数量", operator: "!=", value: "1" },
    description: "v700-统计性-IQR数量",
  },
  {
    key: "statistics_iqr_rate",
    archiveLine: 1844,
    title: "v700-统计性-IQR占比",
    ...COMMON_SCENARIO,
    ruleCategory: "统计性校验",
    scope: "字段级",
    statisticFunction: "异常值检测",
    fields: ["id"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    expectation: { method: "IQR离群点占比", operator: "!=", value: "1%" },
    description: "v700-统计性-IQR占比",
  },
  {
    key: "statistics_z_score",
    archiveLine: 1854,
    title: "v700-统计性-Z-score",
    ...COMMON_SCENARIO,
    ruleCategory: "统计性校验",
    scope: "字段级",
    statisticFunction: "异常值检测",
    fields: ["id"],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }, { label: "期望值", value: "(-1000，1000)" }],
    expectation: { method: "Z-score置信区间", value: "(-1000，1000)" },
    description: "v700-统计性-Z-score",
  },
  {
    key: "custom_sql",
    archiveLine: 1870,
    title: "v700-自定义SQL",
    ...COMMON_SCENARIO,
    ruleCategory: "完整性校验",
    scope: "字段级",
    statisticFunction: "自定义SQL",
    fields: ["id"],
    customSqlTemplate: {
      ruleName: "v700-自定义SQL模板",
      ruleType: 1,
      relationRange: 3,
      ruleDesc: "v700-自定义SQL模板",
      customConfiguration: "select * from ${tableName} where ${colName} = ${value}",
      params: [
        { param: "${tableName}", type: 4, paramName: "当前校验表", description: "当前任务主表" },
        { param: "${colName}", type: 4, paramName: "字段", description: "字段名" },
        { param: "${value}", type: 4, paramName: "值", description: "比较值" },
      ],
    },
    ruleInputs: [{ label: "参数", value: "id" }],
    expectation: { method: "固定值", operator: ">", value: "1" },
    description: "v700-自定义SQL",
  },
  {
    key: "consistency_single_table",
    archiveLine: 1887,
    title: "v700-一致性-单对比表",
    ...COMMON_SCENARIO,
    comparisonTableName: "test_schema3",
    ruleCategory: "一致性校验",
    scope: "多表",
    statisticFunction: "多表数据一致性比对",
    fields: ["name"],
    comparisonFields: ["name"],
    primaryKeys: ["id"],
    comparisonPrimaryKeys: ["id"],
    ruleInputs: [
      { label: "输入分区", value: "dt='2025-11-07'" },
      { label: "比对细节设置", value: "数值差异百分比小于等于100%" },
    ],
    description: "v700-一致性-单对比表",
  },
  {
    key: "consistency_multiple_table",
    archiveLine: 1900,
    title: "v700-一致性-多对比表",
    ...COMMON_SCENARIO,
    comparisonTableName: "test_schema3",
    ruleCategory: "一致性校验",
    scope: "多表",
    statisticFunction: "多表数据一致性比对",
    fields: ["name"],
    comparisonFields: ["name"],
    primaryKeys: ["id"],
    comparisonPrimaryKeys: ["id"],
    ruleInputs: [
      { label: "输入分区", value: "dt='2025-11-07'" },
      { label: "对比表2", value: "test_schema4" },
      { label: "比对字段设置", value: "对比表1：name" },
    ],
    description: "v700-一致性-多对比表",
  },
  {
    key: "timeliness_single_field",
    archiveLine: 1922,
    title: "v700-时效性-单字段",
    ...COMMON_SCENARIO,
    ruleCategory: "时效性校验",
    scope: "字段级",
    statisticFunction: "周期性校验（单字段时间差校验）",
    fields: ["create_datetime"],
    ruleOptions: [{ label: /排序字段/, value: "id" }, { label: /时间差/, value: "!=1天" }],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    description: "v700-时效性-单字段",
  },
  {
    key: "timeliness_multi_field",
    archiveLine: 1932,
    title: "v700-时效性-多字段",
    ...COMMON_SCENARIO,
    ruleCategory: "时效性校验",
    scope: "字段级",
    statisticFunction: "及时性校验（多字段时间差校验）",
    fields: ["id"],
    comparisonFields: ["create_datetime1", "create_datetime2"],
    ruleOptions: [{ label: /时间差/, value: ">=1毫秒" }, { label: /大小关系/, value: "create_datetime1<create_datetime2" }],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    description: "v700-时效性-多字段",
  },
  {
    key: "rationality_trend",
    archiveLine: 1949,
    title: "v700-合理性-趋势",
    ...COMMON_SCENARIO,
    ruleCategory: "合理性校验",
    scope: "字段级",
    statisticFunction: "数据变化趋势",
    fields: ["age"],
    ruleOptions: [{ label: /排序字段/, value: "id" }, { label: /校验方法/, value: "单调递减" }],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }],
    description: "v700-合理性-趋势",
  },
  {
    key: "rationality_field_calculation",
    archiveLine: 1959,
    title: "v700-合理性-字段计算",
    ...COMMON_SCENARIO,
    ruleCategory: "合理性校验",
    scope: "字段级",
    statisticFunction: "字段值计算对比",
    fields: ["age"],
    ruleOptions: [{ label: /对比方法/, value: "计算结果与字段对比" }],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }, { label: "计算逻辑配置", value: "id*age+money" }],
    description: "v700-合理性-字段计算",
  },
  {
    key: "rationality_field_calculation_result",
    archiveLine: 1970,
    title: "v700-合理性-计算结果判断",
    ...COMMON_SCENARIO,
    ruleCategory: "合理性校验",
    scope: "字段级",
    statisticFunction: "字段值计算对比",
    fields: ["age"],
    ruleOptions: [{ label: /对比方法/, value: "计算结果值判断" }, { label: /结果值/, value: ">10000且<=11000" }],
    ruleInputs: [{ label: "过滤条件", value: "id < 100" }, { label: "计算逻辑配置", value: "id*age+money" }],
    description: "v700-合理性-计算结果判断",
  },
  {
    key: "rationality_multi_calculation",
    archiveLine: 1982,
    title: "v700-合理性-多表计算对比",
    ...COMMON_SCENARIO,
    comparisonTableName: "test_schema3",
    ruleCategory: "合理性校验",
    scope: "多表",
    statisticFunction: "多表字段值对比",
    fields: ["id"],
    primaryKeys: ["id"],
    comparisonPrimaryKeys: ["id"],
    ruleOptions: [{ label: /对比方法/, value: "计算结果对比" }, { label: /对比关系/, value: "!=" }],
    ruleInputs: [
      { label: "过滤条件", value: "id < 100" },
      { label: "计算逻辑配置1", value: "(test_return2.id+test_schema3.id)*cast(test_return2.age as double)" },
      { label: "计算逻辑配置2", value: "(cast(test_return2.money as double)-test_return2.id)/test_schema3.id" },
    ],
    description: "v700-合理性-多表计算对比",
  },
  {
    key: "rationality_multi_calculation_result",
    archiveLine: 1997,
    title: "v700-合理性-多表结果判断",
    ...COMMON_SCENARIO,
    comparisonTableName: "test_schema3",
    ruleCategory: "合理性校验",
    scope: "多表",
    statisticFunction: "多表字段值对比",
    fields: ["id"],
    primaryKeys: ["id"],
    comparisonPrimaryKeys: ["id"],
    ruleOptions: [{ label: /对比方法/, value: "计算结果值判断" }, { label: /结果值/, value: ">100或<=400" }],
    ruleInputs: [
      { label: "过滤条件", value: "id < 100" },
      { label: "计算逻辑配置", value: "(test_return2.id+test_schema3.id)*cast(test_return2.age as double)" },
    ],
    description: "v700-合理性-多表结果判断",
  },
] as const;

const MATRIX_SCENARIOS: readonly SparkThriftQualityRuleValidationScenario[] = RULES.map(({ key: _key, ...scenario }) =>
  scenario,
);

for (const datasourceKey of ["sparkthrift", "doris"] as const) {
  test(`C0004 ${datasourceKey} 全量规则矩阵`, async ({ page, step }) => {
    await step(`使用 ${datasourceKey} 配置并执行 38 条规则的通过/不通过分区`, async () => {
      try {
        await expectSparkThriftQualityRuleMatrixContract(
          page,
          `C0004-${datasourceKey}-full-matrix`,
          MATRIX_SCENARIOS.map((scenario) => ({
            ...scenario,
            title: `${scenario.title}-${datasourceKey}`,
            description: `${scenario.description}-${datasourceKey}`,
          })),
          datasourceKey,
        );
      } catch (error) {
        const message = error instanceof Error ? error.stack ?? error.message : String(error);
        await test.info().attach(`${datasourceKey}-全量规则矩阵断言失败详情`, {
          body: message,
          contentType: "text/plain",
        });
        expect.soft(false, `C0004-${datasourceKey} 全量规则矩阵断言失败；详见 Allure 附件`).toBe(true);
      }
    });
  });
}
